300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/api/DeploymentTimeSeriesAnalysisService.java, 300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/cdng/resources/CVNGStepResource.java, 300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/api/CVNGStepTaskService.java, 300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/impl/CVNGStepTaskServiceImpl.java, 300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImplTest.java
=> [feat]: [CVNG-4083]:  added 2 new APIs for group and node filters

400-rest/src/main/java/software/wings/resources/DelegateSetupResourceV3.java
=> [fix]: [DEL-3131]: accountId parameter name fix

dockerization/delegate-proxy/nginx.conf, scripts/jenkins/author-check.sh
=> fix: [ONP-311]: fix delegate-proxy nginx.conf changes for IPv6 support

374-ceng-graphql/src/main/java/io/harness/ccm/graphql/query/recommendation/RecommendationsOverviewQueryV2.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/30098)
=> feat: [CCM-5424]: Exclude Delegate Workload Recommendation

120-ng-manager/src/main/java/io/harness/ng/core/api/impl/SecretCrudServiceImpl.java, 120-ng-manager/src/test/java/io/harness/ng/core/api/impl/SecretCrudServiceImplTest.java, 950-delegate-tasks-beans/src/main/java/io/harness/ng/core/models/SecretTextSpec.java, 990-commons-test/src/main/java/io/harness/rule/OwnerRule.java
=> [fix]: [PL-21563]: Fix for secret ref not visible / masked

300-cv-nextgen/src/main/java/io/harness/cvng/analysis/beans/TransactionMetricInfo.java, 300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/api/DeploymentTimeSeriesAnalysisService.java, 300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentTimeSeriesAnalysisServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/VerificationJobInstanceAnalysisServiceImpl.java, 300-cv-nextgen/src/test/java/io/harness/cvng/BuilderFactory.java, 300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/VerificationJobInstanceAnalysisServiceImplTest.java
=> [feat]: [CVS-9003]: added sorting of txn/metric pairs & resolved duplicate counts

800-pipeline-service/src/main/java/io/harness/pms/helpers/TriggeredByHelper.java, 870-orchestration/src/main/java/io/harness/graph/stepDetail/PmsGraphStepDetailsServiceImpl.java, 870-orchestration/src/test/java/io/harness/graph/stepDetail/PmsGraphStepDetailsServiceImplTest.java, build.properties
=> fix: [PIE-2506]: Fix resume after pause interrupt

800-pipeline-service/src/main/java/io/harness/pms/helpers/TriggeredByHelper.java
=> fix: [CDC-16572]: correctly setting the username in TriggeredByHelper

build.properties
=> fix: hotfix/patch-version: patch update

300-cv-nextgen/src/main/java/io/harness/cvng/core/handler/monitoredService/BaseMonitoredServiceHandler.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/handler/monitoredService/MonitoredServiceSLIMetricUpdateHandler.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/ErrorBudgetRisk.java, 300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java
=> fix: [CVS-8864]: Base delete monitored Service

800-pipeline-service/src/main/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProvider.java, 800-pipeline-service/src/test/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProviderTest.java, 860-orchestration-steps/src/main/java/io/harness/plancreator/approval/ApprovalStagePlanCreatorV2.java
=> [feat]: [PIE-2511]: writing Approval Stage Plan Creator V2

300-cv-nextgen/src/main/java/io/harness/cvng/CVNGAuthenticationFilter.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DeletedCVConfigServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/resources/ServiceLevelObjectiveResource.java, 300-cv-nextgen/src/main/java/io/harness/cvng/verificationjob/entities/VerificationJobInstance.java, 300-cv-nextgen/src/main/resources/stackdriver/dsl/metric-collection.datacollection, 300-cv-nextgen/src/test/java/io/harness/cvng/core/dsl/StackdriverMetricDataCollectionDSLTest.java, 300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/DeletedCVConfigServiceImplTest.java, 300-cv-nextgen/src/test/resources/hoverfly/stackdriver/expected-stackdriver-dsl-output-with-hosts.json, 300-cv-nextgen/src/test/resources/hoverfly/stackdriver/expected-stackdriver-dsl-output.json, 300-cv-nextgen/src/test/resources/src/test/resources/hoverfly/io_harness_cvng_core_dsl_StackdriverMetricDataCollectionDSLTest_testExecute_stackdriverDSL.json, 300-cv-nextgen/src/test/resources/src/test/resources/hoverfly/io_harness_cvng_core_dsl_StackdriverMetricDataCollectionDSLTest_testExecute_stackdriverDSLWithHostDetails.json, 430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/StackdriverDataCollectionInfo.java, 430-cv-nextgen-commons/src/main/java/io/harness/cvng/utils/StackdriverUtils.java, build.properties
=> fix: [CVS-9014]: GCP metric collection DSL bug fix

260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, build.properties
=> fix: [DEL-3211]: Calling dispatchDelegateTaskAsync for Polling tasks 

400-rest/src/main/java/software/wings/beans/infrastructure/instance/Instance.java, 400-rest/src/main/java/software/wings/beans/infrastructure/instance/SyncStatus.java, 400-rest/src/main/java/software/wings/beans/infrastructure/instance/stats/InstanceStatsSnapshot.java
=> feat: [CDC-16686]: export fix for 3 collections required by schwabs

260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, build.properties
=> fix: [DEL-3222]: Fix race in task dispatch workflow

400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/WorkflowExecutionUpdate.java, 865-cg-events/src/main/java/io/harness/beans/event/cg/CgPipelineCompletePayload.java, 865-cg-events/src/main/java/io/harness/beans/event/cg/CgPipelineExecutionPayload.java, 865-cg-events/src/main/java/io/harness/beans/event/cg/CgPipelinePausePayload.java, 865-cg-events/src/main/java/io/harness/beans/event/cg/CgPipelineResumePayload.java, 865-cg-events/src/main/java/io/harness/beans/event/cg/CgPipelineStartPayload.java, 865-cg-events/src/main/java/io/harness/beans/event/cg/pipeline/PipelineExecData.java
=> feat: [CDC-16541]: Changed Pipeline Event Payloads

320-ci-execution/src/main/java/io/harness/stateutils/buildstate/K8BuildSetupUtils.java, 400-rest/src/main/java/software/wings/app/DelegateQueueTask.java, 400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java, 400-rest/src/main/java/software/wings/sm/StateMachineExecutor.java, 400-rest/src/main/resources/metrics/metricDefinitions/delegate_metrics.yaml, 400-rest/src/main/resources/metrics/metricDefinitions/delegate_task_metrics.yaml, 400-rest/src/test/java/software/wings/sm/StateMachineExecutorTest.java, 420-delegate-service/src/main/java/io/harness/metrics/impl/DelegateMetricsServiceImpl.java, 925-access-control-service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml, 925-access-control-service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
=> feat: [CDC-15497]: Added Manual Intervention Event

125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/StepsPlanCreator.java, 860-orchestration-steps/src/main/java/io/harness/plancreator/steps/GenericStepsNodePlanCreator.java
=> feat: [PIE-2530]: Creation of generic stepNode plan creator

260-delegate/src/main/java/software/wings/delegatetasks/pcf/pcftaskhandler/PcfSetupCommandTaskHandler.java, 260-delegate/src/test/java/software/wings/delegatetasks/pcf/pcftaskhandler/PcfSetupCommandTaskHandlerTest.java, 400-rest/src/main/java/software/wings/sm/states/pcf/PcfDeployState.java, 400-rest/src/main/java/software/wings/sm/states/pcf/PcfStateHelper.java, 400-rest/src/main/java/software/wings/sm/states/pcf/PcfSwitchBlueGreenRoutes.java, 400-rest/src/test/java/software/wings/sm/states/pcf/PcfStateHelperTest.java, 400-rest/src/test/java/software/wings/sm/states/pcf/PcfSwitchBlueGreenRoutesTest.java, 930-delegate-tasks/src/main/java/io/harness/delegate/cf/PcfCommandTaskBaseHelper.java, 930-delegate-tasks/src/main/java/io/harness/delegate/cf/PcfRollbackCommandTaskHandler.java, 930-delegate-tasks/src/main/java/io/harness/delegate/cf/PcfRouteUpdateCommandTaskHandler.java, 930-delegate-tasks/src/main/java/io/harness/delegate/cf/apprenaming/AppRenamingOperator.java, 930-delegate-tasks/src/main/java/io/harness/delegate/cf/apprenaming/AppRenamingRollbackOperator.java, 930-delegate-tasks/src/main/java/io/harness/delegate/cf/apprenaming/NonVersionToNonVersionOperator.java, 930-delegate-tasks/src/main/java/io/harness/delegate/cf/apprenaming/NonVersionToVersionOperator.java, 930-delegate-tasks/src/main/java/io/harness/delegate/cf/apprenaming/VersionToNonVersionOperator.java, 930-delegate-tasks/src/test/java/io/harness/delegate/cf/PcfCommandTaskBaseHelperTest.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/pcf/CfInBuiltVariablesUpdateValues.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/response/CfDeployCommandResponse.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/pcf/response/CfRouteUpdateCommandResponse.java, 950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java
[fix]: [CDP-20483]: fix for pcf inbuilt variables
[CDP-20483]: …
=> [fix]: [CDP-20483]: fix for pcf inbuilt variables

390-db-migration/src/main/java/io/harness/migrations/all/AddRingDetailsToDelegateRing.java
=> fix: [DEL-0]: make delegateRing migation idempotent

800-pipeline-service/src/main/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapper.java, 800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java, 800-pipeline-service/src/main/java/io/harness/pms/plan/execution/StagesExecutionHelper.java, 800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/StagesExecutionInfo.java, 800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/PipelineExecutionSummaryDTO.java, 800-pipeline-service/src/main/java/io/harness/pms/plan/execution/handlers/ExecutionSummaryCreateEventHandler.java, 800-pipeline-service/src/test/java/io/harness/pms/pipeline/mappers/PipelineExecutionSummaryDtoMapperTest.java, 800-pipeline-service/src/test/java/io/harness/pms/plan/execution/StagesExecutionHelperTest.java, 800-pipeline-service/src/test/java/io/harness/pms/plan/execution/handlers/ExecutionSummaryCreateEventHandlerTest.java, 860-orchestration-visualization/src/main/java/io/harness/pms/plan/execution/beans/PipelineExecutionSummaryEntity.java, 876-orchestration-beans/src/main/java/io/harness/execution/PlanExecutionMetadata.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/30367)
=> [feat]: [PIE-2466]: Allow stage execution flag needed in execution summary api to hide execution icon from UI

build.properties
=> Branching to release/saas/738xx. New version 739xx

320-ci-execution/src/main/java/io/harness/ci/plan/creator/stage/IntegrationStagePMSPlanCreator.java
=> fix: [CI-3357]: fixed the clone codebase npe

125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformDestroyStep.java, 125-cd-nextgen/src/test/java/io/harness/cdng/provision/terraform/TerraformApplyStepTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/provision/terraform/TerraformDestroyStepTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/provision/terraform/TerraformPlanStepTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/provision/terraform/TerraformStepDataGenerator.java, 125-cd-nextgen/src/test/java/io/harness/cdng/provision/terraform/TerraformStepHelperTest.java, scripts/jenkins/author-check.sh, scripts/jenkins/authorsList.txt
=> [feat]: [CDP-20327]: Integrate artifactory store with terraform Destroy

260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java
=> fix: [DEL-3263]: Changes to remove delegate task limit on agent

860-orchestration-steps/src/main/java/io/harness/steps/resourcerestraint/ResourceRestraintFacilitator.java, 860-orchestration-steps/src/main/java/io/harness/steps/resourcerestraint/service/ResourceRestraintRegistryImpl.java, 882-pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/events/node/facilitate/FacilitatorEventHandler.java
=> fix: [PIE-2612]: Added locking for race condition in resource constraint

860-orchestration-visualization/src/main/java/io/harness/event/StepDetailsUpdateEventHandler.java, build.properties
=> fix: [PIE-2622]: patch graph generation error fix

scripts/jenkins/release-branch.sh
=> feat: [BT-764]: Auto Tagging master branch.

260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java
=> fix: [DEL-3134]: Gracefully fail task in case of vault encryption fails

800-pipeline-service/src/main/java/io/harness/metrics/PipelineTelemetryPublisher.java, 800-pipeline-service/src/test/java/io/harness/metrics/PipelineTelemetryPublisherTest.java, 800-pipeline-service/src/test/java/io/harness/plan/consumers/PartialPlanResponseEventHandlerTest.java, 800-pipeline-service/src/test/java/io/harness/pms/health/HealthResourceTest.java, 800-pipeline-service/src/test/java/io/harness/pms/pipeline/gitsync/PipelineEntityGitSyncHelperTest.java, 800-pipeline-service/src/test/java/io/harness/pms/plan/execution/beans/StagesExecutionInfoTest.java, 800-pipeline-service/src/test/java/io/harness/pms/resourceconstraints/resources/PMSResourceConstraintResourceTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/30601)
=> [techdebt]: [PIE-2566]: Code coverage increase for 800-pipeline-service

125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java
… service step failed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> fix: [PIE-1765]: bug fix for module info not getting populated when service step fails

800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java, 800-pipeline-service/src/test/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelperTest.java, 840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java, 930-ng-core-clients/src/main/java/io/harness/template/remote/TemplateResourceClient.java, build.properties
=> fix: [CDC-0]: add git entity query params to template api calls

260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java
=> fix: [DEL-3278]: Modified task even marker for delegate task events

800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelper.java, 800-pipeline-service/src/test/java/io/harness/pms/pipeline/service/PMSPipelineTemplateHelperTest.java, 840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java, 930-ng-core-clients/src/main/java/io/harness/template/remote/TemplateResourceClient.java
=> fix: [CDS-29173]: add git entity query params to template api calls

300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/LogAnalysisCluster.java, 300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/LogAnalysisServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/TrendAnalysisServiceImpl.java, 300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/LogAnalysisServiceImplTest.java, 430-cv-nextgen-commons/src/main/resources/io/harness/cvng/beans/stackdriver/stackdriver-dashboards-details.datacollection
=> [fix]: [CVS-8991]: reverting changes for compressing

900-git-sync-sdk/src/test/java/io/harness/gitsync/helpers/ScmUserHelperTest.java
=> feat: [PL-22374]: Added UT for Harness_User as Committer.

scripts/terraform/cloudfunctions/ce/ce-cf-resources.tf, scripts/terraform/cloudfunctions/ce/src/python/aws_inventory_init_main.py, scripts/terraform/cloudfunctions/ce/src/python/aws_rds_data_load.py, scripts/terraform/cloudfunctions/ce/src/python/aws_rds_data_main.py, scripts/terraform/cloudfunctions/ce/src/python/bq_schema.py, scripts/terraform/cloudfunctions/ce/src/python/util.py
=> feat: [CCM-5493]: RDS Inventory Management

300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/ChangeEventResource.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/ChangeEventService.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/ChangeEventServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/entities/HeatMap.java, 300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/services/impl/HeatMapServiceImpl.java, 300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/ChangeEventResourceTest.java, 300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/ChangeEventServiceImplTest.java, 430-cv-nextgen-commons/src/main/java/io/harness/cvng/core/services/CVNextGenConstants.java
=> feat: [CVS-8848]: Change event time line API for monitored service.

300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/LogAnalysisServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/TrendAnalysisServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/HostRecordServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/LogRecordServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/ServiceDependencyServiceImpl.java
=> fix: [CVS-8877]: saving records in batches

200-functional-test/src/test/java/io/harness/functional/yaml/YamlFunctionalTestHelper.java, 400-rest/src/main/java/software/wings/beans/yaml/FullSyncChangeset.java, 400-rest/src/main/java/software/wings/beans/yaml/FullSyncError.java, 400-rest/src/main/java/software/wings/service/impl/yaml/YamlDirectoryServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlCloneServiceImpl.java, 400-rest/src/main/java/software/wings/service/intfc/yaml/YamlDirectoryService.java, 400-rest/src/main/java/software/wings/service/intfc/yaml/YamlGitService.java, 400-rest/src/test/java/software/wings/service/impl/yaml/service/YamlCloneServiceImplTest.java
=> fix: [PL-21808]: Full Sync should record error

280-batch-processing/src/main/java/io/harness/batch/processing/service/impl/InstanceDataBulkWriteServiceImpl.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/30745)
=> fix: [CCM-5519]: SyncEvent stopping new Pods

952-scm-java-client/src/main/java/io/harness/impl/scm/ScmGitProviderMapper.java
=> [fix]: [CI-0]: Fix NPE in SCM

310-ci-manager/ci-manager-config.yml
=> feat: [CI-3365]: Added files for versioning support 

400-rest/src/main/java/software/wings/helpers/ext/azure/AzureHelperService.java, 400-rest/src/main/java/software/wings/service/impl/instance/AzureInstanceHandler.java
(cherry picked from commit 55f02b64770bd0a4e6cdccee79072aeab3c4bf3e)
---
This change is [<img …
=> [feat]: [CDS-15080]: Azure instance sync checking

930-ng-license-manager/src/main/java/io/harness/licensing/LicenseModule.java, 930-ng-license-manager/src/main/java/io/harness/licensing/services/DefaultLicenseServiceImpl.java, 930-ng-license-manager/src/test/java/io/harness/licensing/services/DefaultLicenseServiceImplTest.java, build.properties
=> fix: [GTM-729]: License API is failing after latest master deployment

390-db-migration/src/main/java/io/harness/migrations/MigrationBackgroundList.java, 390-db-migration/src/main/java/io/harness/migrations/all/DeleteFailedNgDelegateTokenMigration.java, 955-outbox-sdk/src/main/java/io/harness/outbox/OutboxEvent.java
=> fix: [DEL-3406]: delete failed ng delegate token audit events

800-pipeline-service/src/test/java/io/harness/pms/expressions/PMSExpressionEvaluatorTest.java, 860-orchestration-visualization/src/main/java/io/harness/consumers/GraphUpdateDispatcher.java, 860-orchestration-visualization/src/test/java/io/harness/consumers/GraphUpdateDispatcherTest.java, 870-orchestration/src/main/java/io/harness/engine/executions/node/NodeExecutionServiceImpl.java, 870-orchestration/src/main/java/io/harness/engine/expressions/NodeExecutionsCache.java, 870-orchestration/src/main/java/io/harness/engine/expressions/functors/NodeExecutionMap.java, 870-orchestration/src/test/java/io/harness/engine/expressions/NodeExecutionsCacheTest.java, 870-orchestration/src/test/java/io/harness/engine/expressions/functors/NodeExecutionValueTest.java
=> fix: [PIE-2981]: Fix rollback issue in nextgen

800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java, 800-pipeline-service/src/test/java/io/harness/pms/plan/execution/ExecutionDetailsResourceTest.java
=> fix: [PIE-2988]: Add a v2 api for graph

380-cg-graphql/src/test/java/software/wings/graphql/datafetcher/workflow/WorkflowDataFetcherTest.java, 400-rest/src/main/java/software/wings/graphql/datafetcher/workflow/WorkflowDataFetcher.java
=> fix: [CDS-25820]: workflowByName displays error message

125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/resources/CDNGPipelineConfigurationResource.java, 125-cd-nextgen/src/main/resources/failureStrategyYaml/failurestrategy.yaml, scripts/jenkins/author-check.sh, scripts/jenkins/authorsList.txt
=> feat: [CDS-34628]: Added CD Stage yaml snippet for failure strategies

340-ce-nextgen/src/main/resources/yamltemplates/cost-optimisation-crd.yaml.ftl, 340-ce-nextgen/src/test/resources/yaml/autostopping-only.yaml, 340-ce-nextgen/src/test/resources/yaml/visibility-and-optimization.yaml
=> feat: [CCM-5844]: Changes in k8s connector yaml for admission webhooks

960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java
=> fix: [DEL-3392]: Terminate delegate process forcefully if kill command fails

400-rest/src/main/resources/delegatetemplates/common/delegate-environment.ftl, 400-rest/src/main/resources/delegatetemplates/harness-ecs-delegate.json.ftl, 400-rest/src/main/resources/delegatetemplates/harness-ng-delegate-docker-compose.yaml.ftl, 400-rest/src/main/resources/delegatetemplates/launch-harness-delegate-without-name.sh.ftl, 400-rest/src/main/resources/delegatetemplates/launch-harness-delegate.sh.ftl, 400-rest/src/main/resources/delegatetemplates/launch-harness-ng-delegate.sh.ftl, 400-rest/src/test/resources/expectedDockerCompose.yaml, 400-rest/src/test/resources/expectedHarnessDelegate.yaml, 400-rest/src/test/resources/expectedHarnessDelegateNgClusterAdmin.yaml, 400-rest/src/test/resources/expectedHarnessDelegateNgClusterViewer.yaml, 400-rest/src/test/resources/expectedHarnessDelegateNgNamespaceAdmin.yaml, 400-rest/src/test/resources/expectedHarnessDelegateNgWithoutDescription.yaml, 400-rest/src/test/resources/expectedHarnessDelegateWithCiEnabled.yaml, 400-rest/src/test/resources/expectedLaunchHarnessDelegate.sh, 400-rest/src/test/resources/expectedLaunchHarnessDelegateWithoutName.sh
This reverts commit f81a216f05685d10bd24e2320ade9024f178071f.
---
This change is [<img …
=> feat: [DEL-3155]: remove use_cdn phase3

800-pipeline-service/src/main/java/io/harness/PipelineServiceApplication.java
=> [feat]: [PL-23469]: Adds x-api-key telemetry filter in pipeline service

260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java
=> [fix]: [DEL-3237]: Delegate change to support patch versions in PR.

300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/cvnglogs/ApiCallLogRecord.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/cvnglogs/CVNGLogRecord.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/entities/cvnglogs/ExecutionLogRecord.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/CVNGLogServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/DataCollectionTaskServiceImpl.java, 300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/CVNGLogServiceImplTest.java
=> [feat]: [CVS-9349]: enhanced verify-step/logs end point

120-ng-manager/src/main/java/io/harness/ng/core/envGroup/beans/EnvironmentGroupConfig.java, 120-ng-manager/src/main/java/io/harness/ng/core/envGroup/beans/EnvironmentGroupEntity.java, 120-ng-manager/src/main/java/io/harness/ng/core/gitSync/EnvironmentGroupEntityGitSyncHelper.java, 120-ng-manager/src/main/java/io/harness/serializer/morphia/NGMorphiaRegistrars.java, 125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, 320-ci-execution/src/test/resources/recaster/alias/alias.txt, 800-pipeline-service/src/test/resources/recaster/alias/alias.txt, 860-orchestration-steps/src/test/resources/recaster/alias/alias.txt, 860-orchestration-visualization/src/test/resources/recaster/alias/alias.txt, 870-orchestration/src/test/resources/recaster/alias/alias.txt, 950-ng-core/src/main/java/io/harness/serializer/morphia/NGCoreMorphiaClassesRegistrar.java
=> feat: [PIE-3030]: Making EnvironmentGroup entity implement git sync

260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/31328)
=> [fix]: [DEL-3484]: don't restart watcher and delegate if delegate is not able to get watcher version

125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-default-with-verify.yaml, 125-cd-nextgen/src/main/resources/executionStrategyYaml/ssh-default.yaml
=> [feat]: [CDS-34617]: add default ssh execution strategy yaml

400-rest/src/main/java/software/wings/service/impl/yaml/GitClientImpl.java, 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/K8sTaskHelperBase.java, 930-delegate-tasks/src/test/java/io/harness/delegate/task/k8s/K8sTaskHelperBaseTest.java, 960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java, 980-commons/src/main/java/io/harness/filesystem/FileIo.java, 980-commons/src/test/java/io/harness/filesystem/FileIoTest.java
=> fix: [CDS-34761]: Fix processing .git folder and reading full file

dockerization/delegate/immutable-scripts/proxy_setup.sh
=> fix: [DEL-3444]: properly export proxy config for immutable delegate

800-pipeline-service/src/test/java/io/harness/mongo/PmsMongoIndexesTest.java
=> fix: [CI-3772]: remove unwanted code

920-ng-signup/src/main/java/io/harness/signup/services/impl/SignupServiceImpl.java, 920-ng-signup/src/test/java/io/harness/signup/services/SignupServiceImplTest.java, 930-ng-license-manager/src/main/java/io/harness/licensing/services/DefaultLicenseServiceImpl.java, 970-telemetry-beans/src/main/java/io/harness/TelemetryConstants.java
=> [feat]: [GTM-661]: Added a dummy user to represent an account for telemetry

800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PipelineExecutor.java, 800-pipeline-service/src/main/java/io/harness/pms/plan/execution/RetryExecutionHelper.java, 800-pipeline-service/src/test/java/io/harness/pms/plan/execution/RetryExecuteHelperTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/31303)
=> [feat]: [PIE-2725]: Enable retry for selective stage executions

WORKSPACE, product/ci/scm/go.mod, product/ci/scm/go.sum
=> [fix]: [CI-3723]: Updated jwt-go dependency

960-yaml-sdk/src/main/java/io/harness/yaml/utils/SchemaValidationUtils.java, 960-yaml-sdk/src/main/java/io/harness/yaml/validator/YamlSchemaValidator.java
=> [feat]: [PIE-2727]: filtering schema validation messages

300-cv-nextgen/src/main/java/io/harness/cvng/CVServiceModule.java, 300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/resources/ErrorTrackingDashboardResource.java, 300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/services/api/ErrorTrackingDashboardService.java, 300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/services/impl/ErrorTrackingDashboardServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/services/impl/LogDashboardServiceImpl.java, 300-cv-nextgen/src/test/java/io/harness/cvng/dashboard/services/impl/ErrorTrackingDashboardServiceImplTest.java, 300-cv-nextgen/src/test/java/io/harness/cvng/dashboard/services/impl/LogDashboardServiceImplTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/31433)
=> feat: [SRM-9399]: filtering Error Tracking logs for live monitoring

430-cv-nextgen-commons/src/main/java/io/harness/cvng/beans/ErrorTrackingDataCollectionInfo.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/31474)
=> feat: [SRM-9518]: Error Tracking url structure change

dockerization/delegate/Dockerfile-immutable
=> fix: [DEL-3553]: Fix labeling

400-rest/src/main/java/software/wings/dl/exportimport/WingsMongoExportImport.java
=> fix: [SPG-29]: Export not working when updated after field is in query

450-ce-views/src/main/java/io/harness/ccm/views/businessMapping/dao/BusinessMappingDao.java, scripts/jenkins/authorsList.txt
=> [fix]: [CCM-7125]: Fixed Business Mapping Update API call

320-ci-execution/src/test/java/io/harness/stateutils/buildstate/ConnectorUtilsTest.java
=> Fixed CI tests

810-ng-triggers/src/main/java/io/harness/ngtriggers/service/impl/NGTriggerServiceImpl.java, 960-api-services/src/main/java/io/harness/git/GitClientHelper.java, 960-api-services/src/test/java/io/harness/git/GitClientHelperTest.java
=> fix: [CI-3604]: fixed issue with www in url

300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImpl.java, 300-cv-nextgen/src/test/java/io/harness/cvng/analysis/services/impl/DeploymentLogAnalysisServiceImplTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/31821)
=> feat: [SRM-9874]: Exclude Error Tracking from the verify log view

889-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java, 889-yaml-commons/src/test/java/io/harness/pms/merger/helpers/MergeHelperTest.java, 889-yaml-commons/src/test/resources/emojiExp1.txt, 889-yaml-commons/src/test/resources/emojiExp2.txt
=> fix: [CI-3598]: fixed emojis in pr

access-control/build.properties, access-control/service/src/main/java/io/harness/accesscontrol/acl/api/ACLResourceImpl.java, access-control/service/src/test/java/io/harness/accesscontrol/acl/api/ACLResourceImplTest.java
=> fix: [PL-24555]: Fix NullPointer in ACL Check API

280-batch-processing/src/main/java/io/harness/batch/processing/billing/service/BillingCalculationService.java, 280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, 280-batch-processing/src/test/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTaskletTest.java, 490-ce-commons/src/main/java/io/harness/ccm/commons/service/impl/InstanceDataServiceImpl.java, 490-ce-commons/src/main/java/io/harness/ccm/commons/service/intf/InstanceDataService.java
=> [Fix]: [CCM-7317]: Handle duplicate key

889-yaml-commons/src/main/java/io/harness/pms/yaml/validation/RuntimeInputValuesValidator.java
=> [fix]: [CDS-34966]: Showed List of allowed values on the error message

125-cd-nextgen/src/test/java/io/harness/cdng/aws/service/AwsResourceServiceImplTest.java, 960-api-services/src/main/java/io/harness/aws/AWSCloudformationClientImpl.java, 960-api-services/src/test/java/io/harness/aws/AWSCloudformationClientTest.java
=> [feat]: [CDS-36512]: Add new unittests

access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
**Gitops Admin Role**
**Project Viewer**
**Project Admin**
**Account Viewer**
**Account Admin**
**Org Viewer**
**Org Admin**
Also added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/32276)
=> feat: [CDS-35990]: Managed roles for gitops

120-ng-manager/config.yml, 878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/common/WithDelegateSelector.java, build.properties
=> [CDS-36447 ]: Add jsonIgnore to delegate selector field

280-batch-processing/src/main/java/io/harness/batch/processing/billing/writer/InstanceBillingDataTasklet.java, 280-batch-processing/src/main/java/io/harness/batch/processing/dao/impl/InstanceDataDaoImpl.java, 280-batch-processing/src/main/java/io/harness/batch/processing/dao/intfc/InstanceDataDao.java
=> [Fix]: [CCM-7236]: Correct instance state and active instance itr time

scripts/jenkins/portal-openjdk-bazel.sh
=> feat: [BT-1090]: Adding Condition for signing for feature pipelines.

400-rest/src/main/java/software/wings/helpers/ext/jenkins/JenkinsImpl.java
=> fix: [CDS-36496]: Bitbucket folders not showing on jenkins setup

125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactConfigToDelegateReqMapper.java, 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapper.java, 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/mappers/ArtifactoryResourceMapper.java, 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/artifactory/service/ArtifactoryResourceServiceImpl.java, 125-cd-nextgen/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java, 125-cd-nextgen/src/main/java/io/harness/polling/bean/artifact/ArtifactoryRegistryArtifactInfo.java, 125-cd-nextgen/src/test/java/io/harness/cdng/artifact/mappers/ArtifactResponseToOutcomeMapperTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/artifact/resources/artifactory/mappers/ArtifactoryResourceMapperTest.java, 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHandler.java, 930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryArtifactTaskHelper.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryBaseArtifactDelegateRequest.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryDockerArtifactDelegateRequest.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/artifactory/ArtifactoryGenericArtifactDelegateRequest.java, 950-delegate-tasks-beans/src/main/java/io/harness/serializer/kryo/DelegateTasksBeansKryoRegister.java, 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryClientImpl.java, 960-api-services/src/main/java/io/harness/artifactory/ArtifactoryNgServiceImpl.java, 960-api-services/src/main/java/io/harness/artifactory/service/ArtifactoryRegistryService.java
=> Serverless aritfactory review changes

930-ng-license-manager/src/main/java/io/harness/licensing/api/resource/LicenseResource.java, 930-ng-license-manager/src/main/java/io/harness/licensing/services/DefaultLicenseServiceImpl.java, 930-ng-license-manager/src/main/java/io/harness/licensing/services/LicenseCrudService.java, 930-ng-license-manager/src/main/java/io/harness/repositories/ModuleLicenseRepository.java, 930-ng-license-manager/src/test/java/io/harness/licensing/services/DefaultLicenseServiceImplTest.java, 960-ng-license-beans/src/main/java/io/harness/licensing/remote/NgLicenseHttpClient.java, 970-ng-commons/src/main/java/io/harness/NGCommonEntityConstants.java
=> feat: [GTM-787]: API to get enabled module licenses after specific time

800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java, 800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineService.java, 800-pipeline-service/src/main/java/io/harness/pms/pipeline/service/PMSPipelineServiceImpl.java, 800-pipeline-service/src/main/java/io/harness/pms/template/VariablesServiceImpl.java, 800-pipeline-service/src/main/java/io/harness/pms/variables/VariableCreatorMergeService.java, 800-pipeline-service/src/test/java/io/harness/pms/pipeline/PipelineResourceTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/32801)
=> [techdebt]: [PIE-3640]: Move variable response creators

950-wait-engine/src/main/java/io/harness/waiter/WaitInstance.java, 950-wait-engine/src/main/java/io/harness/waiter/WaitNotifyEngine.java
=> fix: [CDS-36568]: Change TTL of WaitInstance to 90 days; Add log when a WaitInstance are not found to help us in future troubleshooting

260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java
=> feat: [DEL-3938]: change to debug logs

260-delegate/src/main/java/io/harness/delegate/app/DelegateAgentApplication.java, 260-delegate/src/main/java/io/harness/delegate/app/DelegateApplication.java, 260-delegate/src/main/java/io/harness/delegate/app/modules/DelegateAgentModule.java, 380-cg-graphql/src/test/java/software/wings/graphql/datafetcher/trigger/TriggerConditionControllerTest.java, 400-rest/src/main/java/io/harness/grpc/DelegateServiceClassicGrpcClientModule.java, 400-rest/src/test/java/software/wings/helpers/ext/url/SubdomainUrlHelperIntfcTest.java, 400-rest/src/test/java/software/wings/security/authentication/AuthenticationManagerTest.java, 400-rest/src/test/java/software/wings/service/impl/PreDeploymentCheckerTest.java, 400-rest/src/test/java/software/wings/signup/OnpremSignupHandlerTest.java, 940-feature-flag/src/test/java/io/harness/ff/FeatureFlagTest.java, 960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java, 970-grpc/src/main/java/io/harness/grpc/client/ManagerGrpcClientModule.java, build.properties
=> fix: [DEL-3982]: Disable perpetual task worker for all on-prem

scripts/terraform/cloudfunctions/ce/src/python/aws_billing_bq_main.py, scripts/terraform/cloudfunctions/ce/src/python/bq_schema.py
=> feat: [CCM-7437]: NetAmortisedCost support in AWS

136-git-sync-manager/src/main/java/io/harness/gitsync/core/beans/GitFullSyncConfig.java
=> [fix]: [PL-25083]: Remove the last updated by which is not required

320-ci-execution/src/main/java/io/harness/stateutils/buildstate/K8BuildSetupUtils.java
=> fix: [CI-3626]: namespace and connector id modifiaction. 

300-cv-nextgen/src/main/java/io/harness/cvng/analysis/beans/LiveMonitoringLogAnalysisRadarChartClusterDTO.java, 300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/LogAnalysisResult.java, 300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/beans/AnalyzedRadarChartLogDataDTO.java, 300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/beans/AnalyzedRadarChartLogDataWithCountDTO.java, 300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/resources/LogDashboardResource.java, 300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/services/api/LogDashboardService.java, 300-cv-nextgen/src/main/java/io/harness/cvng/dashboard/services/impl/LogDashboardServiceImpl.java, 300-cv-nextgen/src/test/java/io/harness/cvng/dashboard/services/impl/LogDashboardServiceImplTest.java, 400-rest/src/main/java/software/wings/beans/sso/LdapSettingsMapper.java, 400-rest/src/main/java/software/wings/helpers/ext/k8s/K8sManagerHelper.java, 400-rest/src/main/java/software/wings/utils/HelmChartSpecificationMapper.java, 400-rest/src/main/java/software/wings/utils/ManifestFileMapper.java, 930-delegate-tasks/src/main/java/software/wings/beans/ConfigFileDto.java, 930-delegate-tasks/src/main/java/software/wings/beans/appmanifest/ManifestFileDTO.java, 930-delegate-tasks/src/main/java/software/wings/beans/command/HelmDummyCommandUnitConstants.java, 930-delegate-tasks/src/main/java/software/wings/beans/container/HelmChartSpecificationDTO.java, 930-delegate-tasks/src/main/java/software/wings/beans/sso/LdapSettingsDTO.java, 930-ng-core-clients/src/main/java/io/harness/variable/VariableClientModule.java, 930-ng-core-clients/src/main/java/io/harness/variable/remote/VariableClient.java, 930-ng-core-clients/src/main/java/io/harness/variable/remote/VariableHttpClientFactory.java, 980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler/CILiteEngineExceptionHandler.java, 980-commons/src/main/java/io/harness/exception/ngexception/CILiteEngineException.java, build.properties, dockerization/cv-nextgen/scripts/replace_configs.sh
=> feat: [SRM-10575]: Template replace key in CV Config and Updated Response of new Radar Chart APIs

dockerization/delegate/immutable-scripts/token_generator.sh, dockerization/delegate/scripts/token_generator.sh
=> fix: [DEL-3979]: Shell script to generating new delegate auth token

120-ng-manager/src/main/java/io/harness/telemetry/helpers/ConnectorInstrumentationHelper.java
=> feat: [GTM-1036]: Updated connector created telemetry event name

960-yaml-sdk/src/main/java/io/harness/yaml/utils/SchemaValidationUtils.java, 960-yaml-sdk/src/main/java/io/harness/yaml/validator/EnumCodeSchemaHandler.java, 960-yaml-sdk/src/main/java/io/harness/yaml/validator/YamlSchemaValidator.java
…pe message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> [fix]: [PIE-3690]: Removing FQN from message and filtering invalidType messages

310-ci-manager/ci-manager-config.yml
=> fix: [CI-4462]: Biweekly release of addon and le

930-delegate-tasks/src/main/java/io/harness/delegate/task/cloudformation/CloudformationTaskNG.java
[fix]: [CDS-34216]: fix logging
[CDS-34216]: https://harness.atlassian.net/browse/CDS-34216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/33257)
=> [fix]: [CDS-34216]: fix logging

878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/33471)
=> fix: [PIE-3719]: Fix failing tests

878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java, 970-ng-commons/src/main/java/io/harness/beans/SwaggerConstants.java
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/33473)
=> fix: [PIE-3719]: Fix the swaggerConstants file

400-rest/src/main/java/software/wings/service/impl/yaml/handler/artifactstream/DockerArtifactStreamYamlHandler.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/33495)
=> fix: [CDS-37956]: fix changing collection value from yaml for docker artifact stream

320-ci-execution/src/test/java/io/harness/stateutils/buildstate/ConnectorUtilsTest.java
<details>
</details>
<details> …
=> fix: [CI-4571]: ignore test

126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustom.java, 126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java, 126-instance/src/main/java/io/harness/service/instance/InstanceService.java, 126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java, 126-instance/src/main/java/io/harness/service/instancesync/InstanceSyncServiceImpl.java
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/33515)
=> fix: [CDS-37683]: Removing unnecessary OR condition based on timestamp

953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java
<details>
</details>
<details> …
=> fix: [CDS-38080]: fix npe on getting fqn from yamlNode

400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceImpl.java
Please read [go/trigger-cmd](https://harness.atlassian.net/wiki/spaces/BT/pages/21082441647/PR+Checks) to re-trigger PR Checks using Github comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/33458)
=> feat: [CDS-34125]: cloudformation template expressions fix

980-commons/BUILD.bazel
`990-commons-test:abstract-module` has only two classes which are only used in tests in 990-commons-test and 400-rest.
<details>
</details>
<details>
- TI-bootstrap1: …
=> techdebt: [DEL-4168]: Remove 990-commons-test:abstract-module target from 980-commons:module

.github/CODEOWNERS
This change adds some of the delegate team members as owners of all BUILD.bazel files of projects that //260-delegate:module depends on.
The list was retrieved using:
`bazel query 'filter("^[^@]", deps(//260-delegate:module))' --output package | grep -v "/proto" | grep -v "/resources"`
The goal of this change is to avoid unnecessary dependencies being added, allowing us to:
- Maintain the delegate JAR size
- Avoid Vulnerable libraries being added (In the future)
As part of reducing the overall delegate footprint, we are continuously removing unnecessary dependencies.
If a project is removed as 260-delegate:module dependency, we will remove ourselves from the owner list for the BUILD.bazel file.
<details>
- …
=> techdebt: [DEL-4161]: Add delegate team as code owner of BUILD.bazel files

access-control/build/container/Dockerfile-accesscontrol-service-jenkins-k8-openjdk, dockerization/ce-nextgen/Dockerfile-ce-nextgen-jenkins-k8-openjdk, dockerization/change-data-capture/Dockerfile-change-data-capture-jenkins-k8-openjdk, dockerization/ci-manager/Dockerfile-ci-manager-jenkins-k8-openjdk, dockerization/cv-nextgen/Dockerfile-verification-jenkins-k8-openjdk, dockerization/manager/Dockerfile-manager-jenkins-k8-openjdk, dockerization/migrator/Dockerfile-manager-jenkins-k8-openjdk, dockerization/ng-manager/Dockerfile-ng-manager-jenkins-k8-openjdk, dockerization/pipeline-service/Dockerfile-pipeline-service-jenkins-k8-openjdk, dockerization/platform-service/Dockerfile-platform-service-jenkins-k8-openjdk, dockerization/template-service/Dockerfile-template-service-jenkins-k8-openjdk, dockerization/verification/Dockerfile-verification-jenkins-k8-openjdk
<details>
</details>
<details> …
=> [PL-25507]: Update SMP docker files with jdk11 image

300-cv-nextgen/src/main/java/io/harness/cvng/cdng/services/impl/CVNGPlanCreator.java
<details>
</details>
<details> …
=> fix: [SRM-10656]: manual intervention with default rollback.

136-git-sync-manager/src/main/java/io/harness/gitsync/common/remote/GitSyncSettingsResource.java
Fix Error: "postGitSyncSetting" is duplicated in your schema definition!
<details>
</details>
<details>
- …
=> fix: [CDS-0]: Fix git sync endpoints nicknames

300-cv-nextgen/src/main/java/io/harness/cvng/analysis/beans/ServiceGuardTxnMetricAnalysisDataDTO.java, 300-cv-nextgen/src/main/java/io/harness/cvng/analysis/beans/TimeSeriesAnomaliesDTO.java, 300-cv-nextgen/src/main/java/io/harness/cvng/analysis/entities/TimeSeriesShortTermHistory.java, 300-cv-nextgen/src/main/java/io/harness/cvng/analysis/services/impl/TimeSeriesAnalysisServiceImpl.java, 300-cv-nextgen/src/main/java/io/harness/cvng/core/services/api/ExecutionLogger.java
<details>
</details>
<details> …
=> [fix]: [SRM-10661]: fix issue with upper case metric identifier

320-ci-execution/src/main/java/io/harness/ci/integrationstage/VmInitializeStepUtils.java, 320-ci-execution/src/test/java/io/harness/integrationstage/BuildJobEnvInfoBuilderTest.java, 325-sto-beans/src/test/resources/schema/SecurityStage/all.json, 330-ci-beans/src/main/java/io/harness/beans/yaml/extended/infrastrucutre/OSType.java, 330-ci-beans/src/test/resources/schema/IntegrationStage/all.json
<details>
</details>
<details> …
=> [fix]: [CI-4598]: Update osx enum to MacOS

scripts/jenkins/portal-openjdk-bazel.sh
<details>
</details>
<details> …
=> [fix]: [PL-25608]: Feature build fix

260-delegate/src/main/java/io/harness/perpetualtask/datacollection/k8s/ChangeIntelConfigMapHandler.java
<details>
</details>
<details> …
=> [fix]: [SRM-10664]: fix null pointer issue for kubernetes events

280-batch-processing/src/main/java/io/harness/batch/processing/anomalydetection/SlackNotificationsTasklet.java
<details>
</details>
<details> …
=> [Fix]: [CCM-7828]: Disable anomaly slack notification

800-pipeline-service/src/main/java/io/harness/pms/approval/jira/JiraApprovalHelperServiceImpl.java
<details>
</details>
<details> …
=> [fix]: [CDC-35335]: Added logs for jira approval step

840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsRefreshHelper.java, 840-template-service/src/main/java/io/harness/template/helpers/TemplateInputsValidator.java, 840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java, 840-template-service/src/main/java/io/harness/template/helpers/TemplateReferenceHelper.java, 953-yaml-commons/src/main/java/io/harness/template/yaml/TemplateRefHelper.java
<details>
</details>
<details> …
=> fix: [CDS-38412]: fix infinite recursion for templates resolution

bazelrc.common
<details>
</details>
<details> …
=> test toolchain

136-git-sync-manager/src/test/java/io/harness/gitsync/GitSyncTestRule.java, 260-delegate/src/test/resources/kryo-registrations.txt
<details>
</details>
<details> …
=> fix: [DEL-0]: Fix on git sync test failures on post jdk 11 upgrade

300-cv-nextgen/src/main/resources/prometheus/dsl/metric-collection.datacollection, 300-cv-nextgen/src/test/java/io/harness/cvng/core/dsl/PrometheusDataCollectionDSLTest.java, 300-cv-nextgen/src/test/resources/hoverfly/prometheus/expected-prometheus-dsl-output.json, 300-cv-nextgen/src/test/resources/src/test/resources/hoverfly/io_harness_cvng_core_dsl_PrometheusDataCollectionDSLTest_testExecute_prometheusDSLWithHostData.json, build.properties
<details>
</details>
<details> …
=> fix: [SRM-10716]: Prometheus service instance query, remove filter for hot fix

320-ci-execution/src/main/java/ci/pipeline/execution/PipelineExecutionUpdateEventHandler.java, 320-ci-execution/src/main/java/io/harness/common/CICommonEndpointConstants.java, 320-ci-execution/src/main/java/io/harness/logserviceclient/CILogServiceClient.java, 320-ci-execution/src/main/java/io/harness/logserviceclient/CILogServiceUtils.java, 320-ci-execution/src/test/java/io/harness/logserviceclient/CILogServiceUtilsTest.java
<details>
</details>
<details> …
=> [fix]: [CI-3495]: Close log stream with prefixes during cleanup call

260-delegate/src/test/resources/kryo-registrations.txt
added PrivateDnsNameOptionsResponse in kryo-registrations.txt
<details>
</details>
<details> …
=> [fix]: [CDS-35585]: added PrivateDnsNameOptionsResponse in kryo-registrations.txt

build.properties, clients/notification/src/main/java/io/harness/notification/channeldetails/MSTeamChannel.java, clients/notification/src/main/java/io/harness/notification/channeldetails/PagerDutyChannel.java, clients/notification/src/main/java/io/harness/notification/channeldetails/SlackChannel.java, platform-service/build.properties
NPE fix for the notification service client
<details>
</details>
<details>
- …
=> fix: [PL-22129]: Fix NPE for notification service client

260-delegate/src/test/java/software/wings/delegatetasks/aws/ecs/ecstaskhandler/EcsBlueGreenRoute53DNSWeightHandlerTest.java, 930-delegate-tasks/src/main/java/software/wings/delegatetasks/aws/ecs/ecstaskhandler/EcsBlueGreenRoute53DNSWeightHandler.java
<details>
</details>
<details> …
=> [fix]: [CDS-4024]: ECS BG: Adding logic to downscale new service on rollback

925-subscription-service/src/main/java/io/harness/subscription/resource/SubscriptionResource.java, 925-subscription-service/src/main/java/io/harness/subscription/services/SubscriptionService.java, 925-subscription-service/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java, 950-subscription-beans/src/main/java/io/harness/subscription/constant/Prices.java
<details>
</details>
<details> …
=> fix: [GTM-1192]: Use ModuleType for subscription price endpoint

280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/util/InstanceMetaDataUtils.java, 280-batch-processing/src/main/java/io/harness/batch/processing/writer/constants/K8sCCMConstants.java
<details>
</details>
<details> …
=> fix: [CCM-7913]: NodePool Name in Instance Info

125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java, 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java, 125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/beans/CDPipelineModuleInfo.java
- add environment, environment group to ModuleInfo in case of a gitops pr pipeline
- only publish env name when number of environments is 1
<details>
</details>
<details>
- …
=> feat: [CDS-38615]: Adding env info in moduleInfo for Gitops PR Pipeline Execution

800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java, 800-pipeline-service/src/main/java/io/harness/pms/plan/execution/beans/dto/ExecutionDataResponseDTO.java, 800-pipeline-service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionService.java, 800-pipeline-service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java
<details>
</details>
<details> …
=> [feat]: [PIE-2382]: Added get yaml for executions

840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java
<details>
</details>
<details> …
=> [fix]: [CDS-36839]: Improved Error Message

120-ng-manager/src/main/java/io/harness/ng/core/event/ProjectEntityCRUDStreamListener.java, 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImpl.java, 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java, 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/ServiceOverrideService.java, 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImpl.java, 127-cd-nextgen-entities/src/test/java/io/harness/cdng/CDNGEntitiesTestRule.java, 127-cd-nextgen-entities/src/test/java/io/harness/cdng/gitops/service/ClusterServiceTest.java, 127-cd-nextgen-entities/src/test/java/io/harness/ng/core/environment/services/impl/EnvironmentServiceImplTest.java, 127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImplTest.java, 127-cd-nextgen-entities/src/test/java/io/harness/ng/core/serviceoverride/services/impl/ServiceOverrideServiceImplTest.java
- delete when proj is deleted
- delete when env is deleted
- delete when service is deleted
<details>
</details>
<details>
- TI-bootstrap2: …
=> feat: [CDS-37891]: NG Service Overrides entity cascade deletion 

840-template-service/src/main/java/io/harness/template/helpers/TemplateMergeHelper.java, 840-template-service/src/test/java/io/harness/template/helpers/TemplateMergeHelperTest.java, 840-template-service/src/test/resources/pipeline-temp-inf-rec.yaml, 840-template-service/src/test/resources/stage-temp-inf-rec.yaml
<details>
</details>
<details> …
=> [fix]: [CDS-37153]: fixed infinite recursion

125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGModuleInfoProvider.java, 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/envGroup/EnvGroupPlanCreatorHelper.java, 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/gitops/ClusterPlanCreatorUtils.java, 125-cd-nextgen/src/main/java/io/harness/cdng/environment/helper/EnvironmentPlanCreatorConfigMapper.java, 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/ClusterStepParameters.java, 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/EnvClusterRefs.java, 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersOutcome.java, 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java, 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/Metadata.java, 125-cd-nextgen/src/test/java/io/harness/cdng/creator/CDNGModuleInfoProviderTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/environment/helper/EnvironmentPlanCreatorConfigMapperTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/gitops/steps/GitopsClustersStepTest.java
Add environment name to stage module info for a gitops PR pipeline. 
<details>
</details>
<details>
- …
=> feat: [CDS-38615]: Adding env info in stage moduleInfo for Gitops PR Pipeline Execution

127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/mappers/EnvironmentMapper.java, 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/yaml/NGEnvironmentInfoConfig.java
throw error when duplicate variables exist in the env. Using javax validation for the same
<details>
</details>
<details>
- TI-bootstrap2: …
=> feat: [CDS-37242]: NG Duplicate env variable validation

dockerization/base-images/apm/create-feature-builds-with-apm-bins.sh
<details>
</details>
<details> …
=> feat: [BT-1433]: Handling apm for feature builds.

.github/CODEOWNERS, 860-orchestration-steps/src/test/java/io/harness/pms/sdk/core/pipeline/variables/StepGroupVariableCreatorTest.java, 860-orchestration-steps/src/test/resources/pipelineVariableCreatorUuidJson.yaml, 953-yaml-commons/src/main/java/io/harness/when/beans/StepWhenCondition.java
Adding uuid to step when condition and correcting code owners for other services.
<details>
</details>
<details>
- TI-bootstrap2: `trigger …
=> fix: [PIE-4179]: Adding uuid to step when condition and correcting code owners for other services.

product/ci/addon/gojunit/ingest.go, product/ci/addon/gojunit/ingest_test.go, product/ci/addon/gojunit/types.go, product/ci/addon/testreports/junit/junit.go, product/ci/addon/testreports/junit/junit_test.go, product/ci/ti-service/types/types.go
<details>
</details>
<details> …
=> feat: [CI-4781]: Include FileName from test XML reports

800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineResource.java
<details>
</details>
<details> …
=> fix: [PL-25955]: fixed perms required to import pipeline

315-sto-manager/src/main/java/io/harness/app/STOManagerApplication.java
Add handling of primary version to STO app.
<details>
</details>
<details>
- …
=> feat: [STO-4592]: Primary version controller logic

platform-service/build.properties
Update the build version for platform-service release branch
<details>
</details>
<details> …
=> [fix]:[PL-25475]: Update the build version for platform-service release branch

400-rest/src/main/java/io/harness/delegate/authenticator/DelegateTokenAuthenticatorImpl.java, 400-rest/src/main/java/software/wings/app/ManagerCacheRegistrar.java, 400-rest/src/main/java/software/wings/expression/ManagerPreExecutionExpressionEvaluator.java, 400-rest/src/main/java/software/wings/expression/NgSecretManagerFunctor.java, 400-rest/src/main/java/software/wings/expression/SecretManagerFunctor.java, 400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java, 400-rest/src/main/resources/metrics/metricDefinitions/delegate_secret_cache_metrics.yaml, 400-rest/src/test/java/software/wings/expression/NgSecretManagerFunctorTest.java, 400-rest/src/test/java/software/wings/expression/SecretManagerFunctorTest.java, 420-delegate-service/src/main/java/io/harness/metrics/impl/DelegateMetricsServiceImpl.java, 420-delegate-service/src/main/java/io/harness/metrics/intfc/DelegateMetricsService.java
<details>
</details>
<details> …
=> fix: [DEL-4354]: Introducing metric for secret cache

400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceImpl.java, 400-rest/src/supporter-test/java/software/wings/service/impl/workflow/WorkflowServiceTestHelper.java, 400-rest/src/test/java/software/wings/service/impl/workflow/WorkflowServiceImplTest.java
…s app]
<details>
</details>
<details>
- …
=> fix: [CDS-38928]: clear service and infradef when workflow is cloned across apps

access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml, access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml, access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
PR Includes RBAC definitions for STO module
<details>
</details>
<details>
- …
=> feat: [STO-3683]: STO RBAC definitions

280-batch-processing/BUILD.bazel, 340-ce-nextgen/BUILD.bazel, WORKSPACE
<details>
</details>
<details> …
=> fix: [CCM-8062]: Azure lib update rollback for CENG

125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters/DeploymentStageFilterJsonCreatorV2.java, 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStageConfig.java, 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/environment/yaml/EnvironmentYamlV2.java
When gitops is enabled, we fail "Save" of a pipeline under following 2 conditions
- if deploying to all and user has specified list of gitops clusters
- if not deploying to all and user has not specified list of gitops clusters
<details>
</details>
<details> …
=> feat: [CDS-36902]: Validation for deployToAll with Gitops in Deployment Stage Config

120-ng-manager/src/main/java/io/harness/ng/core/aws/resources/AwsHelperResource.java, 125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceService.java, 125-cd-nextgen/src/main/java/io/harness/cdng/aws/service/AwsResourceServiceImpl.java
<details>
</details>
<details> …
=> fix: [CDS-39210]: fix organizationId and projectId for awsConnector with delimitter

300-cv-nextgen/src/main/java/io/harness/cvng/notification/utils/NotificationRuleCommonUtils.java, 300-cv-nextgen/src/main/resources/cvng_notification_templates/cvng_monitoredservice_email.txt, 300-cv-nextgen/src/main/resources/cvng_notification_templates/cvng_slo_email.txt
<details>
</details>
<details> …
=> [feat]: [SRM-10923]: Email notification changes

400-rest/src/main/java/software/wings/sm/states/ApprovalState.java, 400-rest/src/test/java/software/wings/sm/states/ApprovalStateTest.java
<details>
</details>
<details> …
=> [fix]: [CDS-38677]: Fixing slack message length

125-cd-nextgen/src/main/java/io/harness/cdng/gitops/steps/GitopsClustersStep.java, 125-cd-nextgen/src/test/java/io/harness/cdng/gitops/steps/GitopsClustersStepTest.java
<details>
</details>
<details> …
=> feat: [CDS-39246]: Resolve service expression in gitOps step

260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, 878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java
<details>
</details>
<details> …
=> fix: [DEL-4393]: Fix NPE & fix warning on websocket unhandled message processing

420-delegate-agent/src/main/java/io/harness/managerclient/DelegateAgentManagerClientFactory.java, build.properties
<details>
</details>
<details> …
=> fix: [DEL-4399]: Increase request timeout

450-ce-views/src/main/java/io/harness/ccm/views/graphql/QLCEView.java, 450-ce-views/src/main/java/io/harness/ccm/views/service/impl/CEViewServiceImpl.java, 450-ce-views/src/test/test/io/harness/ccm/views/service/impl/CEViewServiceImplTest.java
<details>
</details>
<details> …
=> feat: [CCM-8000]: All Perspectives Backend

260-delegate/src/test/java/software/wings/delegatetasks/jira/JiraTaskTest.java, 930-delegate-tasks/src/main/java/io/harness/delegate/task/jira/JiraTaskNGHandler.java, 930-delegate-tasks/src/main/java/software/wings/delegatetasks/jira/JiraTask.java, 960-api-services/src/main/java/io/harness/jira/JiraClient.java, 970-api-services-beans/src/main/java/io/harness/jira/JiraCreateIssueRequestNG.java
<details>
</details>
<details> …
=> [fix]: [CDS-28853]: fixing default values on issue creation

125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessAwsLambdaDeployStepTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessAwsLambdaRollbackStepTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessAwsLambdaStepHelperTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/serverless/ServerlessStepCommonHelperTest.java, 930-delegate-tasks/src/test/java/io/harness/delegate/serverless/ServerlessAwsLambdaDeployCommandTaskHandlerTest.java, 930-delegate-tasks/src/test/java/io/harness/delegate/serverless/ServerlessAwsLambdaPrepareRollbackCommandTaskHandlerTest.java, 930-delegate-tasks/src/test/java/io/harness/delegate/serverless/ServerlessAwsLambdaRollbackCommandTaskHandlerTest.java, 930-delegate-tasks/src/test/java/io/harness/delegate/task/serverless/ServerlessAwsCommandTaskHelperTest.java, 930-delegate-tasks/src/test/java/io/harness/delegate/task/serverless/ServerlessDelegateTaskHelperTest.java, 930-delegate-tasks/src/test/java/io/harness/delegate/task/serverless/ServerlessGitFetchTaskHelperTest.java, 930-delegate-tasks/src/test/java/io/harness/delegate/task/serverless/ServerlessGitFetchTaskTest.java, 930-delegate-tasks/src/test/java/io/harness/delegate/task/serverless/ServerlessInfraConfigHelperTest.java, 930-delegate-tasks/src/test/java/io/harness/delegate/task/serverless/ServerlessTaskHelperBaseTest.java, 990-commons-test/src/main/java/io/harness/rule/OwnerRule.java, scripts/jenkins/author-check.sh, scripts/jenkins/authorsList.txt
<details>
</details>
<details> …
=> feat: [CDS-39116]: Serverless Unit Test and OwnerRule

260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskLifecycleManager.java, 260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java, 260-delegate/src/test/java/io/harness/perpetualtask/PerpetualTaskLifecycleManagerTest.java, 260-delegate/src/test/java/io/harness/perpetualtask/PerpetualTaskWorkerTest.java, 930-delegate-tasks/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java
<details>
</details>
<details> …
=> feat: [DEL-3944]: Rename PerpetualTask client file

280-batch-processing/BUILD.bazel, 280-batch-processing/src/main/java/io/harness/batch/processing/writer/S3SyncEventWriter.java
<details>
</details>
<details> …
=> [fix]: [CCM-8143] AWS CCM Connector failing after previous successful connections

960-persistence/src/main/java/io/harness/mongo/MongoPersistence.java
<details>
</details>
<details> …
=> fix: [CDS-38969]: Change to concurrent hash map in hpersistence

scripts/jenkins/prApiBackwardCompatibilityCheck.sh
<details>
</details>
<details> …
=> feat: [ART-1691] adding Api backward compatibility detection script for PR checks

product/ci/engine/grpc/tiproxy_handler.go, product/ci/engine/proto/tiproxy.proto, product/ci/split_tests/ti/BUILD.bazel, product/ci/split_tests/ti/ti_helper.go, product/ci/ti-service/client/client.go, product/ci/ti-service/client/http.go
<details>
</details>
<details> …
=> feat: [CI-4803]: Add support for GetTestTimes TI API in lite engine and split tests

400-rest/src/main/java/software/wings/sm/states/DatadogState.java, build.properties
<details>
</details>
<details> …
=> fix: [SRM-11104]: Fix NPE in datadog state

960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java, 960-api-services/src/test/java/io/harness/git/GitClientV2ImplTest.java
<details>
</details>
<details> …
=> [fix]: [CDS-36318]: Improve displayed error for the nested exceptions

build.properties, dockerization/base-images/apm/create-docker-builds-with-apm-bins.sh
<details>
</details>
<details> …
=> [fix]: [BT-1554]: Update path for inspect

260-delegate/src/main/java/io/harness/perpetualtask/PerpetualTaskWorker.java, 420-delegate-agent/src/main/java/io/harness/perpetualtask/PerpetualTaskServiceAgentClient.java, build.properties
<details>
</details>
<details> …
=> fix: [DEL-4512]: Enable log for fetched PT task

scripts/jenkins/prApiBackwardCompatibilityCheck.sh
<details>
</details>
<details> …
=> feat: [ART-1691] Api Backward Compatibility PR Check script update output 

400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl, 400-rest/src/test/resources/expectedDelegateWithoutDelegateName.sh, 960-api-services/src/main/java/io/harness/delegate/service/K8sGlobalConfigServiceImpl.java, 960-api-services/src/main/java/io/harness/k8s/K8sGlobalConfigService.java, 960-api-services/src/main/java/software/wings/service/impl/yaml/K8sGlobalConfigServiceUnsupported.java
Current behavior is to throw an exception if tool doesn't exists. This is the right behavior because we would like to fail fast if any required tool doesn't exists for deployment. The problem is with if customer want to use a delegate with no tools and install only tools that are required for deployment. This should be a temporary solution to unblock the customer as the quickest and safest solution, further changes are required to use only tools that are required for specific manifest type.
<details>
</details>
<details>
- …
=> fix: [CDS-40449]: Ignore get tool path exception

dockerization/delegate/Dockerfile-delegate-non-root-openjdk-ubi, dockerization/delegate/Dockerfile-immutable
TAR utility is very often used in scripts and is unavailable by default in UBI images. We should put it to make life easier for customers. 
<details>
</details>
<details>
- …
=> feat: [DEL-4518]: Add tar to UBI images as it very commonly used

400-rest/src/main/java/software/wings/resources/UserResource.java
<details>
</details>
<details> …
=> [fix]: [PL-21667]: Adding pagination support for switch accounts

840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustom.java, 840-template-service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java, 840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceHelper.java, 840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java, 840-template-service/src/test/java/io/harness/repositories/NGTemplateRepositoryCustomImplTest.java
Fix for creating template , have tested out locally this scenario and it works.
As discussed, I have tested out createTemplate, getTemplate, update template apis and list-metadata for with old and new gitX, its working as expected
<details>
</details>
<details>
- runAuthorCheck: `trigger …
=> [fix]:[pl-27319]: Fix for creating template

970-ng-commons/src/main/java/io/harness/gitsync/sdk/EntityGitDetails.java, pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/PMSPipelineDtoMapper.java
- Tested pipeline summary API, repoURL comes as metadata
<details>
</details>
<details> …
=> feat: [PL-27340]: return repo url as git details in case of remote pipelines

product/ci/addon/docker/Dockerfile.linux.arm64, product/ci/engine/docker/Dockerfile.linux.arm64
<details>
</details>
<details> …
=> feat: [CI-4949]: add arm images

970-ng-commons/src/main/java/io/harness/remote/client/AbstractHttpClientFactory.java
<details>
</details>
<details> …
=> fix: [CDS-40090]: adding log while creating a Retrofit client

340-ce-nextgen/src/main/java/io/harness/ccm/helper/RecommendationQueryHelper.java
<details>
</details>
<details> …
=> [fix]: [CCM-8632]: Added perspective filters in recommendations query

pipeline-service/modules/orchestration/src/test/java/io/harness/OrchestrationLogCacheListenerTest.java, pipeline-service/modules/orchestration/src/test/java/io/harness/engine/executions/plan/PlanExecutionMonitorServiceImplTest.java, pipeline-service/modules/orchestration/src/test/java/io/harness/engine/executions/plan/PlanExecutionServiceImplTest.java
<details>
</details>
<details> …
=> techdebt: [PIE-4189]: Adding UTs

325-sto-beans/src/test/resources/schema/SecurityStage/all.json, 332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/infrastrucutre/VmPoolYaml.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/CIStepGroupUtils.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java, 332-ci-manager/service/src/test/resources/schema/IntegrationStage/all.json
<details>
</details>
<details> …
=> fix: [CI-4687]: Make init timeout configurable for vms

pipeline-service/build/build_jar.sh
This reverts commit cd0b64a47ae6e1b0b185fe5b766cd1e8da62bd37.
<details>
</details>
<details> …
=> feat: [PIE-4821]: Clean script for pipeline service

127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/ArtifactListConfig.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/ArtifactSource.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/artifact/ArtifactSourceVisitorHelper.java
<details>
</details>
<details> …
=> feat: [CDS-41962]: create beans for artifact sources inside service

260-delegate/src/main/java/io/harness/logstreaming/LogStreamingTaskClient.java, 930-delegate-tasks/src/main/java/io/harness/delegate/beans/logstreaming/NGDelegateLogCallback.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/logstreaming/ILogStreamingTaskClient.java, 960-api-services/src/main/java/io/harness/shell/ScriptProcessExecutor.java, 960-api-services/src/main/java/io/harness/shell/ScriptSshExecutor.java, 970-api-services-beans/src/main/java/io/harness/logging/LogCallback.java, pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/ShellScriptStep.java
<details>
</details>
<details> …
=> fix: [CDS-40114]: Force dispatch logs for shell script

tools/build-cleaner/src/main/java/io/harness/buildcleaner/bazel/WriteUtil.java
Add empty dependencies also to the BUILD file. This would make it easier to upsert the BUILD files with any updated dependencies
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/36455)
=> fix: [PL-27456]: Include empty deps list in BUILD files

878-ng-common-utilities/src/main/java/io/harness/engine/expressions/SecretFunctor.java, 878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionEvaluator.java, 878-ng-common-utilities/src/main/java/io/harness/engine/expressions/ShellScriptYamlExpressionFunctor.java, 878-ng-common-utilities/src/test/java/io/harness/engine/expression/ShellScriptYamlExpressionEvaluatorTest.java, 990-commons-test/src/main/java/io/harness/rule/OwnerRule.java, scripts/jenkins/author-check.sh
Evaluator and functor needed for schell script resolution for custom secret manager - ng
<details>
</details>
<details>
- TI-bootstrap2: …
=> [feat]: [PL-26203]: adding yaml expression evaluator and secret functor

125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/infrastructure/InfrastructurePmsPlanCreator.java, 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java
<details>
</details>
<details> …
=> fix: [CDS-42065]: Log infra and provisioner steps yaml

840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java, pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/service/variables_service.proto, pipeline-service/service/src/main/java/io/harness/pms/template/VariablesServiceImpl.java
<details>
</details>
<details> …
=> [feat]: [CDS-40081]: Create v2 version for templates variable api

400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java, 920-delegate-agent-beans/src/main/java/io/harness/delegate/beans/DelegateTaskEvent.java
<details>
</details>
<details> …
=> feat: [CI-5390]: Add task type in task events API for golang delegate

332-ci-manager/build/container/Dockerfile-ci-manager-cie-jdk
<details>
</details>
<details> …
=> fix: [CI-5470]: update image

125-cd-nextgen/src/main/java/io/harness/cdng/jenkins/jenkinsstep/JenkinsBuildStepHelperServiceImpl.java, 200-functional-test/src/test/java/io/harness/functional/delegateservice/DelegateServiceTaskApiFunctionalTest.java, 332-ci-manager/app/src/main/java/io/harness/ci/CIManagerApplication.java, 332-ci-manager/app/src/main/java/io/harness/ci/CIManagerServiceModule.java, 332-ci-manager/app/src/test/java/io/harness/app/impl/CIManagerRule.java, 332-ci-manager/service/BUILD.bazel, 332-ci-manager/service/src/main/java/io/harness/ci/beans/dto/CITaskDetails.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/DelegateTaskEventListener.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/ObserverEventConsumer.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/PipelineExecutionUpdateEventHandler.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/CleanupStep.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/InitializeTaskStep.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/codebase/CodeBaseTaskStep.java, 332-ci-manager/service/src/main/java/io/harness/ci/repositories/CITaskDetailsRepository.java, 332-ci-manager/service/src/main/java/io/harness/ci/serializer/morphia/CIBeansMorphiaRegistrar.java, 400-rest/src/main/java/io/harness/grpc/DelegateServiceGrpcImpl.java, 400-rest/src/main/java/software/wings/service/impl/DelegateTaskServiceClassicImpl.java, 400-rest/src/test/java/io/harness/grpc/DelegateServiceGrpcImplTest.java, 420-delegate-service/src/main/java/software/wings/service/impl/DelegateTaskObserver.java, 870-cg-orchestration/src/main/java/io/harness/beans/DelegateTask.java, 878-ng-common-utilities/src/main/java/io/harness/steps/StepUtils.java, 878-ng-common-utilities/src/test/java/io/harness/steps/StepUtilsTest.java, 910-delegate-service-driver/src/main/java/io/harness/beans/DelegateTaskRequest.java, 910-delegate-service-driver/src/main/java/io/harness/grpc/DelegateServiceGrpcClient.java, 920-delegate-service-beans/src/main/proto/io/harness/delegate/delegate_service.proto, 952-remote-observers/src/main/java/io/harness/observer/AbstractRemoteInformer.java, 952-remote-observers/src/main/proto/io/harness/observer/BUILD.bazel, 952-remote-observers/src/main/proto/io/harness/observer/observer_proto.proto, pipeline-service/service/src/main/java/io/harness/pms/jira/JiraStepHelperServiceImpl.java, pipeline-service/service/src/main/java/io/harness/pms/servicenow/ServiceNowStepHelperServiceImpl.java
<details>
</details>
<details> …
=> feat: [CI-5348]: Added logic for consuming delegate id

120-ng-manager/src/main/java/io/harness/ng/scim/NGScimUserServiceImpl.java, 120-ng-manager/src/test/java/io/harness/ng/scim/NGScimUserServiceImplTest.java, 123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl/NgUserServiceImpl.java
<details>
</details>
<details> …
=> feat: [PL-27627]: user email update via SCIM NG

400-rest/src/main/resources/graphql/public/permissions.graphql, build.properties
<details>
</details>
<details> …
=> [feat]:[PL-28112]: Adding ABORT_WORKFLOW to permissions.graphql

product/ci/addon/tasks/runtests.go
<details>
</details>
<details> …
=> fix: [CI-4581]: Fix SelectTests API response

123-ng-core-user/src/main/java/io/harness/ng/core/DefaultUserGroupCreationService.java
In creating Default User Groups, fetching all accounts using accounts API.
Organization collection contained invalid AccountIds, those which is probably deleted and resulted in failures on creating Role Assignments for Default User Groups.
<details>
</details>
<details>
- runAuthorCheck: `trigger …
=> [fix]: [PL-28134]: In creating Default User Groups, fetching all accounts using accounts API.

840-template-service/src/main/java/io/harness/template/resources/NGTemplateResource.java
<details>
</details>
<details> …
=> [feat]: [cds-42424]: Made docs changes

build.properties, dockerization/verification/Dockerfile-verification-cie-jdk
<details>
</details>
<details> …
=> [fix]: [SECAPP-481]: Removing the ocelot lib

126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustom.java, 126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java, 126-instance/src/main/java/io/harness/service/instance/InstanceService.java, 126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java, 126-instance/src/test/java/io/harness/repositories/instance/InstanceRepositoryCustomImplTest.java, 126-instance/src/test/java/io/harness/service/instance/InstanceServiceImplTest.java
<details>
</details>
<details> …
=> fix: [CDS-43000]: Handle duplicate instances

125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/CdAbstractStepNode.java, 300-cv-nextgen/src/main/java/io/harness/cvng/cdng/beans/CVNGAbstractStepNode.java, 332-ci-manager/contracts/src/main/java/io/harness/cimanager/stepinfo/CIAbstractStepNode.java, 953-yaml-commons/src/main/java/io/harness/plancreator/steps/AbstractStepNode.java, pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal/PmsAbstractStepNode.java, pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepNode.java, pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/WaitStepPlanCreator.java
… to the modules' classes for step node
<details>
</details>
<details>
- …
=> feat: [PIE-5296]: Remove timeout field from AbstractStepNode 

127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/utils/ArtifactUtils.java
<details>
</details>
<details> …
=> [fix]: [CDS-43195]: bug fix

125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, 125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/AzureArtifactConfig.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/ArtifactSourceConstants.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/ArtifactSourceType.java
<details>
</details>
<details> …
=> [feat]: [CDS-42745]: Azure Artifact Source YAML

dockerization/base-images/ubi-base-cie-agents/java-go/Dockerfile-java-go-cie-agent
<details>
</details>
<details> …
=> [feat]: [BT-1696]: Install docker in cie agent

332-ci-manager/app/src/test/java/io/harness/app/CIDashboard/CIDashboardsApisTest.java, 332-ci-manager/build.properties, 332-ci-manager/contracts/src/main/java/io/harness/cimanager/dashboard/api/BuildActiveInfo.java, 332-ci-manager/contracts/src/main/java/io/harness/cimanager/dashboard/api/BuildFailureInfo.java, 332-ci-manager/service/src/main/java/io/harness/ci/dashboard/CIOverviewDashboardServiceImpl.java
<details>
</details>
<details> …
=> fix: [CI-5072]: CI manager restart fix

125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentAbstractStageNode.java, 125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json, 953-yaml-commons/src/main/java/io/harness/plancreator/stages/stage/StageElementConfig.java, pipeline-service/modules/orchestration-steps/src/test/resources/schema/Pipelines/all.json
<details>
</details>
<details> …
=> [feat]: [CDS-43133]: Added YAML Schema type

332-ci-manager/service/src/main/java/io/harness/ci/execution/validation/CIYAMLSanitizationServiceImpl.java
<details>
</details>
<details> …
=> feat: [CI-5554]: add run test step verification 

120-ng-manager/BUILD.bazel, 120-ng-manager/src/main/java/io/harness/ng/chaos/AbstractChaosModule.java, 120-ng-manager/src/main/java/io/harness/ng/chaos/ChaosNotifyCallback.java, clients/chaos/BUILD.bazel, clients/chaos/src/main/java/io/harness/chaos/client/beans/ChaosApplyManifestResponse.java, clients/chaos/src/main/java/io/harness/chaos/client/remote/ChaosClientModule.java, clients/chaos/src/main/java/io/harness/chaos/client/remote/ChaosHttpClient.java, clients/chaos/src/main/java/io/harness/chaos/client/remote/ChaosHttpClientFactory.java
<details>
</details>
<details> …
=> techdebt: [CHAOS-295]: Extract chaos client to a new module

product/ci/addon/testintelligence/java/bazel.go, product/ci/addon/testintelligence/java/bazel_test.go
<details>
</details>
<details> …
=> feat: [CI-5425]: Add test autodetect support for Bazel

125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java, pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProvider.java
<details>
</details>
<details> …
=> fix: [PIE-5523]: fixed failing registrations

332-ci-manager/config/ci-manager-config.yml
<details>
</details>
<details> …
=> feat: [CI-3333]: SBT addon version bump

400-rest/src/main/java/io/harness/iterator/DelegateTaskExpiryCheckIterator.java, 420-delegate-service/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordDao.java
<details>
</details>
<details> …
=> [fix]: [DEL-4971]: Marking PPT with no heartbeat to status TASK_TO_REBALANCE

300-cv-nextgen/src/test/java/io/harness/cvng/cdng/services/impl/resources/CVNGStepResourceTest.java, 300-cv-nextgen/src/test/java/io/harness/cvng/core/jobs/EntityCRUDStreamConsumerTest.java, 300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceTest.java, 300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java
<details>
</details>
<details> …
=> feat: [SRM-12260]: Fixing Unit tests for PR Check failure

120-ng-manager/src/main/java/io/harness/ng/NextGenModule.java, 120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeCRUDResource.java, 120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeEvalutationResource.java, 120-ng-manager/src/main/java/io/harness/ng/freeze/resource/FreezeSchemaResource.java, 120-ng-manager/src/main/java/io/harness/serializer/NextGenRegistrars.java, 125-freeze/BUILD.bazel, 125-freeze/src/main/java/io/harness/freeze/beans/FreezeEntityRule.java, 125-freeze/src/main/java/io/harness/freeze/beans/FreezeWindow.java, 125-freeze/src/main/java/io/harness/freeze/beans/PermissionTypes.java, 125-freeze/src/main/java/io/harness/freeze/beans/Recurrence.java, 125-freeze/src/main/java/io/harness/freeze/beans/RecurrenceSpec.java, 125-freeze/src/main/java/io/harness/freeze/beans/response/FreezeSummaryResponseDTO.java, 125-freeze/src/main/java/io/harness/freeze/beans/yaml/FreezeConfig.java, 125-freeze/src/main/java/io/harness/freeze/beans/yaml/FreezeInfoConfig.java, 125-freeze/src/main/java/io/harness/freeze/helpers/FreezeTimeUtils.java, 125-freeze/src/main/java/io/harness/freeze/mappers/NGFreezeDtoMapper.java, 125-freeze/src/main/java/io/harness/freeze/service/FreezeCRUDService.java, 125-freeze/src/main/java/io/harness/freeze/service/FreezeEvaluateService.java, 125-freeze/src/main/java/io/harness/freeze/service/FreezeSchemaService.java, 125-freeze/src/main/java/io/harness/freeze/service/impl/FreezeCRUDServiceImpl.java, 125-freeze/src/main/java/io/harness/freeze/service/impl/FreezeEvaluateServiceImpl.java, 125-freeze/src/main/java/io/harness/freeze/service/impl/FreezeSchemaServiceImpl.java, 125-freeze/src/main/java/io/harness/serializer/FreezeRegistrars.java, 125-freeze/src/test/java/io/harness/freeze/NGFreezeDtoMapperTest.java, 125-freeze/src/test/resources/projectFreezeConfig.yaml, 960-yaml-sdk/src/main/java/io/harness/yaml/validator/YamlSchemaValidator.java
<details>
</details>
<details> …
=> feat: [CDS-44498]: FreezeSchema and validation

400-rest/src/main/java/software/wings/service/impl/AuditServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/instance/AuditCleanupJob.java
<details>
</details>
<details> …
=> fix: [spg-21]: Audit Cleanup

100-migrator/src/main/java/io/harness/ngmigration/service/servicev2/ServiceV2Mapper.java
<details>
</details>
<details> …
=> feat: [CDS-44558]: add support for multiple artifact sources

956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Add a new flag that decides if we should render the new feature flag mfe for our environment page
<details>
</details>
<details>
- TI-bootstrap: `trigger …
=> feat: [FFM-4666]: Add ff mfe flag

956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
<details>
</details>
<details> …
=> feat: [SRM-12522]: Removed unnecessary FF and added new FF

953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlNode.java, 953-yaml-commons/src/test/java/io/harness/pms/yaml/YamlUtilsTest.java, clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/stages/RollbackStagePlanCreator.java, pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/StagesPlanCreator.java
When a rollback stage for a stage s1 is done, the the rollback stage of the stage that's before s1 should start. This will be taken care of by Next Stage Advisor.
Not handling parallel stages yet, will raise another PR for that
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/39107)
=> [feat]: [PIE-5964]: Add next stage advisor to rollback stages

260-delegate/src/test/java/software/wings/delegatetasks/validation/capabilitycheck/SshHostConnectionCapabilityCheckTest.java, 930-delegate-tasks/src/main/java/io/harness/delegate/task/shell/winrm/WinRmConfigAuthEnhancer.java, 930-delegate-tasks/src/main/java/software/wings/delegatetasks/validation/capabilitycheck/WinrmHostConnectionCapabilityCheck.java, 932-connector-task/src/main/java/io/harness/connector/task/shell/SshSessionConfigMapper.java, 940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/services/SshKeySpecDTOHelper.java
<details>
</details>
<details> …
=> fix: [CDS-45383]: NPE when providing No TGT method for Winrm

440-connector-nextgen/src/main/java/io/harness/connector/ConnectorRegistryFactory.java, 440-connector-nextgen/src/test/java/io/harness/connector/impl/GitConnectorValidatorTest.java
<details>
</details>
<details> …
=> feat: [CI-5666]: custom git connection via manager

884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java, pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl/GraphGenerationServiceImpl.java, pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils/OrchestrationUtils.java, pipeline-service/modules/orchestration/src/test/java/io/harness/engine/utils/OrchestrationUtilsTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/39419)
=> [feat]: [PIE-6086]: Add node execution id to graph for parallel blocks

125-cd-nextgen/src/main/java/io/harness/cdng/ecs/EcsStepCommonHelper.java, 125-cd-nextgen/src/main/java/io/harness/cdng/ecs/beans/EcsHarnessStoreManifestsContent.java, 125-cd-nextgen/src/test/java/io/harness/cdng/ecs/EcsStepCommonHelperTest.java
<details>
</details>
<details> …
=> fix: [CDS-45832]: ECS NG Harness store refactor

123-ng-core-user/src/main/java/io/harness/ng/core/entities/EmailConfig.java, 123-ng-core-user/src/main/java/io/harness/ng/core/utils/UserGroupMapper.java, 123-ng-core-user/src/test/java/io/harness/ng/core/outbox/UserGroupEventHandlerTest.java, 960-ng-core-beans/src/main/java/io/harness/ng/core/notification/EmailConfigDTO.java, build.properties, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java
<details>
</details>
<details> …
=> Revert "feat: [spg-560]: Adding a checkbox to send notification to all users part of usergroup "

490-ce-commons/src/main/java/io/harness/ccm/commons/beans/recommendation/RecommendationUtils.java, 490-ce-commons/src/main/java/io/harness/ccm/commons/beans/recommendation/models/RecommendClusterRequest.java
Added minCpu and minMem in node recommendation request.
<details>
</details>
<details>
- …
=> [fix]: [CCM-9722]: Added minCpu and minMem in node recommendation request

300-cv-nextgen/src/main/java/io/harness/cvng/governance/beans/ExpansionKeysConstants.java, 300-cv-nextgen/src/main/java/io/harness/cvng/governance/services/SLOPolicyExpansionHandler.java
<details>
</details>
<details> …
=> [fix]: [SRM-12507]: adding support for env v2.

300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/beans/SLOHealthListView.java, 300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImpl.java
<details>
</details>
<details> …
=> fix: [SRM-12747]: SLOHealthListView class changes for develop branch

840-template-service/contracts/openapi/public/v1/jaxrs-spec-config.json, 840-template-service/contracts/openapi/public/v1/openapi.yaml, 840-template-service/src/main/java/io/harness/template/resources/AccountTemplateApiImpl.java, 840-template-service/src/main/java/io/harness/template/resources/OrgTemplateApiImpl.java, 840-template-service/src/main/java/io/harness/template/resources/ProjectTemplateApiImpl.java, 840-template-service/src/main/java/io/harness/template/resources/TemplateResourceApiMapper.java, 840-template-service/src/main/java/io/harness/template/resources/TemplateResourceApiUtils.java, 840-template-service/src/test/java/io/harness/template/resources/TemplateResourceApiMapperTest.java, 840-template-service/src/test/java/io/harness/template/resources/TemplateResourceApiUtilsTest.java
<details>
</details>
<details> …
=> fix: [PL-29620]: error fixes for templates

315-sto-manager/src/test/resources/schema/SecurityStage/all.json, 332-ci-manager/contracts/src/main/java/io/harness/cimanager/yaml/extended/platform/ArchType.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeUtils.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/InitializeTaskStep.java, 332-ci-manager/service/src/test/java/io/harness/ci/plan/creator/codebase/CIModuleInfoProviderTest.java, 332-ci-manager/service/src/test/resources/schema/IntegrationStage/all.json
<details>
</details>
<details> …
=> feat: [CI-5868]: mac anka testing

125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java, 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStepInfo.java, 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStepParams.java, 930-delegate-tasks/src/main/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoApiClient.java, 930-delegate-tasks/src/test/java/io/harness/delegate/task/gitapi/client/impl/AzureRepoClientTest.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/gitapi/GitApiTaskParams.java, 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java, 960-api-services/src/main/java/io/harness/cistatus/service/GithubServiceImpl.java, 960-api-services/src/main/java/io/harness/cistatus/service/azurerepo/AzureRepoService.java, 960-api-services/src/main/java/io/harness/cistatus/service/azurerepo/AzureRepoServiceImpl.java, 960-api-services/src/test/java/io/harness/cistatus/service/azurerepo/AzureRepoServiceImplTest.java, build.properties
Add bypass parameters to Merge PR step
<details>
</details>
<details>
- TI-bootstrap2: …
=> feat: [CDS-45872]: add bypass parameters to Merge PR step

build.properties
<details>
</details>
<details> …
=> [fix]:[SMP-807]:Version bump

batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/impl/AWSEC2RecommendationServiceImpl.java
* [CCM-9342]: Fixing the NPE for recommendation results
* [CCM-9342]: Fixing the NPE for recommendation results
* [CCM-9342]: Fixing the NPE for recommendation results
* [CCM-9342]: Fixing the NPE for recommendation results
<details>
</details>
<details>
- PMD: …
=> fix: [CCM-9342]: Fixing the NPE for recommendation results (#40029)

956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java, batch-processing/build.properties, batch-processing/service/src/main/java/io/harness/batch/processing/billing/writer/InstanceBillingDataTasklet.java, batch-processing/service/src/main/java/io/harness/batch/processing/cloudevents/aws/ec2/service/impl/AWSEC2RecommendationServiceImpl.java, batch-processing/service/src/main/java/io/harness/batch/processing/pricing/gcp/bigquery/BQConst.java, batch-processing/service/src/main/java/io/harness/batch/processing/pricing/gcp/bigquery/BigQueryHelperService.java, batch-processing/service/src/main/java/io/harness/batch/processing/pricing/gcp/bigquery/BigQueryHelperServiceImpl.java, batch-processing/service/src/main/java/io/harness/batch/processing/pricing/gcp/bigquery/VMInstanceServiceBillingData.java, batch-processing/service/src/main/java/io/harness/batch/processing/pricing/service/impl/AwsCustomBillingServiceImpl.java, batch-processing/service/src/main/java/io/harness/batch/processing/pricing/service/intfc/AwsCustomBillingService.java, batch-processing/service/src/test/java/io/harness/batch/processing/pricing/gcp/bigquery/impl/BigQueryHelperServiceImplTest.java, batch-processing/service/src/test/java/io/harness/batch/processing/pricing/service/impl/AwsCustomBillingServiceImplTest.java
https://harness.atlassian.net/browse/CCM-9879
<details>
</details>
<details> …
=> [feat]:[CCM-9879] : Hotfix for AWS netAmortised cost calculation

970-grpc/src/main/java/io/harness/event/client/impl/tailer/ChronicleEventTailer.java, build.properties
<details>
</details>
<details>
- TI-bootstrap3: `trigger …
=> fix: [CCM-10058]: QA Hotfix ChronicleEventTailer index not updating when making rest call

332-ci-manager/build.properties, 332-ci-manager/service/src/main/resources/enterprise-redisson-jcache.yaml, 332-ci-manager/service/src/main/resources/redisson-jcache.yaml
hotfix for cache issue
<details>
</details>
<details>
- …
=> hotfix for cache issue

120-ng-manager/src/main/java/io/harness/ng/overview/resource/CDDashboardOverviewResource.java, 120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardService.java, 120-ng-manager/src/main/java/io/harness/ng/overview/service/CDOverviewDashboardServiceImpl.java, 126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustom.java, 126-instance/src/main/java/io/harness/repositories/instance/InstanceRepositoryCustomImpl.java, 126-instance/src/main/java/io/harness/service/instance/InstanceService.java, 126-instance/src/main/java/io/harness/service/instance/InstanceServiceImpl.java, 126-instance/src/main/java/io/harness/service/instancedashboardservice/InstanceDashboardService.java, 126-instance/src/main/java/io/harness/service/instancedashboardservice/InstanceDashboardServiceImpl.java, 136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java, 970-ng-commons/src/main/java/io/harness/NGCommonEntityConstants.java
Created API getInstancesDetails for getting active instances meta data based on build, environment, infrastructure and pipelineExecutionId. 
<details>
</details>
<details>
- TI-bootstrap: …
=> [feat]: [CDS-46905]: created getInstancesDetails API

batch-processing/service/src/main/java/io/harness/batch/processing/pricing/gcp/bigquery/BigQueryHelperService.java, batch-processing/service/src/main/java/io/harness/batch/processing/pricing/gcp/bigquery/BigQueryHelperServiceImpl.java, batch-processing/service/src/main/java/io/harness/batch/processing/service/impl/CustomBillingMetaDataServiceImpl.java, batch-processing/service/src/test/java/io/harness/batch/processing/service/impl/CustomBillingMetaDataServiceImplTest.java
`accountId` has been newly passed in `BigQueryServiceImpl` and for one of the flow we are passing `accountId` as null in AWS. passing the correct accountId in that case too.
Due to this error, AWS BillingData was not getting generated.
<details>
</details>
<details>
- BuildNumberMetadata: `trigger …
=> [fix]:[CCM-9879]: fixing null accountId issue

125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java, 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreator.java, 125-cd-nextgen/src/main/java/io/harness/cdng/creator/variables/ServiceVariableCreator.java, 125-cd-nextgen/src/main/java/io/harness/cdng/manifest/mappers/ManifestOutcomeMapper.java, 125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/manifest/IndividualManifestPlanCreatorTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/service/ServiceDefinitionPlanCreatorTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/pipeline/helpers/CDNGPipelineConfigurationHelperTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/pipeline/resources/CDNGPipelineConfigurationResourceTest.java, 125-cd-nextgen/src/test/resources/recaster/alias/alias.txt, 125-cd-nextgen/src/test/resources/schema/DeploymentStage/all.json, 125-cd-nextgen/src/test/resources/schema/DeploymentSteps/all.json, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/ManifestConfigType.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/ManifestType.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/AsgConfigurationManifestOutcome.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/AsgLaunchTemplateManifestOutcome.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/AsgScalingPolicyManifestOutcome.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/AsgScheduledUpdateGroupActionManifestOutcome.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/ManifestOutcome.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgConfigurationManifest.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgLaunchTemplateManifest.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgScalingPolicyManifest.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/kinds/AsgScheduledUpdateGroupActionManifest.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/AsgServiceSpec.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans/ServiceDefinitionType.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/AsgConfigurationManifestVisitorHelper.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/AsgLaunchTemplateManifestVisitorHelper.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/AsgScalingPolicyManifestVisitorHelper.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/manifest/AsgScheduledUpdateGroupActionManifestVisitorHelper.java, 127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor/helpers/serviceconfig/AsgServiceSpecVisitorHelper.java, 960-ng-core-beans/src/main/java/io/harness/ng/core/k8s/ServiceSpecType.java
<details>
</details>
<details>
- TI-bootstrap3: `trigger …
=> feat: [CDS-47022]: added service for ASG

123-ng-core-user/src/main/java/io/harness/ng/core/api/UserGroupService.java, 123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/DefaultUserGroupServiceImpl.java, 123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java
In DefaultUserGroupJob which is used for reconcillation of default user groups,
updating user group throws DuplicateFieldException.
Fixed the updating user group by avoiding convert from DTO to entity which is causing loss of context for update.
<details>
</details>
<details>
- …
=> [fix]: [PL-30251]: Fixed updating user group using DefaultUserGroupJob.

srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/analysis/resources/LogAnalysisResource.java
…e present.
<details>
</details>
<details>
- TI-bootstrap1: `trigger …
=> feat: [SRM-12731]: Fix for log host sampling issues.

pipeline-service/config/config.yml, pipeline-service/modules/orchestration/src/main/java/io/harness/PipelineSettingsServiceImpl.java
Adding Trial license check for restrictions in pipeline executions
Impact : Only trial license adopting restrictions on executions
Testing: HF already deployed to QA and Prod
ReleaseNotes summary needed? No
Is it new task type? No
Did you make changes to the code in a backward-compatible manner? Yes
Did you add a new class which is added in kryo serialization? - No
Will the new version of the delegate receive old version task and process? Yes
If new version of the pipeline-service receives response for the old task will it be able to handle it successfully? Yes
Did you make a change in delegate task which will be created in pipeline-services via grpc call to manager? No change
If the older version of pipeline-service creates the task parameter and calls newer cg manager, will it be okay? …
=> [feat]: [PIE-6964]: Adding Trial license check for restrictions in pipeline executions

948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/sumologic/SumologicLogSampleDataRequest.java, 948-cv-nextgen-beans/src/main/java/io/harness/cvng/beans/sumologic/SumologicMetricSampleDataRequest.java
<details>
</details>
<details>
- …
=> [fix]: [SRM-13328]: fixed no constructor issue in delegate and manager.

450-ce-views/src/test/test/io/harness/ccm/views/service/impl/ViewsBillingServiceImplTest.java, access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml, batch-processing/build.properties, batch-processing/service/src/test/java/io/harness/batch/processing/anomalydetection/AnomalyAlertsServiceImplTest.java, batch-processing/service/src/test/java/io/harness/batch/processing/tasklet/K8sNodeRecommendationTaskletTest.java, ce-nextgen/service/src/test/java/io/harness/ccm/CENextGenStartupTest.java, ce-nextgen/service/src/test/resources/test-config.yml
Fixed junit test cases and rbac permission issue
<details>
</details>
<details>
- TI-bootstrap: …
=> [fix]: [CCM-9632]: Fixed junit test cases and rbac permission issue

batch-processing/build.properties, batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/util/CurrencyPreferenceHelperImpl.java
Removed cache and added logs for testing
<details>
</details>
<details>
- TI-bootstrap: `trigger …
=> [fix]: [CCM-9632]: Removed cache and added logs for testing

160-model-gen-tool/config-datagen.yml
Summary:
Issue: DataGenApp not starting after enabling queueing service
Soln: Add queue config
- [ x] I've documented the changes in the PR description.
<details>
</details>
<details>
- …
=> fix: [DEL-5670]: Add queue service config to datagen app

pipeline-service/service/src/main/java/io/harness/pms/approval/notification/ApprovalNotificationHandlerImpl.java
<details>
</details>
<details>
- …
=> fix: [CDS-29134]: fix acl check in send notification Harness Approval

310-iacm-manager/build/container/scripts/replace_configs.sh, 332-ci-manager/build.properties, 332-ci-manager/config/ci-manager-config.yml, 332-ci-manager/container/scripts/replace_configs.sh, 332-ci-manager/service/src/main/java/io/harness/ci/beans/config/ExecutionLimits.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/CIExecutionServiceModule.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/enforcement/CIBuildEnforcerImpl.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/QueueExecutionUtils.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/V1/InitializeTaskStepV2.java, dockerization/ci-manager/scripts/replace_configs.sh
<details>
</details>
<details>
- …
=> fix: [CI-6647]: Fix npe for null build type

332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/VmInitializeTaskParamsBuilder.java, 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
<details>
</details>
<details>
- …
=> feat: [CI-5455]: windows hosted ff

120-ng-manager/contracts/openapi/v1/openapi.yaml, 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AbstractServicesApiImpl.java, 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/AccountServicesApiImpl.java, 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/OrgServicesApiImpl.java, 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ProjectServicesApiImpl.java, 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResource.java, 120-ng-manager/src/main/java/io/harness/ng/core/service/resources/ServiceResourceV2.java, 120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementService.java, 120-ng-manager/src/main/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceImpl.java, 120-ng-manager/src/test/java/io/harness/ng/core/service/resources/ProjectServicesApiImplTest.java, 120-ng-manager/src/test/java/io/harness/ng/core/service/resources/ServiceResourceTest.java, 120-ng-manager/src/test/java/io/harness/ng/core/service/services/ServiceEntityManagementServiceTest.java, 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/OutboxEventConstants.java, 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/events/ServiceForceDeleteEvent.java, 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/ServiceEntityService.java, 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java, 127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImplTest.java
Force deletion of Service Entity in NG as per https://harness.atlassian.net/wiki/spaces/PLATFORM/pages/21237040305/Force+Delete+support+for+Harness+Entities
<details>
</details>
<details>
- …
=> feat: [CDS-47125]: Force deletion of Service Entity in NG

125-cd-nextgen/src/test/java/io/harness/cdng/elastigroup/ElastigroupBGStageSetupStepTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/elastigroup/ElastigroupFixedInstancesTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelperTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/elastigroup/ElastigroupStepUtilsTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/elastigroup/rollback/ElastigroupRollbackStepHelperTest.java
<details>
</details>
<details>
- …
=> junit for Spot

ce-nextgen/awstemplate/prod/HarnessAWSTemplate.yaml
<details>
</details>
<details>
- …
=> [fix]: [CCM-0]: added governance policy

400-rest/src/main/java/io/harness/serializer/kryo/ManagerKryoRegistrar.java, 400-rest/src/main/java/io/harness/serializer/morphia/ManagerMorphiaRegistrar.java, 400-rest/src/main/java/software/wings/api/k8s/K8sGitFetchInfo.java, 400-rest/src/main/java/software/wings/api/k8s/K8sGitInfo.java, 400-rest/src/main/java/software/wings/sm/states/k8s/AbstractK8sState.java, 400-rest/src/test/java/software/wings/sm/states/k8s/AbstractK8SStateTest.java, 400-rest/src/test/resources/manager-kryo-registrations.txt, 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/metadata/GitFetchMetadataContext.java, 930-delegate-tasks/src/main/java/io/harness/delegate/task/git/metadata/GitFetchMetadataLocalThread.java, 930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitFetchFilesTask.java, 930-delegate-tasks/src/main/java/software/wings/delegatetasks/ScmFetchFilesHelper.java, 930-delegate-tasks/src/main/java/software/wings/service/impl/GitServiceImpl.java, 930-delegate-tasks/src/main/java/software/wings/service/impl/yaml/GitClientImpl.java, 930-delegate-tasks/src/main/java/software/wings/service/intfc/GitService.java, 950-delegate-tasks-beans/src/main/java/software/wings/beans/yaml/GitCommandExecutionResponse.java, 950-delegate-tasks-beans/src/main/java/software/wings/beans/yaml/GitFetchFilesRequest.java, 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
Created a sweeping output with value :- ${k8sGitFetchInfo.Service.commitId}
Tested to print variable in sheel script
<details>
</details>
<details> …
=> feat: [CDS-50962]: Support for the CommitId used for fetching manifests as a Built-In variable

120-ng-manager/src/main/java/io/harness/ng/webhook/WebhookHelper.java, 900-git-sync-sdk/src/test/java/io/harness/gitsync/scm/SCMGitSyncHelperTest.java, 952-scm-java-client/src/main/java/io/harness/beans/ReleaseWebhookEvent.java, 952-scm-java-client/src/main/java/io/harness/beans/WebhookEvent.java, 952-scm-java-client/src/main/java/io/harness/impl/WebhookParserSCMServiceImpl.java, 953-events-api/src/main/proto/io/harness/eventsframework/schemas/webhookpayloads/webhookdata.proto, pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/Constants.java, pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/WebhookEvent.java, pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/v2/github/action/GithubReleaseAction.java, pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/v2/github/event/GithubEventSpec.java, pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/v2/github/event/GithubReleaseSpec.java, pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/v2/github/event/GithubTriggerEvent.java, pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/TriggerFilterStore.java, pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/WebhookConfigHelper.java, pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper/NgTriggerConfigAdaptor.java, pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/utils/WebhookTriggerFilterUtils.java, tools/go/update_bazel_repo.sh
This PR adds support for Github release events in Github webhook triggers.
<details>
</details>
<details>
- Feature Name Check: `trigger …
=> feat: [PIE-6046]: NG - Add support for Release Event in Github Webhook Triggers

120-ng-manager/src/main/java/io/harness/ng/core/outbox/EnvironmentEventHandler.java, 120-ng-manager/src/main/java/io/harness/ng/core/outbox/EnvironmentGroupOutboxEventHandler.java, 120-ng-manager/src/main/java/io/harness/ng/core/outbox/ServiceOutBoxEventHandler.java, 840-template-service/src/main/java/io/harness/template/events/TemplateOutboxEventHandler.java
have added code for getting audit trials while we do force deletion of services,templates,environments,environmentgroup.
<details>
</details>
<details>
- Copyright Check: `trigger …
=> fix: [CDS-47125]: Add audit trials for force delete of services, environments 

930-delegate-tasks/src/main/java/io/harness/delegate/pcf/CfRollbackCommandTaskHandlerNG.java, 930-delegate-tasks/src/main/java/io/harness/delegate/task/cf/CfCommandTaskHelperNG.java, 930-delegate-tasks/src/test/java/io/harness/delegate/pcf/CfRollbackCommandTaskHandlerTest.java
Junit for Cf Rollback task handler
<details>
</details>
<details>
- …
=> feat: [CDS-51558]: Junit for Cf Rollback command Task Handler

125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java, 125-cd-nextgen/src/main/java/io/harness/cdng/aws/asg/AsgStepCommonHelper.java, 125-cd-nextgen/src/main/resources/executionStrategyYaml/asg-bluegreen-with-verify.yaml, 125-cd-nextgen/src/main/resources/executionStrategyYaml/asg-bluegreen.yaml, 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenDeployCommandTaskHandler.java, 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenPrepareRollbackCommandTaskHandler.java, 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenRollbackCommandTaskHandler.java, 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgBlueGreenSwapServiceCommandTaskHandler.java, 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgPrepareRollbackDataCommandTaskHandler.java, 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgRollingDeployCommandTaskHandler.java, 930-delegate-tasks/src/main/java/io/harness/delegate/aws/asg/AsgRollingRollbackCommandTaskHandler.java, 960-api-services/src/main/java/io/harness/aws/asg/AsgSdkManager.java, 960-api-services/src/main/java/io/harness/aws/asg/manifest/AsgConfigurationManifestHandler.java, 960-api-services/src/main/java/io/harness/aws/asg/manifest/AsgInstanceRefreshHandler.java, 960-api-services/src/main/java/io/harness/aws/asg/manifest/AsgScalingPolicyManifestHandler.java, 960-api-services/src/main/java/io/harness/aws/asg/manifest/AsgScheduledActionManifestHandler.java, 960-api-services/src/main/java/io/harness/aws/asg/manifest/AsgSwapServiceHandler.java
<details>
</details>
<details>
- …
=> fix: [CDS-52527]: Asg Improve logging

ce-nextgen/build.properties, ce-nextgen/build/container/scripts/start_process.sh
Added advanced Java flags to enable native memory tracking
<details>
</details>
<details>
- …
=> [feat]: [CCM-11015]: Added Java flags to enable native memory tracking

batch-processing/build.properties, batch-processing/build/container/scripts/replace_configs.sh, batch-processing/service/batch-processing-config.yml, batch-processing/service/src/main/java/io/harness/batch/processing/config/BatchMainConfig.java, batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, batch-processing/service/src/test/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTaskletTest.java, dockerization/batch-processing/scripts/replace_configs.sh
Adding a flag `isClickHouseEnabled` for batch-processing. Default value will be `false`.
<details>
</details>
<details>
- Feature Name Check: …
=> [feat]: [CCM-11047]: adding a flag isClickHouseEnabled for batch-processing

.github/CODEOWNERS
<details>
</details>
<details>
- …
=> feat: [PIE-8073]: add code owners for gitx code

ce-nextgen/build.properties, ce-nextgen/build/container/scripts/replace_configs.sh
replace config for smp
<details>
</details>
<details>
- …
=> replace config for smp

ce-nextgen/build.properties, ce-nextgen/build/build_dist.sh, ce-nextgen/build/container/Dockerfile-ce-nextgen-cie-jdk, ce-nextgen/build/container/scripts/start_process.sh, ce-nextgen/config/jfr/default.jfc, ce-nextgen/config/jfr/profile.jfc
Added jfr profiles in ce-nextgen docker image
<details>
</details>
<details>
- TI-bootstrap: …
=> [feat]: [CCM-11015]: Added jfr profiles in ce-nextgen docker image

400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java
For ECS delegate, during registration, we skip setting (newly introduced flag) delegateDisconnect, which get default to true and never gets updated in subsequent heartbeat calls.
As a fix, we are not setting explicitly as false.
Testing:
Tested locally and delegate disconnect is now get set to false
<details>
</details>
<details>
- …
=> fix: [DEL-5939]: Mark delegate disconnected flag as false during upsert

120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/docker/DockerArtifactResource.java
<details>
</details>
<details>
- TI-ALL: `trigger tiAll`
- …
=> hotfixpreqa: [CDS-38025]: Correcting docker connector identifier

136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java, 136-git-sync-manager/src/test/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImplTest.java, 136-git-sync-manager/src/test/java/io/harness/gitsync/scm/BitbucketConnectorDTOTest.java, 930-ng-core-clients/src/main/java/io/harness/utils/ConnectorUtils.java, 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/bitbucket/BitbucketConnectorDTO.java, 960-api-services/src/main/java/io/harness/git/GitClientHelper.java, 960-api-services/src/test/java/io/harness/git/GitClientHelperTest.java
Git exp repo list API does not work when the connect is a account level connect with url configured as https://github.com/ , this needs to be resolved. 
Tests done : Tested http and ssh for github, bitbucket, azure connectors with account and repo level settings. Tested fetch branch api as well.
<details>
</details>
<details>
- …
=> fix: [CI-6630]: fixed git exp repo listing

idp-service/config/config.yml, idp-service/container/scripts/replace_configs.sh, idp-service/modules/k8s/src/main/java/io/harness/k8s/client/K8sApiClient.java, idp-service/modules/k8s/src/main/java/io/harness/k8s/client/K8sClient.java, idp-service/service/src/main/java/io/harness/idp/app/IdpConfiguration.java, idp-service/service/src/main/java/io/harness/idp/app/IdpModule.java, idp-service/service/src/main/java/io/harness/idp/status/k8s/PodHealthCheck.java
<details>
</details>
<details>
- TI-ALL: `trigger tiAll`
- …
=> feat: [IDP-176]: Get k8s config from config.yml

930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java
<details>
</details>
<details>
- …
=> feat: [PLG-1949]: Don't allow sales-led accounts to purchase subscriptions

136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java
<details>
</details>
<details>
- …
=> feat: [PIE-8645]: added cache upsert handling for get-batch-file use-case

332-ci-manager/build.properties, 332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/queue/CIInitTaskMessageProcessorImpl.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/states/V1/InitializeTaskStepV2.java
<details>
</details>
<details>
- …
=> fix: [CI-7093]: fixed error message issue

953-git-sync-commons/src/main/proto/io/harness/gitsync/harness_to_git.proto
<details>
</details>
<details>
- …
=> feat: [PIE-8422]: add new boolean field to getFileRequest in git-service grpc call to support fetching only file-content

pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers/MarkAsFailureAdviseHandler.java, pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/advise/handlers/MarkAsFailureAdviseHandlerTest.java
<details>
</details>
<details>
- …
=> [fix]: [PIE-8661]:  Handled NodeStatusUpdate in case of BrokeStatuses other than Failed.

product/ci/common/logs/remote_writer.go
<details>
</details>
<details>
- …
=> fix: [CI-7114]: Added logs to check incoming stream after close

pipeline-service/build.properties, pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources/InputSetResourcePMSImpl.java
If pipelinBranch is null we will get the pipelinBranch from gitEntityBasicInfo's branch field
<details>
</details>
<details>
- Feature Name Check: …
=> [fix]: [SPG-2260]: fix trigger is loading from master branch

360-cg-manager/container/scripts/replace_configs.sh, dockerization/manager/scripts/replace_configs.sh
The PR is for a regression in 776xx caused by using REDIS_NETTY_THREAD in configmap. Inclusion of this variable was not tested with redisSentinels and lead to crash.
It contains wrapping of singleServerConfig which were previously unrestricted and added to sentinels lead to pod crashes.
<details>
</details>
<details>
- …
=> [fix]:[SMP-1003]: Fixes for manager crash due to redisSingleServer

srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/jobs/EntityChangeEventMessageProcessor.java
<details>
</details>
<details>
- …
=> fix: [SRM-14265]: passed failing test testCompoudIndexForOrgDeletionIsPresent

120-ng-manager/src/main/java/io/harness/ng/core/environment/resources/EnvironmentResourceV2.java
Mark org/project identifiers as not required in service overrides delete api
This is to mark these fields as optional in the open api spec. We support org/account level service overrides now and hence this is needed. 
<details>
</details>
<details>
- …
=> [feat]: [CDS-57663]: Mark org/project identifier as not required for service overrides delete

dockerization/delegate/Dockerfile, dockerization/delegate/Dockerfile-minimal
In ARM64 base vm, 3rd party libs were not getting installed because we were passing default amd64 value to and for arm64 also it was taking that default value.
Testing:
Create the test image [testim](https://hub.docker.com/layers/harness/cv-demo/testim/images/sha256-106b9ccd0d82b3a6341489a0fd7caceb2aaf132a75cc5ba7476d143999f3b0cf?context=explore)
Installed the docker delegate in graviton aws machine.
Check the delegate logs and it was showing tools (kubectl, helm, etc were installed).
Type the kubcetl and kustomize
<details>
</details>
<details>
You can run multiple PR check triggers by comma separating them in a single comment. …
=> fix:[del-6144] fixing targetarch for arm64 base image

260-delegate/src/test/java/software/wings/delegatetasks/terraform/TerraformInputVariablesObtainTaskTest.java, 260-delegate/src/test/java/software/wings/delegatetasks/terraform/helper/TerraformConfigInspectClientImplTest.java, 260-delegate/src/test/resources/kryo-registrations.txt, 400-rest/src/main/java/software/wings/service/impl/InfrastructureProvisionerServiceImpl.java, 400-rest/src/test/resources/manager-kryo-registrations.txt, 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelper.java, 930-delegate-tasks/src/main/java/io/harness/delegate/task/terraform/TerraformBaseHelperImpl.java, 930-delegate-tasks/src/main/java/software/wings/beans/delegation/TerraformProvisionParameters.java, 930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformFetchTargetsTask.java, 930-delegate-tasks/src/main/java/software/wings/delegatetasks/TerraformInputVariablesObtainTask.java, 930-delegate-tasks/src/main/java/software/wings/delegatetasks/terraform/helper/TerraformConfigInspectClientImpl.java, 930-delegate-tasks/src/main/java/software/wings/service/impl/TerraformConfigInspectServiceImpl.java, 930-delegate-tasks/src/main/java/software/wings/service/intfc/TerraformConfigInspectService.java, 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java, 960-api-services/src/main/java/io/harness/delegate/clienttools/TerraformConfigInspectVersion.java, 960-api-services/src/main/java/software/wings/delegatetasks/terraform/BUILD.bazel, 960-api-services/src/main/java/software/wings/delegatetasks/terraform/TerraformConfigInspectClient.java, 970-api-services-beans/src/main/java/io/harness/provision/model/TfConfigInspectVersion.java, 970-api-services-beans/src/main/java/io/harness/serializer/kryo/ApiServiceBeansKryoRegister.java
<details>
</details>
<details>
- …
=> [feat]: [CDS-56695]: add support for terraform-config-inspect v1.2

930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java
License subscriptions require customer email to be attached to the Stripe subscription metadata.
<details>
</details>
<details>
- Feature Name …
=> fix: [PLG-2092]: Fix for Stripe subscription request missing customer email

125-cd-nextgen/src/main/java/io/harness/cdng/creator/CDNGPlanCreatorProvider.java
- Correct the folder path for AWS Lambda Steps
<details>
</details>
<details>
- Trigger CommonChecks: `trigger commonchecks`
- Feature Name Check: …
=> feat: [CDS-57955]: Correct the folder path for AWS Lambda Steps

pipeline-service/build.properties, pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleBgMigrationDetails.java, pipeline-service/service/src/main/java/io/harness/pms/migration/PipelineCoreTimeScaleMigrationDetails.java
- Set the proper version branch release/pipeline-service/1_27
- [fix]: [CDS-58167]: Move environment group ref column rename migration to Background
Move RenameEnvGroupRefInServiceInfraInfoTable to background timescale migration. 
<details>
- 
</details>
<details>
You can run multiple PR check triggers by comma separating them in a single …
=> [fix]: [CDS-58167]: Move environment group ref column rename migration to Background

420-delegate-service/src/main/java/io/harness/service/impl/DelegateCacheImpl.java
Summary
- Add null check to check if delegate exists before adding to RLocalCachedMap
Test
-Local sanity
<details>
- 
</details>
<details>
- …
=> fix: [DEL-6128]: Add to RlocalCachedMap cache only after checking delegate exists

idp-service/contracts/openapi/v1/openapi.yaml, idp-service/src/main/java/io/harness/idp/gitintegration/BUILD.bazel, idp-service/src/main/java/io/harness/idp/gitintegration/mappers/ConnectorDetailsMapper.java, idp-service/src/main/java/io/harness/idp/gitintegration/repositories/CatalogConnectorRepositoryCustom.java, idp-service/src/main/java/io/harness/idp/gitintegration/repositories/CatalogConnectorRepositoryCustomImpl.java, idp-service/src/main/java/io/harness/idp/gitintegration/resources/ConnectorInfoApiImpl.java, idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationService.java, idp-service/src/main/java/io/harness/idp/gitintegration/service/GitIntegrationServiceImpl.java
<details>
- 
</details>
<details>
- …
=> feat: [IDP-355]: Support for Default Connector - GET API

332-ci-manager/app/src/test/java/io/harness/app/CIDashboard/CIDashboardsApisTest.java, 332-ci-manager/contracts/src/main/java/io/harness/cimanager/dashboard/api/CIDashboardHelper.java, 332-ci-manager/contracts/src/main/java/io/harness/cimanager/dashboard/api/DashboardBuildExecutionInfo.java, 332-ci-manager/service/src/main/java/io/harness/ci/dashboard/CIOverviewDashboardServiceImpl.java
<details>
- 
</details>
<details>
- …
=> feat: [CI-7480]: added changeRate in buildExecution API

332-ci-manager/config/ci-manager-config.yml, product/ci/addon/docker/Dockerfile.linux.arm64
<details>
- 
</details>
<details>
- …
=> feat: [CI-7794]: Change config to take relevant images

935-subscription-sdk/src/main/java/io/harness/subscription/helpers/impl/StripeHelperImpl.java, build.properties
Invoice details on newly created invoices were missing accountIdentifier in metadata.
Update the invoice after the subscription is updated, so that the metadata is applied to the newly created invoice.
This metadata is required to properly get routed through the identity-gateway.
<details>
- 
</details>
<details>
You can run multiple PR check …
=> feat: [PLG-2226]: Update invoice metadata after subscription update

srm-service/modules/cv-nextgen-service/service/src/main/resources/cvng_notification_templates/cvng_monitoredservice_et_email.txt
Need to remove 'Code Errors' from email template
<details>
- 
</details>
<details> …
=> feat: [CET-1293]: Reword email notifications for CET module

product/ci/addon/tasks/run.go, product/ci/addon/tasks/run_test.go, product/ci/addon/tasks/runtests.go
<details>
- 
</details>
<details>
- …
=> [feat]: [CI-7933]: Revert output vars to old logic for run and runtest

dockerization/delegate/Dockerfile, dockerization/delegate/Dockerfile-minimal
The initial issue is https://harness.atlassian.net/browse/CDS-59060, jGit was failing to fetch some tags with special characters. One of the fixes was to add LANG env variable to delegate. We found that this was not enough for immutable delegates as en_US.en_US.UTF-8 was not installed.
With microdnf install glibc-langpack-en we're installing en locales on delegate.
In order to test I run a delegate from that image and run a terraform step what would fetch a repo with has some tags with special characters (test passed) .
<details>
- 
- `trigger …
=> [fix]: [CDS-59060]: install glibc-langpack-en

956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java, srm-service/build/container/scripts/replace_configs.sh, srm-service/config/cv-nextgen-config.yml, srm-service/modules/cv-nextgen-service/service/BUILD.bazel, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/CVServiceModule.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/VerificationApplication.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/VerificationConfiguration.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/cdng/resources/VerifyStepResourceImpl.java, srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/cdng/services/impl/resources/VerifyStepResourceImplTest.java, srm-service/modules/cv-nextgen-service/service/src/test/resources/test-config.yml
* feat:[OIP-52]: Add telemetry for the verify step result.
* feat:[OIP-52]: fix typo.
* feat:[OIP-52-telemetry]: Address PR comment.
<details>
- 
</details>
<details> …
=> feat:[OIP-52]: Add telemetry for '/overview' API (#47256)

840-template-service/src/main/java/io/harness/template/services/NGTemplateServiceImpl.java, 840-template-service/src/main/java/io/harness/template/utils/TemplateUtils.java
<details>
- 
</details>
<details>
- …
=> hotfixpreqa: [feat]: [CDS-69027]: Applied EnforceGitX only to remoteEnabled TemplateTypes.

954-connector-beans/src/main/java/io/harness/delegate/beans/connector/gcpsecretmanager/GcpSecretManagerConnectorDTO.java
Add GCP SM connector valdation
<details>
- 
</details>
<details>
- …
=> fix: [PL-32527]: Add GCP SM connector valdation

332-ci-manager/service/src/main/java/io/harness/ci/execution/states/V1/InitializeTaskStepV2.java
<details>
- 
</details>
<details>
- …
=> fix: [CI-7928]: fixed strategy expansion

125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/PluginInfoProviderHelper.java
<details>
- 
</details>
<details>
- …
=> fix: [CDS-69562]: Fix SAM port conflicts issue

332-ci-manager/service/src/main/java/io/harness/ci/execution/states/AbstractStepExecutable.java, 332-ci-manager/service/src/test/java/io/harness/ci/states/BackgroundStepTest.java, 332-ci-manager/service/src/test/java/io/harness/ci/states/CIDelegateTaskExecutorTest.java, 332-ci-manager/service/src/test/java/io/harness/ci/states/RunStepTest.java, 879-pipeline-ci-commons/src/main/java/io/harness/execution/CIDelegateTaskExecutor.java, 879-pipeline-ci-commons/src/main/java/io/harness/pms/sdk/core/plugin/CommonAbstractStepExecutable.java
<details>
- 
</details>
<details>
- …
=> fix: [CI-7862]: added stageId in abstractStepExecutable

400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java
Summary: Add Null check on checkprofile
Test:
Local test 
<details>
- 
</details>
<details> …
=> fix: [PL-38280]: Fix NPE on checkprofile call

450-ce-views/src/main/java/io/harness/ccm/views/graphql/ViewsQueryBuilder.java
- Added condition to remove empty string from filter values.
- Added clickhouse query support for labels.values.
<details>
- 
</details>
<details>
- …
=> [fix]: [CCM-12510]: Added condition to remove empty string from filter values

360-cg-manager/src/main/java/software/wings/resources/secretsmanagement/GcpSecretsManagerResourceV2.java, 440-connector-nextgen/src/main/java/io/harness/connector/entities/embedded/gcpsecretmanager/GcpSecretManagerConnector.java, 440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/GcpSecretManagerDTOToEntity.java, 440-connector-nextgen/src/main/java/io/harness/connector/mappers/secretmanagermapper/GcpSecretManagerEntityToDTO.java, 440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSecretManagerDTOToEntityTest.java, 440-connector-nextgen/src/test/java/io/harness/connector/mappers/secretmanagermappper/GcpSecretManagerEntityToDTOTest.java, 440-connector-nextgen/src/test/resources/schema/Connectors/all.json, 890-sm-delegate/src/main/java/io/harness/ng/GcpSecretManagerConfigDTOMapper.java, 931-encryption-service/src/java/io/harness/encryptors/clients/GcpSecretsManagerEncryptor.java, 931-encryption-service/src/test/io/harness/encryptors/clients/GcpSecretsManagerEncryptorTest.java, 931-secret-providers/src/java/io/harness/mappers/GcpSecretManagerConfigMapper.java, 931-secret-providers/src/java/software/wings/beans/GcpSecretsManagerConfig.java, 940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/GcpSecretManagerConfigDTO.java, 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/gcpsecretmanager/GcpSecretManagerConnectorDTO.java, 954-connector-beans/src/test/java/io/harness/delegate/beans/connector/gcpsecretmanager/GcpSecretManagerConnectorDTOTest.java, 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java, 970-ng-commons/src/main/java/io/harness/SecretManagerDescriptionConstants.java, build.properties
[PL-32537](https://harness.atlassian.net/browse/PL-32537): Backend changes for GCP SM Workload Identity
Develop PR: https://github.com/harness/harness-core/pull/47169/files
Hotfixes: https://github.com/harness/harness-core/pull/47404/files, https://github.com/harness/harness-core/pull/47563/files
Adding validations: https://github.com/harness/harness-core/pull/47679/files, https://github.com/harness/harness-core/pull/47742/files
<details>
- 
-  Trigger multiple builds together: For eg: …
=> fix: [PL-32537]: Backend changes for GCP SM Workload Identity

pipeline-service/service/src/test/java/io/harness/pms/plan/execution/PlanExecutionResourceTest.java
Added UTs for Coverage
<details>
- 
</details>
<details> …
=> [feat]: [CDS-69831]: Added UTs for Coverage.

960-api-services/src/main/java/io/harness/k8s/KubernetesContainerServiceImpl.java, 960-api-services/src/main/java/io/harness/k8s/KubernetesHelperService.java, 960-api-services/src/test/java/io/harness/k8s/KubernetesHelperServiceTest.java
Develop PR for prod hotfix https://github.com/harness/harness-core/pull/48602
<details>
- 
</details>
<details>
- …
=> fix: [CDS-70386]: Ignore fabric8 failures selectively

332-ci-manager/build.properties, 332-ci-manager/service/src/main/java/io/harness/ci/telemetry/CiTelemetryPublisher.java, 332-ci-manager/service/src/test/java/io/harness/telemetry/CiTelemetryPublisherTest.java
<details>
- 
</details>
<details>
- …
=> fix: [CI-8304]: CI data in segment

884-pms-commons/src/main/java/io/harness/monitoring/EventMonitoringServiceImpl.java, 884-pms-commons/src/main/java/io/harness/pms/events/base/PmsAbstractMessageListener.java, 884-pms-commons/src/main/java/io/harness/pms/events/base/PmsBaseEventHandler.java, 884-pms-commons/src/main/java/io/harness/pms/sdk/execution/events/NotifyEventHandler.java, 953-yaml-commons/src/main/java/io/harness/pms/sdk/execution/events/PmsCommonsBaseEventHandler.java, 970-ng-commons/src/main/java/io/harness/monitoring/MonitoringInfo.java, clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/async/AsyncCreatorBaseEventHandler.java, pipeline-service/service/src/main/java/io/harness/plan/consumers/PartialPlanResponseEventHandler.java, pipeline-service/service/src/test/java/io/harness/plan/consumers/PartialPlanResponseEventHandlerTest.java
Fixing the redis-queue-time metric graph for PMS events.
Related DOC: https://harness.atlassian.net/wiki/spaces/PIPE/pages/21404647460/01+June-2023+Load-test#Action-items%3A.1
<details>
- 
</details>
<details>
- Compile: `trigger …
=> [feat]: [CDS-71224]: Fixing the redis-queue-time metric graph for PMS events

878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java, 878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java, 878-ng-common-utilities/src/main/java/io/harness/gitx/GitXTransientBranchGuard.java, 970-ng-commons/src/main/java/io/harness/gitsync/interceptor/GitEntityInfo.java, template-service/service/src/main/java/io/harness/repositories/NGTemplateRepositoryCustomImpl.java, template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java
- Added support for transient branch which overrides default branch selection logic if present.
- If template ref in a yaml has any git branch present, it should be set as transient branch while fetching the template which essentially overrides everything and template is fetched from given branch only.
- The value should be reset as soon as operation is over as other templates may or may not abide by default logic, thus this transient branch shouldn't affect other flows.
<details>
- 
- …
=> feat: [CDS-71298]: Added logic to override default branching logic for templates in case static branch is present

953-yaml-commons/src/main/java/io/harness/pms/yaml/YamlUtils.java, pipeline-service/build.properties
<details>
- 
</details>
<details>
- …
=> fix: [CDS-71353]: use new object mapper to enable check duplicate in a method

930-ng-license-manager/src/main/java/io/harness/licensing/helpers/ModuleLicenseSummaryHelper.java
<details>
- 
</details>
<details>
- …
=> fix: [CHAOS-1823]: Adding null check for summary license api for chaos  experiment

scripts/cie/sonar/sonar-pr-scanner.sh, tools/bazel/GenTestRules.bzl
<details>
- 
</details>
<details>
- …
=> feat: [BT-4169]: Selecting tests for PR for coverage

template-service/build.properties, template-service/service/src/main/java/io/harness/template/helpers/TemplateMergeServiceHelper.java
<details>
- 
</details>
<details>
- …
=> feat: [CDS-71846]: Remove updating branch from Git context while getting template

400-rest/src/main/java/software/wings/resources/UserResourceNG.java, 400-rest/src/test/java/software/wings/security/AuthRuleFilterTest.java
Summary: Fix unit tes
<details>
- 
</details>
<details> …
=> fix: [PL-38777]: Fix Authfilter unit test

pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/ContainerStepCleanupHelper.java
<details>
- 
</details>
<details>
- …
=> [feat]: [CI-8459]: Handle podCleanup details

400-rest/src/test/java/software/wings/security/AuthenticationFilterTest.java
Summary:
Fix Unit test
<details>
- 
</details>
<details> …
=> fix: [PL-39441]: Fix unit test

batch-processing/build.properties, batch-processing/service/src/main/java/io/harness/batch/processing/service/impl/GoogleCloudStorageServiceImpl.java, batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java
Added this enhancement behind Feature Flag
<details>
- 
</details>
<details>
- …
=> [fix]:[CCM-12752]: hfix for relativity with feature flag

400-rest/src/main/java/software/wings/security/authentication/BatchQueryConfig.java, batch-processing/build.properties, batch-processing/build/container/scripts/replace_configs.sh, batch-processing/service/batch-processing-config.yml, batch-processing/service/src/main/java/io/harness/batch/processing/service/impl/GoogleCloudStorageServiceImpl.java, batch-processing/service/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, batch-processing/service/src/test/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTaskletTest.java, dockerization/batch-processing/scripts/replace_configs.sh
CCM-12752: Hotfix is done on 796xx so doing hotfix on 797xx
CCM-12705: PublishedMessages read batch size to 1000
<details>
- 
</details>
<details>
- …
=> [fix]:[CCM-12752]: hfix for relativity to add FF

360-cg-manager/chart/templates/virtualservice.yaml, pipeline-service/chart/templates/virtualservice.yaml
Fixing naming
<details>
- 
</details>
<details>
- MessageMetadata: `trigger …
=> feat:[IE-129]: Identation fix for pipeline service  and fixing virtualservice for cg-manager

100-migrator/config/manifest.yaml, 110-change-data-capture/config/manifest.yaml, 120-ng-manager/config/manifest.yaml, 310-iacm-manager/config/manifest.yaml, 315-sto-manager/config/manifest.yaml, 332-ci-manager/config/manifest.yaml, 360-cg-manager/chart/templates/virtualservice.yaml, 360-cg-manager/config/manifest.yaml, access-control/config/manifest.yaml, audit-event-streaming/config/manifest.yaml, batch-processing/config/manifest.yaml, build/build_jar.sh, ce-nextgen/config/manifest.yaml, pipeline-service/chart/templates/virtualservice.yaml, pipeline-service/config/manifest.yaml, platform-service/config/manifest.yaml, srm-service/config/manifest.yaml, template-service/config/manifest.yaml
<details>
- 
</details>
<details>
- …
=> feat:[IE-130]: Cleaning up manifest.yaml

100-migrator/config/manifest.yaml, 110-change-data-capture/config/manifest.yaml, 120-ng-manager/config/manifest.yaml, 310-iacm-manager/config/manifest.yaml, 315-sto-manager/config/manifest.yaml, 332-ci-manager/config/manifest.yaml, 360-cg-manager/chart/templates/virtualservice.yaml, 360-cg-manager/config/manifest.yaml, access-control/config/manifest.yaml, audit-event-streaming/config/manifest.yaml, batch-processing/config/manifest.yaml, build/build_jar.sh, ce-nextgen/config/manifest.yaml, pipeline-service/chart/templates/virtualservice.yaml, pipeline-service/config/manifest.yaml, platform-service/config/manifest.yaml, srm-service/config/manifest.yaml, template-service/config/manifest.yaml
This is used by infra evol project
This doesn't impact anything at this moment
Tested:
https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/ci/orgs/default/projects/FEATUREBUILDS/pipelines/Build_Harness/executions/xb9qhiNARpO6iTyZEF1sag/pipeline?storeType=INLINE
Build harness-core services
<details>
- 
</details>
<details>
You can run …
=> feat: [IE-130]: Refactoring manifest yaml for building services

pipeline-service/service/src/main/java/io/harness/pms/plan/execution/ExecutionDetailsResource.java
<details>
- 
</details>
<details>
- …
=> [fix]: [CDS-72155]: Adding ACL check for v2 api

pipeline-service/modules/ng-triggers/src/test/java/io/harness/ngtriggers/eventmapper/filters/impl/BitbucketPRCommentTriggerFilterTest.java, pipeline-service/modules/ng-triggers/src/test/java/io/harness/ngtriggers/eventmapper/filters/impl/BuildTriggerEventConditionsFilterTest.java
<details>
- 
</details>
<details>
- …
=> feat: [CDS-69936]: UT added

platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/ResourceType.java, platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/ResourceTypeConstants.java
Added the following two new audit trail resources:
- CET Agent Tokens
- CET Critical Event Definitions
CET will be logging audit trail events for these resources.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/49754)
=> feat: [CET-1364] Log CET audit trail events

136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitDefaultBranchCacheHelper.java, 136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java, 136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/GitDefaultBranchCacheHelperTest.java
Have added code to integrate get batch file flow for templates with default branch caching. Have tested out the get batch file for templates with git default branch caching FF enabled and its working as expected.
<details>
- 
</details>
<details>
You can run multiple PR check triggers by comma separating them in a single comment. e.g. …
=> [feat]: [CDS-72587]: Integrated get batch file with default branch caching

pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/eventmapper/filters/impl/GithubIssueCommentTriggerFilter.java, pipeline-service/modules/ng-triggers/src/test/java/io/harness/ngtriggers/eventmapper/filters/impl/GithubIssueCommentTriggerFilterTest.java
Throw exception when we error response from find pr details
<details>
- 
</details>
<details> …
=> [fix]: [CDS-72209]: Throw exception when we error response from find pr details

956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
[CET-1262](https://harness.atlassian.net/browse/CET-1262) added FF (adding BE changes, so want to make sure we are flexible)
<details>
- 
</details>
<details> …
=> feat: [CET-1547]: Add FF for platform MS integration

332-ci-manager/config/ci-manager-config.yml
<details>
- 
</details>
<details>
- …
=> feat: [CI-8680]: replace config for gitness jwt

120-ng-manager/src/main/java/io/harness/ng/core/migration/background/StaleUserMetadataCleanupMigration.java, 120-ng-manager/src/main/java/io/harness/ng/migration/NGCoreBackgroundMigrationDetails.java, 400-rest/src/main/java/software/wings/resources/UserResourceNG.java, build.properties
<details>
- 
</details>
<details>
- …
=> fix: [PL-40075]: [PROD] Added migration to delete stale entries in UserMetadata

100-migrator/src/main/java/io/harness/ngmigration/utils/CaseFormat.java, 100-migrator/src/main/java/io/harness/ngmigration/utils/MigratorUtility.java
added support for harness ui format for identifiers
<details>
- 
</details>
<details> …
=> [fix]: [CDS-74293]: added support for ui format for identifier

332-ci-manager/build.properties, 960-api-services/src/main/java/io/harness/git/GitClientHelper.java, 960-api-services/src/test/java/io/harness/git/GitClientHelperTest.java
<details>
- 
</details>
<details>
- …
=> fix: [CI-8680]: api endpoint for harness scm

950-events-framework-monitor/src/main/java/service/RedisStreamsMetricsAggregatorImpl.java, build.properties
logs - https://cloudlogging.app.goo.gl/t6E271rZGYNe1JDc9
Basically Range Query is failing for pipeline_orchestration stream and that is failing all other streams metric publishing as well. So in this PR majorly I have done three changes:
Reduced Range query batch size to 100 so that it does not timeout
Added exception handling so that one streams failure should not impact other streams metric publishing
Changed Memory computation logic to use MEMORY USAGE command since its support now in both Prod and QA Redis Enterprise.
<details>
- 
- `trigger …
=> [fix]: [PL-40273]: Fixed exception handling and introduced memoryusagecommand

access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
<details>
- 
</details>
<details>
- …
=> feat: [CET-1531]: Added CET Permissions To Default Admin Roles

125-cd-nextgen/modules/azure/core/src/main/java/io/harness/cdng/provision/azure/AzureCommonHelper.java, 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/CDStepHelper.java, 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/common/resources/BUILD.bazel, 125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/common/resources/GitResourceServiceHelper.java, 125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelper.java, 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/TerraformStepHelper.java, 125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt/TerragruntStepHelper.java, 125-cd-nextgen/src/test/java/io/harness/cdng/CDStepHelperTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/common/resources/GitResourceServiceHelperTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/provision/azure/AzureCommonHelperTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/provision/cloudformation/CloudformationStepHelperTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/provision/terraform/TerraformStepHelperTest.java, 125-cd-nextgen/src/test/java/io/harness/cdng/provision/terragrunt/TerragruntStepHelperTest.java, 440-connector-nextgen/src/main/java/io/harness/connector/validator/scmValidators/GitConfigAuthenticationInfoHelper.java, 932-connector-task/src/main/java/io/harness/connector/task/git/GitAuthenticationDecryptionHelper.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/connector/awsconnector/AwsCFTaskParamsRequest.java
Changes are regarding adding support for Github App authentication for cloudformation and azure tasks. Changes include both manager side changes as delegate changes are already done.
Tests done:
https://docs.google.com/spreadsheets/d/1xACyF9YSLQ7bIIzIYVp17CsmynD_0ofQf4HCwlq8pBc/edit#gid=1092161727
<details>
- 
</details>
<details>
You can run …
=> feat:[CDS-73838]: support for Github app authentication for cloudformation and azure

build/build_dist.sh
<details>
- 
</details>
<details>
- …
=> feat: [IE-197]:Multistage dockerfile support for srm-service

idp-service/contracts/openapi/v1/openapi.yaml
This is for adding the open API spec
for 
Scorecard Score API -
-> API- Scorecard score overall summary
-> API- Scorecards for getting only scores, and re calibrate
-> API- Scorecards for getting the graph data.
Data Source API
-> API - Getting data sources for account
-> API - Getting the data points in data sources 
<details>
- 
</details>
<details>
<summary>PR Check …
=> feat: [IDP-972]: Open API spec for scorecard scores and data source apis

953-yaml-commons/src/main/java/io/harness/pms/yaml/individualschema/PipelineSchemaParserV0.java
Added StrategyNode Individual Schema for V0 Static Schema Parser
Schema for StrategyNode 
```
{
"title":"StrategyConfig",
"type":"object",
"properties":{
"matrix":{
"oneOf":[
{
"$ref":"#/definitions/pipeline/common/ParameterFieldMatrixConfigInterface"
},
{
"type":"string",
"pattern":"^<\\+input>((\\.)((executionInput\\(\\))|(allowedValues|default|regex)\\(.+?\\)))*$",
"minLength":1
}
]
},
"parallelism":{
"oneOf":[
{
"type":"integer",
"format":"int32",
"minimum":0
},
{
"type":"string",
"pattern":"(<\\+.+>.*)",
"minLength":1
}
]
},
"repeat":{
"$ref":"#/definitions/pipeline/common/HarnessForConfig"
},
"description":{
"desc":"This is the description for StrategyConfig"
}
},
"$schema":"http://json-schema.org/draft-07/schema#",
"allOf":[
{
"oneOf":[
{
"required":[
"repeat"
]
},
{
"required":[ …
```
=> feat: [CDS-75211]: Added StrategyNode Individual Schema for V0 Static Schema Parser

360-cg-manager/chart/templates/config.yaml
Adding Iterator config for Delegate DMS
Build:
https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/DevSpaces/pipelines/Build_Services/executions/EQUv7eP7SG2NzrP97rRHGg/pipeline?connectorRef=harnessplinfra&repoName=harness-pl-infra&branch=master&storeType=REMOTE&stage=wZeGfqg7StSakUSUp1NfhQ&stageExecId=CAXJtrRUQq-L9MpPGCVmFA
Deploy: 
https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/DevSpaces/pipelines/Deploy_Services/executions/Su9NlHuZTFevIkW6iv6KHg/pipeline?connectorRef=harnessplinfra&repoName=harness-pl-infra&branch=master&storeType=REMOTE
<details>
- 
- …
=> fix:[IE-360]: Fix iterator config for Harness-manager

access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml, access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml, access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml
`COMMITCHECK` isn’t a resource in harness itself, it’s just a child resource of a repository.
As such, we should move it’s permissions under `REPOSITORY` resource type, such that a user will be able to configure the permission per repo (otherwise it would only be per proj/org/acc).
user without permission trying to submit status check:
User with permission trying to submit status check:
<details>
- 
- Immutable delegate …
=> fix: [CODE-793]: Remove `COMMITCHECK` Resource and move `code_commitCheck_report` under `REPOSITORY` Resource

120-ng-manager/chart/templates/config.yaml, 120-ng-manager/config.yml, 120-ng-manager/src/main/java/io/harness/ng/NextGenConfiguration.java, 120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable/UpdateVersionInfoTask.java, 120-ng-manager/src/main/resources/mvi/baseinfo.json, dockerization/ng-manager/scripts/replace_configs.sh
Related PR: https://github.com/harness/harness-core/pull/52046 
1. Added support for fetching the STO version number in Release Notes
2. Refactoring the code by adding switch-case instead of if-else cases and error handling with try-catch blocks
Tested locally:
1. Ran the sto-core server locally by following https://github.com/harness/sto-core#readme 
2. successfully GET request locally to get the version in the response
3. Updated the moduleVersionInfo collection's document for STO as follows:
Note:
Gotchas for running the postgres in local for sto-core
1. `docker pull postgres:14.4`
2. `docker run -d --name postgresSto -p 5432:5432 -e POSTGRES_PASSWORD=sto_local postgres:14.4`
3. `docker exec postgresSto sh -c 'echo "DO \$\$ BEGIN IF NOT EXISTS(SELECT schema_name FROM …
=> feat:[PLG-2233] Add release version support for STO

490-ce-commons/src/main/java/io/harness/ccm/commons/dao/recommendation/K8sRecommendationDAO.java
Query optimisation for Nodepool Recommendations
<details>
- 
</details>
<details> …
=> [fix]:[CCM-10575]: Optimising the query

930-delegate-tasks/src/main/java/io/harness/delegate/task/artifacts/s3/S3ArtifactTaskNG.java, 930-ng-license-manager/src/main/java/io/harness/subscription/services/impl/SubscriptionServiceImpl.java, 935-subscription-sdk/src/main/java/io/harness/subscription/helpers/StripeHelper.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/S3ArtifactDelegateResponse.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/bamboo/BambooArtifactDelegateRequest.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/servicenow/ServiceNowTaskNGParameters.java, 950-subscription-beans/src/main/java/io/harness/subscription/dto/SubscriptionDetailDTO.java, 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/servicenow/ServiceNowAuthCredentialsDTO.java, 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/servicenow/ServiceNowRefreshTokenDTO.java, 960-api-services/src/main/java/io/harness/artifacts/beans/BuildDetailsInternal.java, 960-api-services/src/main/java/io/harness/artifacts/gar/GarRestClient.java, 960-api-services/src/main/java/io/harness/artifacts/gar/beans/GarInternalConfig.java, 960-api-services/src/main/java/io/harness/artifacts/gcr/beans/GcrInternalConfig.java, 960-api-services/src/main/java/io/harness/artifacts/githubpackages/beans/GithubMavenMetaData.java, 960-api-services/src/main/java/io/harness/artifacts/githubpackages/beans/SnapshotVersion.java, 960-api-services/src/main/java/io/harness/artifacts/githubpackages/beans/SnapshotVersions.java, 960-api-services/src/main/java/io/harness/googlefunctions/GcpInternalConfig.java, 960-api-services/src/main/java/io/harness/servicenow/auth/refreshtoken/RefreshTokenRestClient.java, pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/JiraApprovalStep.java
<details>
- 
</details>
<details>
- …
=> [feat]: [CDS-77038]: code pulse added

pipeline-service/build.properties, pipeline-service/service/src/main/java/io/harness/PipelineServiceApplication.java, pipeline-service/service/src/main/java/io/harness/PipelineServiceModule.java
<details>
- 
</details>
<details>
- …
=> feat:  [CDS-78881]: Seperating threads change for load test

332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/GitBuildStatusUtility.java, 332-ci-manager/service/src/test/java/io/harness/ci/execution/execution/BuildStatusPushParametersTest.java, 332-ci-manager/service/src/test/java/io/harness/ci/execution/states/DockerStepTest.java, 332-ci-manager/service/src/test/java/io/harness/ci/execution/stateutils/buildstate/BuildSetupUtilsTest.java, 332-ci-manager/service/src/test/java/io/harness/ci/execution/stateutils/buildstate/providers/InternalContainerParamsProviderTest.java, 879-pipeline-ci-commons/src/main/java/io/harness/utils/CiCodebaseUtils.java, 884-pms-commons/src/main/java/io/harness/pms/execution/utils/AmbianceUtils.java, pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/container/utils/ContainerParamsProviderTest.java, pipeline-service/modules/orchestration/src/test/java/io/harness/engine/events/PipelineStageExecutionUpdateEventHandlerTest.java, pipeline-service/modules/orchestration/src/test/java/io/harness/engine/events/PipelineStepExecutionUpdateEventHandlerTest.java, pipeline-service/modules/orchestration/src/test/java/io/harness/engine/executions/step/StepExecutionEntityServiceTest.java, pipeline-service/modules/orchestration/src/test/java/io/harness/engine/pms/execution/strategy/plan/PlanExecutionStrategyTest.java, pipeline-service/modules/pms-contracts/src/main/proto/io/harness/pms/contracts/plan/execution_metadata.proto, pipeline-service/service/src/test/java/io/harness/pms/migration/PopulateAmbianceFieldsAtFirstLevelInApprovalInstancesMigrationTest.java
Changes - Removing executionUuid field usage of execution_metadata.proto
This is required to get rid of execution metadata from ambiance
Impact - Moved from executionUUid to planExecution field directly inside in ambiance
Testing - Tested few running executions in local, there were no issues
<details>
- 
</details>
<details>
You can run …
=> [fix]: [CDS-78981]: Removing executionUuid field usage of execution_metadata.proto

product/ci/addon/tasks/runtests.go, product/ci/addon/tasks/runtests_test.go, product/ci/addon/testintelligence/ruby/helper.go, product/ci/addon/testintelligence/ruby/rspec.go
<details>
- 
</details>
<details>
- …
=> feat: [CI-9117]: Ruby runner sync with latest agent

100-migrator/src/main/java/io/harness/ngmigration/service/workflow/WorkflowHandler.java
<details>
- 
</details>
<details>
- …
=> fix: [CDS-76799]: adding loop strategy to canary workflows

360-cg-manager/chart/Chart.yaml, 360-cg-manager/chart/values.yaml
<details>
- 
</details>
<details>
- …
=> fix: [CDS-79772]: GitOps gitlab HF with correct images

platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/beans/custom/executions/NodeExecutionEventData.java
<details>
- 
</details>
<details>
- …
=> [feat]: [CDS-80147]: Added RunSequence to Audit EventData

125-cd-nextgen/src/main/java/io/harness/cdng/gitops/GitOpsStepUtils.java, 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/MergePRStep.java, 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/UpdateReleaseRepoStep.java, 125-cd-nextgen/src/main/java/io/harness/cdng/gitops/revertpr/RevertPRStep.java
<details>
- 
</details>
<details>
- …
=> add extract token logic

120-ng-manager/src/main/java/io/harness/ng/support/client/CannyClient.java, 120-ng-manager/src/main/java/io/harness/ng/support/client/CannyClientConstants.java, 120-ng-manager/src/main/java/io/harness/ng/support/dto/CannyPostResponseDTO.java, 120-ng-manager/src/main/java/io/harness/ng/support/resource/CannyResource.java, 120-ng-manager/src/test/java/io/harness/ng/support/CannyClientTest.java
API under NG Manager to create a post on canny. This will be used to redirect tickets of type "FEATURE_REQUEST" to canny instead of Zendesk.
<details>
- 
</details>
<details>
- CodeformatCheckstyle: …
=> feat: [CDS-78464]: API for post creation on Canny

933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java
url can be both qa.git.harness.io/code/account/org/project/repo or qa.harness.io/code/git/account/org/project/repo
<details>
- 
</details>
<details>
- …
=> fix: [CI-9328]: fix status check to support both url pattern

310-iacm-manager/app/src/main/java/io/harness/iacm/plan/creator/stage/IACMStagePMSPlanCreator.java, 315-sto-manager/app/src/main/java/io/harness/sto/plan/creator/stage/SecurityStagePMSPlanCreator.java
Creating a private constructor of Utility class and injecting to the class causing the issue.
Removed the @Inject tag.
<details>
- 
</details>
<details> …
=> fix: [CDS-81155]: Remove the StageUtils Inject tag

310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerConfiguration.java, 310-iacm-manager/app/src/main/java/io/harness/app/IACMManagerServiceModule.java, 310-iacm-manager/config/iacm-manager-config.yml, 332-ci-manager/app/src/main/java/io/harness/ci/CIManagerConfiguration.java, 332-ci-manager/app/src/main/java/io/harness/ci/CIManagerServiceModule.java, 332-ci-manager/app/src/test/java/io/harness/app/impl/CIManagerRule.java, 332-ci-manager/build.properties, 332-ci-manager/chart/templates/config.yaml, 332-ci-manager/config/ci-manager-config.yml, 332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/ConnectorUtils.java, 332-ci-manager/service/src/test/java/io/harness/ci/executionplan/rule/CIExecutionRule.java, 332-ci-manager/service/src/test/java/io/harness/ci/states/codebase/CodeBaseStepTest.java, 879-pipeline-ci-commons/src/main/java/io/harness/ci/utils/BaseConnectorUtils.java, 933-ci-commons/src/main/java/io/harness/git/checks/GitStatusCheckHelper.java, 933-ci-commons/src/test/java/io/harness/ci/git/checks/GitStatusCheckHelperTest.java, 952-scm-java-client/src/test/java/io/harness/impl/scm/ScmServiceClientImplTest.java, 960-api-services/src/main/java/io/harness/git/GitClientHelper.java, 960-api-services/src/test/java/io/harness/git/GitClientHelperTest.java, WORKSPACE, product/ci/scm/git/git.go, product/ci/scm/go.mod, product/ci/scm/go.sum, product/ci/scm/parser/testdata/harness_pr.json.golden
<details>
- 
</details>
<details>
- …
=> feat: [CI-9328]: ci-harness code integration

product/ci/engine/docker/Dockerfile.windows.amd64.ltsc2022
<details>
- 
</details>
<details>
- …
=> fix: [CI-9755]: le dockerfile syntax

332-ci-manager/config/ci-manager-config.yml
<details>
- 
</details>
<details>
- …
=> feat: [CI-9755]: updated vm image versions for win22

100-migrator/src/main/java/io/harness/ngmigration/service/importer/TriggerImportService.java
<details>
- 
</details>
<details>
- …
=> fix:[CDS-81706]: fix service ref

template-service/build/container/scripts/start_process.sh, template-service/container/scripts/start_process.sh
This PR adds open telemetry jar for template service.
<details>
- 
</details>
<details> …
=> feat: [PL-42207]: Added open telemetry jar for template service

400-rest/src/main/java/io/harness/delegate/service/DelegateVersionService.java, 400-rest/src/test/java/io/harness/delegate/service/DelegateVersionTest.java
Summary: 
- Fix issue of latest supported version showing image tag path
Test
-Unit test
<details>
- 
</details>
<details>
- CodeFormat: `trigger …
=> fix: [PL-42168]: Fix issue of latest supported version including path

pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/expressions/functors/TriggerFunctor.java, pipeline-service/modules/ng-triggers/src/test/java/io/harness/ngtriggers/expressions/TriggerFunctorTest.java
Remove triggerPayload from jsonObject returned in trigger functor
<details>
- 
</details>
<details>
- Checkstyle: …
=> [fix]: [CDS-82398]: Remove triggerPayload from jsonObject returned in trigger functor

110-change-data-capture/chart/templates/pdb.yaml, 315-sto-manager/chart/templates/pdb.yaml
Added pod disruption budget for remaining modules
1. sto-manager
2. log-service
3. change-data-capture
<details>
- 
</details>
<details>
- CodeFormat: …
=> feat: [SMP-777]: Added PDB for remaining services

953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java, 953-yaml-commons/src/test/java/io/harness/pms/merger/helpers/MergeHelperTest.java
<details>
- 
</details>
<details>
- …
=> [fix]: [CDS-81143]: fix merge iputset api throwing 500 error

125-cd-nextgen/src/main/java/io/harness/cdng/plugininfoproviders/ServerlessV2PluginInfoProviderHelper.java
IRSA and cross account support for S3 Artifact Source
<details>
- 
</details>
<details> …
=> feat:[CDS-82788]: IRSA and cross account support for S3 Artifact Source

product/log-service/config/config.go, product/log-service/handler/handler.go, product/log-service/handler/store.go, product/platform/client/client.go, product/platform/client/http.go
<details>
- 
</details>
<details>
- …
=> fix: [CI-9657]: Add vanity url support

access-control/service/src/main/resources/io/harness/accesscontrol/permissions/permissions.yml, access-control/service/src/main/resources/io/harness/accesscontrol/resources/resourceTypes.yml, access-control/service/src/main/resources/io/harness/accesscontrol/roles/managed-roles.yml, access-control/service/src/main/resources/io/harness/accesscontrol/roles/privileged-roles.yml
RBAC changes for CCM Commitment Orchestrator
<details>
- 
</details>
<details>
- …
=> feat: [CCM-15040]: Add permissions for CCM Commitment Orchestrator in Access Control

270-verification/chart/values.yaml
Adding global mongo in values.yaml
Build: https://app.harness.io/ng/account/vpCkHKsDSxK9_KYfjCTMKA/home/orgs/default/projects/DevSpaces/pipelines/Build_Services/executions/TgjZuXqRS0O64ZsRCuQm6A/pipeline?connectorRef=harnessplinfra&repoName=harness-pl-infra&branch=master&storeType=REMOTE
Deploy:
<details>
- 
</details>
<details>
You can run …
=> fix:[IE-410]: Fix verification-svc helm chart

product/log-service/cli/server/server.go, product/log-service/config/config.go, product/log-service/handler/handler.go
<details>
- 
</details>
<details>
- …
=> fix: [CI-9657]: Add separate config for vanity client

956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
This is GA'ed in prod1 and prod2.  Removing PIPELINE_ROLLBACK from code
<details>
- 
</details>
<details>
- …
=> feat:[CDS-83515]: Remove PIPELINE_ROLLBACK from code

srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/activity/services/impl/KubernetesClusterActivityUpdateHandler.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/beans/dependency/KubernetesDependencyMetadata.java, srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/activity/services/impl/ActivityServiceImplTest.java, srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/activity/services/impl/KubernetesClusterActivityUpdateHandlerTest.java, srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/core/services/impl/monitoredService/ServiceDependencyServiceImplTest.java
Customer wants to give multiple values for the workload for the given namespace.
<details>
- 
</details>
<details>
- …
=> feat: [SRM-16138]: Make workloads in the Kubernetes service dependency handle multiple values.

953-yaml-commons/src/main/java/io/harness/pms/expression/helper/InputSetMergeHelperV1.java, 953-yaml-commons/src/main/java/io/harness/pms/merger/helpers/MergeHelper.java, 953-yaml-commons/src/test/java/io/harness/pms/merger/helpers/MergeHelperTest.java, pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImpl.java, pipeline-service/service/src/test/java/io/harness/pms/plan/execution/service/PMSExecutionServiceImplTest.java
Revert the null check change made while calling yaml config and made the changes such that it affects only 1 api and doesn't cause unexpected behaviour for others
<details>
- 
</details>
<details>
- …
=> [fix]: [CDS-81143]: Revert changes to avoid unexpected behaviour for merge inputset for pipeline

ssca-manager/chart/Chart.yaml, ssca-manager/chart/templates/ingress.yaml
<details>
- 
</details>
<details>
- …
=> feat: [SSCA-921]: fix ingress rewrite for v1 apis

332-ci-manager/service/src/main/java/io/harness/ci/execution/plugin/CiPluginStepInfoProvider.java, 332-ci-manager/service/src/test/java/io/harness/ci/plugin/CiPluginStepInfoProviderTest.java
- need to populate ssca service end point and ssca service secret in container step group initialization.
- Added a cache to avoid calls for same pipeline execution id again and again
- Not doing the changes during pod initialization in pipeline service - Closed the previous PR with the comment -  https://github.com/harness/harness-core/pull/55033#issuecomment-1795489135
<details>
- 
- Immutable delegate `trigger …
=> feat: [SSCA-838]: populate ssca service secrets on container step group initialization

332-ssca/cd/src/main/java/io/harness/ssca/cd/CdSscaBeansRegistrar.java, pipeline-service/service/src/main/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProvider.java
<details>
- 
</details>
<details>
- …
=> feat: [SSCA-887]: remove ssca steps from pipeline service

dockerization/platform-service/scripts/replace_configs.sh, platform-service/build/container/scripts/replace_configs.sh, platform-service/config/config.yml, platform-service/modules/audit-service/src/main/java/io/harness/audit/scheduledJobs/AccountActivityMetricsPublisherService.java, platform-service/service/src/main/java/io/harness/platform/audit/AuditServiceConfiguration.java, platform-service/service/src/main/java/io/harness/platform/audit/AuditServiceSetup.java
* fix: [PL-42523]: Make account activity metrics to be configurable
<details>
- 
</details>
<details>
- Checkstyle: …
=> fix: [PL-42523]: Make account activity metrics to be configurable 

120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResource.java, 120-ng-manager/src/main/java/io/harness/ng/core/remote/UserGroupResourceV2.java, 123-ng-core-user/src/main/java/io/harness/ng/core/api/impl/UserGroupServiceImpl.java, 123-ng-core-user/src/test/java/io/harness/ng/core/api/impl/UserGroupServiceImplTest.java
there are two issues - 
1. while creating userGroup, validations on userGroup happens only when created through APIs not from service methods 
2. while updating userGroups, validations are present on userGroup identifiers which is not required and due to which userGroups with wrong identifiers are not getting updated anymore.
fix -
1. for fixing this issue, validation has been added on service method, now on creating userGroup from anywhere validation will always be applied.
2. for fixing update issue, validation has been removed from identifiers.
Testing - 
1. tested through creating usergroup through ldap API
2. tested creating usergroup through API
3. tested updating usergroup with wrong identifier, getting updated
<details>
- Feature build: `trigger …
=> fix: [PL-42284]: fix for adding validations on usergroup create and removing on update usergroup calls

315-sto-manager/chart/values.yaml, 332-ci-manager/chart/values.yaml
bump sto-plugin version in values file for ci and sto IE charts
<details>
- 
</details>
<details>
- Checkstyle: …
=> feat: [STO-6706]: bump sto-plugin version in values file for ci and sto

idp-service/src/main/java/io/harness/idp/scorecard/scores/repositories/ScoreRepositoryCustomImpl.java
<details>
- 
</details>
<details>
- …
=> feat: [IDP-1667]: Total Components mismatch in Scorecard stats API

400-rest/src/test/java/software/wings/scheduler/DelegateExpiryAlertIteratorTest.java
Summary:
Fix unit test
<details>
- 
</details>
<details> …
=> fix: [PL-42154]: Unit test fix

120-ng-manager/src/test/resources/server/stub/project/project-2.json, 970-ng-commons/src/main/java/io/harness/entities/ModuleType.java
Change SEI module licensing state on ONBOARDED
<details>
- 
</details>
<details> …
=> feat: [SEI-3795]: Change SEI module licensing state on ONBOARDED

400-rest/src/test/java/software/wings/service/impl/AwsHelperServiceTest.java, 930-delegate-tasks/src/main/java/io/harness/delegate/task/winrm/aws/AwsS3ArtifactDownloadHandler.java, 930-delegate-tasks/src/main/java/software/wings/service/impl/AwsHelperService.java, 930-delegate-tasks/src/test/java/io/harness/delegate/task/shell/ArtifactDownloadHandlerTest.java
Supporting CrossaccountARN with Manual and IRSA based auth for Download Artifact
<details>
- 
</details>
<details>
- …
=> fix: [CDS-81276]: supporting CrossaccountARN with Manual and IRSA based auth for Download Artifact

127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/mappers/InfrastructureFilterHelper.java
Changes include passing of account identifier and org identifier of environment instead of actual pipeline in criteria for fetching list of envs.
Tests Done :
Validation of Infra listing at pipeline studio
Infra listing validation in env page in project, org and account level.
<details>
- 
</details>
<details>
You can run multiple PR check …
=> feat:[CDS-84961]: fix for account level infra not showing up in pipeline studio

srm-service/build.properties, srm-service/chart/Chart.yaml, srm-service/chart/templates/config.yaml
<details>
- 
</details>
<details>
- …
=> feat: [SRM-16239]: Add missing config for Audit/Webhook Url in chart

120-ng-manager/src/main/java/io/harness/ng/core/invites/api/impl/InviteServiceImpl.java, 120-ng-manager/src/main/java/io/harness/repositories/invites/custom/InviteRepositoryCustom.java, 120-ng-manager/src/main/java/io/harness/repositories/invites/custom/InviteRepositoryCustomImpl.java, 120-ng-manager/src/test/resources/mongo/indexes.txt, 123-ng-core-user/src/main/java/io/harness/ng/core/invites/entities/Invite.java
Index Utilization
Tested for:
-> Tested for sorting orders supported on UI
<details>
- 
</details>
<details>
- …
=> fix: [PL-42825]: make sorting users on email and name case insensitive

120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java
Fix the project count query to resolve the
Tested for:
-> checked for project count in different scopes.
<details>
- 
</details>
<details>
- …
=> feat: [PL-40511]: Fix projects-count API to resolve timeout issue

120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/entity/Variable.java, 120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/services/impl/VariableServiceImpl.java, 120-ng-manager/modules/ng-variables/src/main/java/io/harness/repositories/variable/custom/VariableRepositoryCustom.java, 120-ng-manager/modules/ng-variables/src/main/java/io/harness/repositories/variable/custom/VariableRepositoryCustomImpl.java, 120-ng-manager/modules/ng-variables/src/test/java/io/harness/ng/core/variable/services/impl/VariableServiceImplTest.java, 120-ng-manager/src/test/resources/mongo/indexes.txt
Made sorting case insensitive 
Tested for:
-> Tested for sorting orders supported on UI
Index utilization:
<details>
- 
</details>
<details>
- …
=> fix: [PL-42842]: fix case insensitive sorting on listing variable page

srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/CVServiceModule.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/core/services/impl/sidekickexecutors/VerificationTaskCleanupSideKickExecutor.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecord.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/CompositeSLORecordBucket.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLIRecord.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/entities/SLIRecordBucket.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/api/CompositeSLORecordBucketService.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/api/CompositeSLORecordService.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/api/SLIRecordBucketService.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordBucketServiceImpl.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImpl.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLIRecordBucketServiceImpl.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLOMetricAnalysisStateExecutor.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/cvng/statemachine/services/api/CompositeSLORestoreMetricAnalysisStateExecutor.java, srm-service/modules/cv-nextgen-service/service/src/main/java/io/harness/serializer/morphia/CVNextGenMorphiaRegister.java, srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordBucketServiceImplTest.java, srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/CompositeSLORecordServiceImplTest.java, srm-service/modules/cv-nextgen-service/service/src/test/java/io/harness/cvng/servicelevelobjective/services/impl/SLODashboardServiceImplTest.java
- In addition to writing to CompositeSLORecord , records are also written to CompositeSLORecordBucket in chunk size of 5 currently.
- CompositeSLORecordBucket reads from the SLIRecordBucket only and all windows and processing takes on multiples of SLI_RECORD_BUCKET_SIZE only.
<details>
- 
</details>
<details>
You can run multiple PR check …
=> [feat]: [SRM-14726]: write to CompositeSLORecordBucket in addition to write to CompositeSLORecord

pipeline-service/service/src/test/java/io/harness/pms/plan/creation/PipelineServiceInternalInfoProviderTest.java
<details>
- 
</details>
<details>
- …
=> feat: [SSCA-940]: fix PipelineServiceInternalInfoProviderTest in develop branch

360-cg-manager/src/main/java/software/wings/app/WingsApplication.java
Adds exception mapper for NGAccessDeniedException in manager. This is to fix error response structure for delegate list page.
Test:
- Before changes
- After changes
<details>
- 
</details>
<details>
- …
=> [fix]: [PL-39630]: Adds exception mapper for NGAccessDeniedException in manager

product/ci/scm/docker/Dockerfile, product/ci/scm/docker/Dockerfile-scm-multistage
<details>
- 
</details>
<details>
- …
=> fix: [CI-10298]:  scm grpc version upgrade to latest

template-service/service/src/main/java/io/harness/serializer/TemplateServiceModuleRegistrars.java
fix broken TemplateServiceComponentTest template service test in develop
<details>
- 
</details>
<details>
- …
=> feat: [CDS-84921]: fix broken TemplateServiceComponentTest template service test in develop

120-ng-manager/src/main/java/io/harness/ng/core/impl/ProjectServiceImpl.java, 950-ng-project-n-orgs/src/main/java/io/harness/repositories/core/custom/ProjectRepositoryCustom.java, 950-ng-project-n-orgs/src/main/java/io/harness/repositories/core/custom/ProjectRepositoryCustomImpl.java
Make sorting case insensitive for listing projects.
Tested for:
Tested list API for project
<details>
- 
</details>
<details>
- CodeFormat: `trigger …
=> feat: [PL-32066]: Make sorting case insentive for projects

400-rest/src/test/java/software/wings/service/impl/instance/ServerlessDashboardServiceImplTest.java, 900-git-sync-sdk/src/test/java/io/harness/gitsync/scm/SCMGitSyncHelperTest.java
Broke due to this change: https://github.com/harness/harness-core/pull/55631
<details>
- 
</details>
<details>
- …
=> fix: [CDS-85046]: fix develop tests {SCMGitSyncHelperTest, ServerlessDashboardServiceImplTest}

400-rest/src/main/java/software/wings/resources/AccountResource.java
Added support for service to service communication for GET- /account api by enabling @InternalApi so that we can call this api directly without going through gateway
<details>
- 
</details>
<details>
- …
=> fix: [PL-42587]: Add support for internal api in account resource

332-ci-manager/config/ci-manager-config.yml
Upgraded plugin version after the change as part of https://harness.atlassian.net/browse/CI-10347
The plugin build is https://harness.drone.io/drone-plugins/drone-meltwater-cache/197
<details>
- 
</details>
<details>
- Compile: …
=> fix:[CI-10347]: CI plugin version upgrade

idp-service/chart/templates/ingress.yaml, idp-service/contracts/openapi/v1/openapi.yaml, idp-service/src/main/java/io/harness/idp/migration/AddRuleIdentifierMigration.java, idp-service/src/main/java/io/harness/idp/migration/IdpBGMigrationDetails.java, idp-service/src/main/java/io/harness/idp/migration/MultipleInputValuesMigration.java, idp-service/src/main/java/io/harness/idp/scorecard/checks/mappers/CheckDetailsMapper.java, idp-service/src/main/java/io/harness/idp/scorecard/checks/service/CheckServiceImpl.java, idp-service/src/main/java/io/harness/idp/scorecard/datapoints/mappers/DataPointMapper.java, idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/scm/bitbucket/BitbucketIsBranchProtectionSetDsl.java, idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/scm/bitbucket/BitbucketMeanTimeToMergePRDsl.java, idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/scm/github/GithubIsBranchProtectionSetDsl.java, idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/scm/github/GithubMeanTimeToMergePRDsl.java, idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/scm/github/GithubOpenCodeScanningAlertsDsl.java, idp-service/src/main/java/io/harness/idp/scorecard/datasourcelocations/locations/scm/github/GithubOpenDependabotAlertsDsl.java, idp-service/src/main/resources/migrations/scorecard/checks.json, idp-service/src/main/resources/migrations/scorecard/dataPoints.json, idp-service/src/main/resources/migrations/scorecard/datasourceLocations.json, idp-service/src/test/java/io/harness/idp/scorecard/datasources/mappers/DataSourceDataPointsMapMapperTest.java, idp-service/src/test/java/io/harness/idp/scorecard/datasources/resources/DataSourceApiImplTest.java, idp-service/src/test/java/io/harness/idp/scorecard/datasources/service/DataSourceServiceImplTest.java, idp-service/src/test/java/io/harness/idp/scorecard/scores/service/CheckServiceImplTest.java, idp-service/src/test/java/io/harness/idp/scorecard/scores/service/ScoreComputerServiceImplTest.java
1. Add /v2/scores to ingress
2. Remove conditional_input_value, is_conditional and conditional_input_description from openapi and code.
3. Remove validateRules() and add code to generate rule identifiers even in case of update as check update could have new rules (without identifiers).
4. Add validation for required input values.
5. Remove \" from input values at various places as UI will add it for all input values going forward.
6. Add back the data points for fileContents and fileContains
<details>
- 
- `trigger …
=> feat: [IDP-1699]: Misc changes for multiple input values integration

400-rest/src/main/java/software/wings/resources/CEReportScheduleResource.java, 450-ce-views/src/main/java/io/harness/ccm/views/service/CEReportTemplateBuilderService.java, 450-ce-views/src/main/java/io/harness/ccm/views/service/impl/CEReportTemplateBuilderServiceImpl.java, batch-processing/service/src/main/java/io/harness/batch/processing/reports/ScheduledReportServiceImpl.java
- Removed the usage of big query service
- Updated cloudProvider table name based on whether clickhouse is used or not
<details>
- 
</details>
<details> …
=> [fix]: [CCM-15146]: Fix Scheduled reports in SMP

260-delegate/build.properties, 890-sm-delegate/src/main/java/io/harness/delegatetasks/UpsertSecretTaskValidationHandler.java, 890-sm-delegate/src/test/java/io/harness/delegatetasks/UpsertSecretTaskValidationHandlerTest.java
HF for https://github.com/harness/harness-core/pull/55484
Azure key vault heartbeat check creates a secret. This secret didn't have expiry datetime set.
Added missing expiry duration for 30 mins from the time of creation.
Validated that expiry is now set for every version of the secret.
<details>
- 
</details>
<details>
You can run multiple …
=> fix: [PL-42509]: Added expiry for secret created via heartbeat check of azure key vault

pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers/TriggerHelper.java
Add trigger xpressions that can be suggested while passing expression from ui
<details>
- 
</details>
<details>
- …
=> [feat]: [CDS-84856]: Add trigger xpressions that can be suggested while passing expression from ui

scripts/jenkins/check-file.sh
<details>
- 
</details>
<details>
- …
=> fix: [BT-5989]: Auto true Copilecode check

120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/util/ArtifactResourceUtils.java
<details>
- 
</details>
<details>
- …
=> [fix]: [CDS-83207]: Fix for develop

scripts/terraform/cloudfunctions/ce/ce-cf-resources.tf, scripts/terraform/cloudfunctions/ce/main.tf, scripts/terraform/cloudfunctions/ce/src/python/aws_ebs_data_main.py, scripts/terraform/cloudfunctions/ce/src/python/aws_ec2_data_main.py, scripts/terraform/cloudfunctions/ce/src/python/aws_rds_data_main.py, scripts/terraform/cloudfunctions/ce/src/python/azure_vm_inventory_data_main.py, scripts/terraform/cloudfunctions/ce/src/python/gcp_disk_inventory_data_main.py, scripts/terraform/cloudfunctions/ce/src/python/gcp_instance_inventory_data_main.py, scripts/terraform/cloudfunctions/ce/src/python/util.py, scripts/terraform/cloudfunctions/main.tf
<details>
- 
</details>
<details>
- …
=> feat: [CCM-13190]: Direct load jobs for inventory CFs to another project

pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExecutionExpressionUsageService.java, pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/ExecutionExpressionUsageServiceImpl.java, pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/beans/ExecutionExpressionUsagesEntity.java, pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/beans/ExpressionValueMetadata.java, pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/morphia/OrchestrationMorphiaRegistrar.java, pipeline-service/service/src/test/resources/mongo/indexes.txt
Changes - Adding one more collection to capture expressions during executions.
Usage -
a. Show all expressions per step evaluated in the step to what value, just like CG
b. Might be used to analyse if any breaking expression engine change was merged which broke customer expressions (exploratory)
Impact - No impact in this PR, as only impl is added for service layer and indexes
Testing - Mongo indexes test is passing
<details>
- 
-  Trigger multiple builds together: For eg: `trigger dms, …
=> [fix]: [CDS-85900]: Adding support to capture expressions during execution

136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/ScmFacilitatorServiceImpl.java, 440-connector-nextgen/src/main/java/io/harness/connector/utils/HarnessCodeConnectorUtils.java, 952-scm-java-client/src/main/java/io/harness/impl/scm/ScmGitProviderMapper.java, 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/harness/HarnessConnectorDTO.java
For get user repos we need to know org account project of harness connector to get repo from apis hence passing it down. 
<details>
- 
</details>
<details> …
=> feat: [CODE-1151]: repo list changes for harness code

pipeline-service/contracts/openapi/v1/openapi.yaml, pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceService.java, pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/ApprovalInstanceServiceImpl.java, pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/entities/HarnessApprovalInstance.java, pipeline-service/modules/orchestration-steps/src/test/java/io/harness/steps/approval/step/ApprovalInstanceServiceTest.java, pipeline-service/service/src/main/java/io/harness/pms/approval/ApprovalResourceService.java, pipeline-service/service/src/main/java/io/harness/pms/approval/ApprovalResourceServiceImpl.java, pipeline-service/service/src/main/java/io/harness/pms/approval/api/ApprovalsApiImpl.java, pipeline-service/service/src/test/java/io/harness/pms/approval/ApprovalResourceImplServiceImplTest.java, pipeline-service/service/src/test/java/io/harness/pms/approval/api/ApprovalsApiImplTest.java
Added callback Id in the harness approval step params, this is another id which can be used by the customer to identify an approval instance and approve it.
Have modified the API for approving by execution id to have callback id as a parameter.
Tested locally the changes:
1. Passing callback id to the API and approving/rejecting an execution.
2. Passing no callback id to the API and approving/rejecting an execution.
<details>
- 
-  Trigger multiple builds together: For eg: `trigger dms, …
=> feat: [CDS-85968]: add callback id handling for approval step and api

125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtils.java, 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/DeploymentStagePMSPlanCreatorV2.java, 125-cd-nextgen/src/main/java/io/harness/cdng/creator/plan/stage/v1/DeploymentStagePlanCreator.java, 125-cd-nextgen/src/test/java/io/harness/cdng/creator/plan/service/ServiceAllInOnePlanCreatorUtilsTest.java, 125-cd-nextgen/src/test/resources/cdng/creator/servicePlanCreator/pipeline.yaml
If infrastructure definitions field is provided during environment propagation from stage, then the plan creator should use that infrastructure value instead of the value of infrastructure from the propagated environment. 
<details>
- 
</details>
<details>
You can run multiple PR check triggers by comma separating them in a single comment. …
=> [feat]: [CDS-83149]: Allow infrastructure definition override during plan creation

400-rest/src/main/java/software/wings/helpers/ext/account/DeleteAccountHelper.java
We need to increment deletion Algo number to re trigger deletions for deleted entities.
<details>
- 
</details>
<details>
- CodeFormat: `trigger …
=> feat: [PL-43549]: increment build number for deletion algo (#56719)

260-delegate/build.properties
<details>
- 
</details>
<details>
- …
=> [fix]: [CI-8872]: upgrade scm version

260-delegate/build.properties
<details>
- 
</details>
<details>
- …
=> [fix]: [CI-8872]: upgrade scm version 

980-commons/src/main/java/io/harness/utils/UuidAndIdentifierUtils.java, 980-commons/src/test/java/io/harness/data/validator/UuidValidatorTest.java, build.properties
<details>
- 
</details>
<details>
- …
=> [fix]: [PL-43576]: Convert dot,spaces and dashes to underscore

332-ci-manager/chart/Chart.yaml, 332-ci-manager/chart/values.yaml
<details>
- 
</details>
<details>
- …
=> fix: [SMP-2360]: update image tags for smp 0.12.0 ci manager

136-git-sync-manager/src/main/java/io/harness/gitsync/common/dtos/CreatePRRequest.java, 136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitRepoHelper.java, 878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareContextHelper.java, 878-ng-common-utilities/src/main/java/io/harness/gitaware/helper/GitAwareEntityHelper.java, 878-ng-common-utilities/src/main/java/io/harness/gitx/GitXSettingsHelper.java, 878-ng-common-utilities/src/test/java/io/harness/gitaware/helper/GitAwareEntityHelperTest.java, 900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitEntityCreateInfoDTO.java, 900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitEntityUpdateInfoDTO.java, 900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor/GitSyncThreadDecorator.java, 953-git-sync-commons/src/main/java/io/harness/gitsync/interceptor/GitSyncConstants.java, 954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/harness/HarnessConnectorDTO.java, 960-api-services/src/main/java/io/harness/git/GitClientHelper.java, 970-ng-commons/src/main/java/io/harness/gitsync/interceptor/GitEntityInfo.java, 970-ng-commons/src/main/java/io/harness/gitsync/sdk/EntityGitDetails.java, 970-ng-commons/src/main/java/io/harness/gitsync/sdk/GitSyncApiConstants.java, pipeline-service/service/src/main/java/io/harness/pms/filter/creation/FilterCreatorMergeService.java
1. Remove any null check on connector ref(Since connector ref can be empty/null)
2. Added file path for the harness code
3. Added a new param isHarnessCodeRepo in the GitInfoDetails dto which is the DTO for accepting GitX param in the API to differentiate between the create entity request between remote entity third party connector or harness connector. GitSettingHelper uses this param to set the connectorRef to empty if this param is set. If the param is not set the flow remains the same.
<details>
- 
- `trigger …
=> fix: [CODE-1186]: changes for the gitx

332-ci-manager/config/ci-manager-config.yml
<details>
- 
</details>
<details>
- …
=> feat: [SSCA-1035]: provide entrypoints in ci manager config

100-migrator/src/main/java/io/harness/ngmigration/service/importer/TriggerImportService.java, 100-migrator/src/main/java/io/harness/ngmigration/service/manifestspec/HttpHelmManifestSpec.java, 100-migrator/src/main/java/io/harness/ngmigration/service/manifestspec/ManifestSpecFactory.java, 100-migrator/src/main/java/io/harness/ngmigration/service/manifestspec/ManifestSpecMapper.java
<details>
- 
</details>
<details>
- …
=> feat: [CDS-87101]: support for migrating helm triggers

ssca-manager/service/src/main/java/io/harness/repositories/remediation_tracker/RemediationTrackerRepository.java, ssca-manager/service/src/main/java/io/harness/repositories/remediation_tracker/RemediationTrackerRepositoryCustom.java, ssca-manager/service/src/main/java/io/harness/repositories/remediation_tracker/RemediationTrackerRepositoryCustomImpl.java, ssca-manager/service/src/main/java/io/harness/ssca/api/RemediationTrackerApiImpl.java, ssca-manager/service/src/main/java/io/harness/ssca/api/RemediationTrackerApiUtils.java, ssca-manager/service/src/main/java/io/harness/ssca/entities/remediation_tracker/CVEVulnerability.java, ssca-manager/service/src/main/java/io/harness/ssca/entities/remediation_tracker/ContactInfo.java, ssca-manager/service/src/main/java/io/harness/ssca/entities/remediation_tracker/DefaultVulnerability.java, ssca-manager/service/src/main/java/io/harness/ssca/entities/remediation_tracker/RemediationTrackerEntity.java, ssca-manager/service/src/main/java/io/harness/ssca/entities/remediation_tracker/VulnerabilityInfo.java, ssca-manager/service/src/main/java/io/harness/ssca/mapper/RemediationTrackerMapper.java, ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerService.java, ssca-manager/service/src/main/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImpl.java, ssca-manager/service/src/test/java/io/harness/BuilderFactory.java, ssca-manager/service/src/test/java/io/harness/ssca/services/remediation_tracker/RemediationTrackerServiceImplTest.java
<details>
- 
</details>
<details>
- …
=> feat: [SSCA-1062]: Add implementation for Listing API of remediation

332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/CodebaseUtils.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/IntegrationStageUtils.java, 332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer/vm/VmPluginCompatibleStepSerializer.java, 332-ci-manager/service/src/test/java/io/harness/ci/execution/stateutils/buildstate/CodebaseUtilsTest.java, 332-ci-manager/service/src/test/java/io/harness/ci/execution/stateutils/buildstate/PluginSettingUtilsTest.java, 879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/GitCloneStepInfo.java, 879-pipeline-ci-commons/src/main/java/io/harness/utils/CiCodebaseUtils.java, 879-pipeline-ci-commons/src/test/java/io/harness/utils/CiCodebaseUtilsTest.java, pipeline-service/service/src/main/resources/static-schema/v0/pipeline.json, pipeline-service/service/src/main/resources/static-schema/v1/pipeline.json, template-service/service/src/main/resources/static-schema/v0/template.json, template-service/service/src/main/resources/static-schema/v1/template.json
<details>
- 
</details>
<details>
- …
=> feat: [CI-10747]: harness code git clone step

970-ng-commons/src/main/java/io/harness/validator/NGRegexValidatorConstants.java, pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/HarnessApprovalStepInfo.java
Added schema validations for callback id to support:
1. Empty string/null
2. alphanumeric characters including _- and excluding spaces
3. expressions(single and multiple), runtime inputs with default value/execution input
4. expressions mixed with 2.
Tested the above cases in local
Sample values tested: 
1. <+pipeline.name>_<+pipeline.name>-testing123
2. testing123
3. <+pipeline.name>
4. <+input>
5. <+input>.executionInput()
Schema PR: https://github.com/harness/harness-schema/pull/275
<details>
- 
- `trigger …
=> feat: [CDS-87088]: add schema validations for callback id

100-migrator/src/main/java/io/harness/ngmigration/NGMigrationApplication.java
<details>
- 
</details>
<details>
- …
=> [feat]: [PL-43742]: Added TaskResponseEventModule to migrator service

930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sCanaryBaseHandler.java, 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sCanaryBaseHandlerTest.java
Fixing develop
<details>
- 
</details>
<details>
- MessageMetadata: `trigger …
=> feat: [CDS-82480] fix TrafficRoutingInfoDTO Path

332-ci-manager/service/src/main/java/io/harness/ci/execution/states/ssca/SscaEnforcementStep.java, 332-ci-manager/service/src/test/java/io/harness/ci/execution/states/ssca/SscaEnforcementStepTest.java, 332-ssca/commons/src/main/java/io/harness/ssca/client/beans/enforcement/SscaEnforcementSummary.java, 879-pipeline-ci-commons/src/main/java/io/harness/ssca/execution/orchestration/outcome/PublishedSbomArtifact.java, 950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/stepstatus/artifact/SscaArtifactMetadata.java, pipeline-service/modules/orchestration-steps/src/main/java/io/harness/ssca/execution/CdSscaEnforcementStep.java, ssca-manager/service/BUILD.bazel, ssca-manager/service/src/main/java/io/harness/repositories/exemption/ExemptionRepositoryCustom.java, ssca-manager/service/src/main/java/io/harness/repositories/exemption/ExemptionRepositoryCustomImpl.java, ssca-manager/service/src/main/java/io/harness/ssca/api/ExemptionsApiImpl.java, ssca-manager/service/src/main/java/io/harness/ssca/services/EnforcementStepServiceImpl.java, ssca-manager/service/src/main/java/io/harness/ssca/services/RuleEngineServiceImpl.java, ssca-manager/service/src/main/java/io/harness/ssca/services/exemption/ExemptionHelper.java, ssca-manager/service/src/main/java/io/harness/ssca/services/exemption/ExemptionServiceImpl.java, ssca-manager/service/src/main/java/io/harness/ssca/services/user/UserService.java, ssca-manager/service/src/main/java/io/harness/ssca/services/user/UserServiceImpl.java, ssca-manager/service/src/main/java/io/harness/ssca/utils/VersionUtils.java, ssca-manager/service/src/test/java/io/harness/SSCAManagerTestRule.java, ssca-manager/service/src/test/java/io/harness/ssca/services/EnforcementStepServiceImplTest.java, ssca-manager/service/src/test/java/io/harness/ssca/services/exemption/ExemptionHelperTest.java, ssca-manager/service/src/test/java/io/harness/ssca/services/exemption/ExemptionServiceImplTest.java, ssca-manager/service/src/test/java/io/harness/ssca/utils/VersionUtilsTest.java
1. Adding version comparator to check exemption version and component version
2. Adding exemptedComponentCount in pipeline dtos.
3. Adding UTs
4. Adding logs for better application insights.
<details>
- 
</details>
<details>
- Compile: …
=> feat: [SSCA-1145]: Adding version check for using exemptions in enforcement and adding relevant UTs.

dockerization/base-images/go/1/1.21/Dockerfile
Upgrading GO for UBI-GO base image to 1.21.5
Changes have been tested by CI team and Gitops teams
<details>
- 
</details>
<details>
- CodeFormat: …
=> [fix]: [PL-43592]: Upgrading Go to 1.21.5

dockerization/base-images/python/3/3.11/Dockerfile, dockerization/base-images/python/3/3.8/Dockerfile, dockerization/base-images/python/3/3.9/Dockerfile
Upgrading node to 20 from 18.
Testing
CE and CV team gave the sign off with test image.
<details>
- 
</details>
<details>
- CodeFormat: `trigger …
=> fix:[PL-43149] upgrade node in base image

WORKSPACE, product/ci/scm/go.mod, product/ci/scm/go.sum
Scm autogen change
<details>
- 
</details>
<details>
- MessageMetadata: `trigger …
=> feat: [CI-11011]: Scm autogen change
