harness/harness-core

270-delegate-service-app/container/scripts/replace_configs.sh, 270-delegate-service-app/delegate-service-config.yml, 360-cg-manager/config.yml, 360-cg-manager/container/scripts/replace_configs.sh, 400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, 400-rest/src/main/resources/delegatetemplates/delegate.sh.ftl, 400-rest/src/test/java/software/wings/service/delegate/DelegateServiceTest.java, 400-rest/src/test/java/software/wings/service/delegate/DelegateTaskServiceClassicTest.java, 400-rest/src/test/resources/expectedDelegateOpenJdk.sh, 400-rest/src/test/resources/expectedDelegateWithoutDelegateName.sh, 960-api-services/src/main/java/io/harness/delegate/configuration/InstallUtils.java, dockerization/delegate-service-app/scripts/replace_configs.sh, dockerization/manager/scripts/replace_configs.sh
=> fix: [CDP-20260]: Remove KUBECTL_VERSION dependency in tools install

260-delegate/src/test/java/software/wings/delegatetasks/TerraformProvisionTaskTest.java, 400-rest/src/main/java/software/wings/delegatetasks/TerraformProvisionTask.java, 960-api-services/src/main/java/io/harness/terraform/TerraformClient.java, 960-api-services/src/main/java/io/harness/terraform/TerraformClientImpl.java, 960-api-services/src/main/java/io/harness/terraform/TerraformHelperUtils.java, 960-api-services/src/test/java/io/harness/terraform/TerraformClientImplTest.java, 960-api-services/src/test/java/io/harness/terraform/TerraformHelperUtilsTest.java, 970-api-services-beans/src/main/java/io/harness/terraform/beans/TerraformVersion.java, 970-api-services-beans/src/test/java/io/harness/terraform/beans/TerraformVersionTest.java
=> feat: [CDP-17623]: Support terraform destroy -auto-approve in newer versions

800-pipeline-service/src/main/java/io/harness/pms/events/PipelineDeleteEvent.java, 800-pipeline-service/src/main/java/io/harness/pms/outbox/PipelineOutboxEventHandler.java, 800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineSetupUsageHelper.java, 800-pipeline-service/src/main/java/io/harness/repositories/pipeline/PMSPipelineRepositoryCustomImpl.java
=> fix: [PIE-2531]: Delete setup usage if no setup usage are there

300-cv-nextgen/src/main/java/io/harness/cvng/servicelevelobjective/services/impl/SLOErrorBudgetResetServiceImpl.java
=> fix: [CVS-9049]: Error budget reset to reset HealthIndicator.

136-git-sync-manager/src/main/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcService.java, 136-git-sync-manager/src/test/java/io/harness/gitsync/sdk/HarnessToGitPushInfoGrpcServiceTest.java
=> fix: [PL-22447]: set the securityPrincipal

300-cv-nextgen/src/main/java/io/harness/cvng/core/resources/MonitoredServiceResource.java, 300-cv-nextgen/src/test/java/io/harness/cvng/core/resources/MonitoredServiceResourceTest.java
…ty service
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> [fix]: [CVS-7927]: Pre-Validation when monitored service is created with empty params

300-cv-nextgen/src/main/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImpl.java, 300-cv-nextgen/src/test/java/io/harness/cvng/core/services/impl/monitoredService/MonitoredServiceServiceImplTest.java
=> [fix]: [CVS-9071]: returning empty list in case of no monitored service

953-events-api/src/main/java/io/harness/eventsframework/impl/redis/RedisAbstractConsumer.java, 953-events-api/src/main/java/io/harness/eventsframework/impl/redis/RedisProducer.java, 953-events-api/src/main/resources/metrics/metricDefinitions/redis_event_metrics.yaml, scripts/jenkins/authorsList.txt
=> [feat]: [PL-21845]: Add event monitoring on event framework consumers

280-batch-processing/src/main/java/io/harness/batch/processing/schedule/EventJobScheduler.java, 280-batch-processing/src/main/java/io/harness/batch/processing/service/impl/InstanceDataBulkWriteServiceImpl.java, 280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/support/K8SWorkloadService.java, 280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/util/CacheUtils.java
Please note that the `InstanceDataKeys.activeInstanceIterator` value is updated as `instanceSyncTime + 50yrs` and not `usageStartTime+50yrs`
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/30620)
=> fix: [CCM-5504]: activeInstanceIterator update with StartEvent

320-ci-execution/src/main/java/io/harness/ci/integrationstage/IntegrationStageUtils.java, 320-ci-execution/src/test/java/io/harness/ci/integrationstage/IntegrationStageUtilsTest.java, scripts/jenkins/author-check.sh, scripts/jenkins/authorsList.txt
=> fix: [CI-3464]: Handling .git in the end of ssh url

280-batch-processing/src/main/java/io/harness/batch/processing/schedule/BatchJobRunner.java
=> [fix]: [CCM-5539]: Delaying hourly job by 3 hrs

400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, 400-rest/src/main/resources/delegatetemplates/start.sh.ftl
=> fix: [DEL-3426]: Disable audit check for ng on delegate update

400-rest/src/main/java/software/wings/service/impl/UserServiceImpl.java, build.properties
=> fix: [PL-23500]: added user group ldap sync with UserId

260-delegate/container/scripts/delegate.sh, 400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, 400-rest/src/main/resources/delegatetemplates/harness-delegate.yaml.ftl, 400-rest/src/test/resources/expectedDelegateOpenJdk.sh, 400-rest/src/test/resources/expectedDelegateWithoutDelegateName.sh, 400-rest/src/test/resources/expectedHarnessDelegate.yaml, 400-rest/src/test/resources/expectedHarnessDelegateImmutable.yaml, 400-rest/src/test/resources/expectedHarnessDelegateWithCiEnabled.yaml, README.md, dockerization/delegate/immutable-scripts/start.sh, dockerization/delegate/scripts/delegate.sh, on-prem/kubernetes_installer/delegate.yaml
=> feat: [DEL-3365]: Reduce CG delegate xmx to 1.5Gi and pod memory to 4Gi

400-rest/src/main/java/software/wings/graphql/datafetcher/outcome/OutcomeConnectionDataFetcher.java, 400-rest/src/main/java/software/wings/service/impl/SettingsServiceImpl.java
=> fix: [CDS-34753]: setting attribute should return right total

400-rest/src/main/resources/graphql/public/delegateMutatation.graphql
=> fix: [DEL-3479]: Deprecate scope uuid in graphql api

400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java
=> fix: [DEL-3500]: Wrong log printed for non shell delegates

280-batch-processing/src/main/java/io/harness/batch/processing/billing/writer/support/BillingDataGenerationValidator.java, 280-batch-processing/src/test/java/io/harness/batch/processing/billing/writer/support/BillingDataGenerationValidatorTest.java
=> [fix]: [CCM-7064]: Add 2 days buffer time between job run time and event received 

320-ci-execution/src/main/java/io/harness/ci/plan/creator/filter/CIStageFilterJsonCreator.java, 930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/helper/ConnectorEnvVariablesHelper.java, 930-delegate-tasks/src/test/java/io/harness/delegate/task/citasks/cik8handler/helper/ConnectorEnvVariablesHelperTest.java
=> fix: [CI-3895]: allow secret in user name env variables

product/ci/scm/file/file.go, product/ci/scm/file/file_test.go
=> feat: [PL-24264]: Fetch commit id for file operations in azure

260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, 960-api-services/src/main/java/io/harness/delegate/configuration/DelegateConfiguration.java
Changes to print delegateConfiguration (without secrets) in delegate logs.
This will be helpful in debugging issues in customer environment, where we don't have access to config-delegate.yml …
=> fix: [DEL-3789]: Print delegate configuration in delegate logs

400-rest/src/main/java/io/harness/perpetualtask/internal/PerpetualTaskRecordHandler.java
When Perpetual task is failed to be assigned and raise an exception, it caught by WingsException handling and log in the stack driver. However, we already have a catch clause to handle those failed assigned exception and print the call stack which has clearer log messaging and easier for troubleshooting. 
The above screenshot shows the exception message that needs to be remove and use a better logging message for the issue, it would be printing the log message.
catch (Exception e) {
log.error("Failed to assign any Delegate to perpetual task {} ", taskId, e);
}
which already exist.
- BuildNumberMetadata: `trigger …
=> feat: [DEL-3782]: Improve the exception handling and consolidate the exception to be meaningful

400-rest/src/main/java/software/wings/beans/artifact/ArtifactStreamAttributes.java
=> fix: [CDS-25357]: Ensure metadata is of instance HashMap

260-delegate/src/main/java/io/harness/delegate/service/DelegateAgentServiceImpl.java, 960-watcher/src/main/java/io/harness/watcher/service/WatcherServiceImpl.java, 980-commons/src/main/java/io/harness/utils/ProcessControl.java
This change-set contains following improvements:
1) Send primaryVersion while starting Delegate process (in case of on-prem)
2) Verbose logging if we get exception in watchDelegate()
3) Look for existence of delegate process before attempting to kill it. …
=> fix: [DEL-3719]: Improvements in watcher while watching delegate process

400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java, 400-rest/src/test/java/software/wings/delegatetasks/GitCommandTaskTest.java, 400-rest/src/test/java/software/wings/service/impl/yaml/YamlGitServiceImplTest.java, 930-delegate-tasks/src/main/java/software/wings/delegatetasks/GitCommandTask.java, 990-commons-test/src/main/java/io/harness/rule/OwnerRule.java
=> fix: [PL-18485]: Raise alert when a more general issue happens during git integration

400-rest/src/main/java/software/wings/resources/ExecutionResource.java
=> fix: [CDS-36340]: Resetting workflow triggeredBy when pipelines are resumed

126-instance/src/main/java/io/harness/service/stats/statscollector/InstanceStatsIteratorHandler.java
Update pool size and interval for InstanceStatsIteratorHandler
---
This change is [<img …
=> [feat]: [PL-24756]: Update pool size and interval for InstanceStatsIteratorHandler

400-rest/src/main/java/software/wings/service/impl/AccountServiceImpl.java
=> fix: [DEL-3918]: Remove extraneous logging while fetching delegate configuration

860-orchestration-steps/src/main/java/io/harness/plancreator/pipeline/PipelineInfoConfig.java, 860-orchestration-steps/src/test/resources/schema/Pipelines/all.json
=> fix: [CDS-36785]: Revert OneOf in PipelineInfoConfig

280-batch-processing/src/main/java/io/harness/batch/processing/service/impl/WorkloadRepositoryImpl.java, 280-batch-processing/src/main/java/io/harness/batch/processing/service/intfc/WorkloadRepository.java, 280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTasklet.java, 280-batch-processing/src/main/java/io/harness/batch/processing/tasklet/support/K8SWorkloadService.java, 280-batch-processing/src/test/java/io/harness/batch/processing/tasklet/ClusterDataToBigQueryTaskletTest.java, build.properties
=> [fix]: [CCM-7534]: k8sWorkload query change use workload uid

970-ng-commons/src/main/java/io/harness/ng/core/utils/NGYamlUtils.java, 970-ng-commons/src/main/java/io/serializer/HObjectMapper.java, platform-service/Readme.MD, platform-service/build/container/BUILD.bazel, platform-service/config/BUILD.bazel, platform-service/service/BUILD.bazel
=> techdebt: [PL-0]: Fix NGYamlUtils to not re-configure common ObjectMapper

136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper/GitSyncConnectorHelper.java, 136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl/YamlGitConfigServiceImpl.java, 136-git-sync-manager/src/main/java/io/harness/gitsync/common/service/YamlGitConfigService.java, 136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/GitSyncConnectorHelperTest.java
=> [fix]: [CI-3959]: handle webhook registration

400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java
=> [fix]: [CCM-7324]: Removed default CE permissions from user group creation

878-ng-common-utilities/src/main/java/io/harness/plancreator/steps/common/WithDelegateSelector.java, build.properties
=> [CDS-37311]: Revert jsonignore for selector field

400-rest/src/main/java/software/wings/service/impl/trigger/TriggerServiceImpl.java, 400-rest/src/test/java/software/wings/service/impl/trigger/TriggerServiceTest.java
=> fix: [CDS-37510]: do workflow variable allowed values check only when variable value is provided

860-orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStep.java, 860-orchestration-steps/src/main/java/io/harness/steps/policy/step/PolicyStepHelper.java, 860-orchestration-steps/src/test/java/io/harness/steps/policy/step/PolicyStepHelperTest.java, 860-orchestration-steps/src/test/java/io/harness/steps/policy/step/PolicyStepTest.java, 870-orchestration/src/main/java/io/harness/engine/GovernanceServiceImpl.java, 950-opa-client/src/main/java/io/harness/opaclient/OpaServiceClient.java
All requests to Policy Manager have an 'entityMetadata' query param, which is supposed to have a key value pair with key 'entityName'. The value of entityName will be displayed in the Policy Evaluations tab. In this PR, the pipeline name is sent to the Policy Manager for pipeline save/runs as entityName, and the policy step name is sent for policy steps. This behaviour has been discussed with the OPA team.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/33320)
=> [feat]: [OPA-172]: Send correct entity metadata to Policy Manager

800-pipeline-service/src/main/java/io/harness/pms/pipeline/PipelineEntity.java, 800-pipeline-service/src/main/java/io/harness/pms/plan/execution/ExecutionHelper.java, 800-pipeline-service/src/main/java/io/harness/pms/plan/execution/PlanExecutionResource.java, 800-pipeline-service/src/test/java/io/harness/pms/plan/execution/PlanExecutionResourceTest.java
Pipeline YAML has a flag `allowStageExecutions` whose value is also stored in the DB. However, we need to remove the usage of the DB flag now, because the with git simplification, the YAML on Git can easily be outdated wrt the DB entry. Hence, we need to use the value of the flag in the YAML and not in the DB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/harness/harness-core/33499)
=> [feat]: [PIE-3817]: Generate stages execution list using flag value in pipeline yaml

280-batch-processing/src/main/java/io/harness/batch/processing/service/impl/WorkloadRepositoryImpl.java, 340-ce-nextgen/src/test/resources/mongo/indexes.txt, 490-ce-commons/src/main/java/io/harness/ccm/commons/entities/k8s/K8sWorkload.java
=> [Feat]: [CCM-7533]: TTL index in k8s workload collection

platform-service/modules/notification-service/BUILD.bazel, platform-service/modules/notification-service/src/main/java/io/harness/notification/evaluator/SecretExpressionEvaluator.java, platform-service/modules/notification-service/src/main/java/io/harness/notification/functor/SecretFunctor.java, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MSTeamsServiceImpl.java, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/PagerDutyServiceImpl.java, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/SlackServiceImpl.java, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/api/NotificationSettingsService.java, platform-service/modules/notification-service/src/test/java/io/harness/notification/service/NotificationSettingsServiceImplTest.java
Backend code changes to support secrets for userGroups
<details>
</details>
<details>
- TI-bootstrap3: `trigger …
=> feat: [Pl-25475]: Support of secrets for UserGroup notifications

platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java, platform-service/modules/notification-service/src/test/java/io/harness/notification/service/NotificationSettingsServiceImplTest.java
Fix regex pattern for secret expressions
<details>
</details>
<details>
- …
=> fix: [PL-25475]: Fix regex pattern for secret expression

400-rest/src/main/java/software/wings/service/impl/yaml/service/YamlServiceImpl.java
Made changes to upsert-entity api
<details>
</details>
<details>
- …
=> fix: [PL-23938]: return 400 in case of upsert entity failure

platform-service/build.properties, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MSTeamsServiceImpl.java, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/MailServiceImpl.java, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/NotificationSettingsServiceImpl.java, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/PagerDutyServiceImpl.java, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/SlackServiceImpl.java, platform-service/modules/notification-service/src/main/java/io/harness/notification/service/api/NotificationSettingsService.java, platform-service/modules/notification-service/src/test/java/io/harness/notification/service/MSTeamsServiceImplTest.java, platform-service/modules/notification-service/src/test/java/io/harness/notification/service/NotificationSettingsServiceImplTest.java, platform-service/modules/notification-service/src/test/java/io/harness/notification/service/PagerDutyServiceImplTest.java, platform-service/modules/notification-service/src/test/java/io/harness/notification/service/SlackServiceImplTest.java
Code changes to remove the setting sendNotificationViaDelegate
<details>
</details>
<details> …
=> [fix]:[PL-26131]: Remove variable sendNotificationViaDelegate option for notification channels

260-delegate/src/main/java/io/harness/perpetualtask/k8s/watch/NodeWatcher.java, 260-delegate/src/main/java/io/harness/perpetualtask/k8s/watch/PVWatcher.java, 260-delegate/src/main/java/io/harness/perpetualtask/k8s/watch/PodWatcher.java, 930-delegate-tasks/src/main/java/io/harness/perpetualtask/k8s/utils/K8sWatcherHelper.java
- Increased watcher creation retry count
- Reset watcher id count while deleting it
- Added nonNull conditions on `timeoutSeconds` to verify if API is failing or not.
<details>
</details>
<details>
- …
=> [fix]: [CCM-8233]: Increased watcher creation retry count and Reset watcher count while deleting it

999-annotations/BUILD.bazel, 999-annotations/src/main/java/io/harness/agent/sdk/BUILD.bazel, 999-annotations/src/main/java/io/harness/annotations/dev/BUILD.bazel, tools/bazel/macros.bzl
Breaking 999-annotations module to have granular build targets. These files were created using the automated BuildCleaner tool.
<details>
</details>
<details>
- …
=> feat: [PL-27456]: Granular targets for 999-annotations

400-rest/src/main/java/io/harness/stream/DelegateStreamHandler.java, 400-rest/src/main/java/software/wings/resources/DelegateAgentResource.java, 400-rest/src/main/java/software/wings/service/impl/DelegateServiceImpl.java, 400-rest/src/main/java/software/wings/service/intfc/DelegateService.java, 400-rest/src/test/java/software/wings/resources/DelegateAgentResourceTest.java, 400-rest/src/test/java/software/wings/service/delegate/DelegateServiceTest.java, 920-delegate-service-beans/src/main/java/io/harness/delegate/beans/Delegate.java, 980-commons/src/main/java/io/harness/agent/AgentGatewayUtils.java
Adding an `mlts` field to the delegate class which indicates whether a delegate is connected via mTLS.
The flag is set during delegate registration.
This change helps us to display the mTLS status of delegates in the UI, and thus customers to track their mTLS delegates during onboarding to mTLS.
- UTs
- Local testing: Started both a new delegate with mTLS and without mTLS, an existing one that keeps the same connection type (mTLS and non-mTLS), and an existing one that changes from/to mTLS. Ensured that delegates collection entry got created / updated as expected.
<details>
</details>
<details>
You can run multiple PR check …
=> feat: [DEL-4649]: Add 'mtls' flag to delegate during registration to mark mTLS delegates

pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/RetryHelper.java, pipeline-service/modules/orchestration/src/test/java/io/harness/engine/interrupts/helpers/RetryHelperTest.java
Fixing execution input value coming null on step retries when retry is done through failure strategy.
Reason: On retry we create a new nodeExecution, so the execution input instance was not present for the new nodeExecutionId.
Fix: While cloning the nodeExecution for retry, we are now cloning the execution input instance as well.
<details>
</details>
<details>
- BuildNumberMetadata: `trigger …
=> [fix]: [PIE-4874]: Fixing execution input value coming null on retry steps when retyr is done by failure strategy

260-delegate/src/main/java/io/harness/perpetualtask/k8s/watch/PodWatcher.java, 260-delegate/src/test/java/io/harness/perpetualtask/k8s/watch/PodWatcherTest.java, 990-commons-test/src/main/java/io/harness/rule/OwnerRule.java
Adding a check for Pod status as Running before sending PodInfo event.
Details:
We found that Pod cost is calculated more than Node cost. 
We are getting pod start and stop time in events (PodInfo and PodEvent respectively), when we send pod start event we check for pod schedule condition but we don’t check for Pod Lifecycle phase. Current Pod might node be in Running State.
But these pods are not coming in sync through SyncEvent because we are just checking for `status.phase==Running`.
From pod start and sync events it looks like the pods are not in running state but we are considering it for billing. 
<details>
</details>
<details>
<summary>PR Check …
=> [fix]: [CCM-8983]: Check for Pod status as Running before sending PodInfo Event

136-git-sync-manager/src/test/java/io/harness/gitsync/common/helper/GitFilePathHelperTest.java
<details>
</details>
<details> …
=> feat: [PL-28849]: added UT for fetch url operation for account level bitbucket onprem connector

400-rest/src/main/java/io/harness/delegate/service/DelegateVersionService.java, 400-rest/src/test/java/io/harness/delegate/service/DelegateVersionServiceTest.java, 890-sm-core/src/main/java/software/wings/app/PortalConfig.java, build.properties
Variable:
1- IMMUTABLE_DELEGATE_DOCKER_IMAGE
2- UPGRADER_DOCKER_IMAGE
will be added to configMap for manager running on on-prem.
corresponding helm-chart pr: https://github.com/harness/helm-harness-manager/pull/30
This change and helm-chart changes needs to go in same release if BE goes first then on-prem will break for accounts with immutable enabled.
Testing:
1- Immutable image was used for delegates in new account. Helm delegate used immutable image as specified in configMap, upgrader pointed to latest tag. 
Installed delegate and checked on smp.
<details>
</details>
<details>
You can run multiple PR check triggers by comma …
=> fix: [DEL-5374]: immutable delegate for on prem 

400-rest/src/main/java/software/wings/sm/states/collaboration/JiraCreateUpdate.java, 400-rest/src/test/resources/mock_create_meta
For Jira connectors using new meta endpoint, and execution containing multi-select fields, allowedValues.value was containing an empty string, breaking the original implementation logic.
Now we check both for null equality and also empty string.
- …
=> [fix]: [CDS-49108]: fixing condition where value string was empty

260-delegate/build.properties, 390-db-migration/src/main/java/io/harness/migrations/all/InitTerraformProvisionersSourceType.java, 400-rest/src/main/java/software/wings/sm/states/provision/TerraformProvisionState.java
With Terraform S3 Support for CG we introduced a class containing S3FileConfig, which had a field s3URIList, which was getting passed to the delegateTaskPackage as BasicDBList, which was deprecated from DelegateKryo due to security issue,
This is now fixed as we're resolving it to Java ArrayList and passed to delegate
<details>
</details>
<details> …
=> fix: [CDS-2970]: PRE-QA Fix for Double migration run and casting of s3URIList to deprecated BasicDBList

932-connector-task/src/main/java/io/harness/connector/service/git/NGGitServiceImpl.java, 960-api-services/src/main/java/io/harness/git/GitClientV2Impl.java, build.properties
Somehow removed the logic for identifier for normal fetch.
<details>
</details>
<details>
- …
=> fix: [CDS-55062]: NG commit changes when SCM FF is off

123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/UserResource.java, 123-ng-core-user/src/test/java/io/harness/ng/core/user/remote/UserResourceTest.java, 400-rest/src/main/java/software/wings/resources/UserResource.java, 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
We will now support deletion of externallyManaged user from the UI with a warning. Hence, to support this, we are removing the externallyManaged check from the backend API for user deletion.
Testing (the below scenarios are tried with the FF- "PL_USER_DELETION_V2" enabled):-
1. Tested deleting a SCIM managed user in NG, who is not SCIM managed in CG -> User deletion successful from NG.
2. Tested deleting a SCIM managed user in NG, who is also SCIM managed in CG -> User deletion successful from NG.
3. Tested deleting a SCIM managed user in CG, who is also present in NG -> User is not deleted. However, they get removed from all the userGroups in CG (which is the current behaviour).
4. Tested deleting a SCIM managed user in CG, who is not present in NG -> User deletion successful from CG. …
=> feat: [PL-38974]: Allow deletion of SCIM users

125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/ssh/SshCommandStepHelper.java, 125-cd-nextgen/src/test/java/io/harness/cdng/ssh/SshCommandStepHelperTest.java
added support for for pipeline variables (e.g. $var) for ssh.
Note that variables with same name under different variable levels will be overriden like: Stage var will be overriden by Pipeline, Pipeline - by Service, Service - by Environment.
<details>
- 
</details>
<details>
You can run multiple PR check triggers by comma separating them in …
=> fix: [CDS-70189]: added support for  for pipeline variables for ssh

930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandler.java, 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBlueGreenStageScaleDownRequestHandlerTest.java
Ignore workloads with no color suffix or duplicates. In the current feature we were scaling down the resources which did not had color suffix. These resources are not managed by harness so we should not scale them down. It use to show error message while trying to scale/ delete duplicates. To avoid the clutter in log messages we will remove the duplicated from the list.
<details>
- 
- Immutable delegate `trigger …
=> feat: [CDS-70928]: Avoid scaling/deleting of duplicate/ non color coded resources

260-delegate/build.properties, 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sBGRequestHandler.java, 930-delegate-tasks/src/main/java/io/harness/delegate/k8s/K8sManifestHashGenerator.java, 930-delegate-tasks/src/main/java/io/harness/delegate/task/k8s/k8sbase/K8sTaskHelperBase.java, 930-delegate-tasks/src/test/java/io/harness/delegate/k8s/K8sBGRequestHandlerTest.java
Passing env variables while calculating manifest hash. We were not passing GCP environment variables in case GKE infra due to which it was failing specifically for this case
Parent PR: https://github.com/harness/harness-core/pull/50028
tested locally
<details>
- 
</details>
<details>
You can run multiple PR check triggers by comma separating …
=> fix: [CDS-73469]: prod hotfix:  Passing env variables while calculating manifest hash

125-cd-nextgen/src/test/java/io/harness/cdng/elastigroup/ElastigroupStepCommonHelperTest.java, 260-delegate/src/test/java/software/wings/delegatetasks/k8s/K8sTaskHelperTest.java, 930-delegate-tasks/src/test/java/io/harness/delegate/task/TasValidationHandlerTest.java, bazelrc.common, pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/PMSYamlSchemaServiceImpl.java, template-service/service/src/test/java/io/harness/template/services/NGTemplateServiceImplTest.java
As part of jdk 17 upgrade steps, UTs runtime env will be changed to java 17. This requires the UTs to be compatible with it. Additionally some packages need to be open up for allowing reflective access java internals. This has been added to `bazelrc.common` file. The changes doesn't affect jdk 11 env (apart from adding illegal access harmless log for any non opened package) because packages are not restricted by default in jdk 11.
Testing:
1. No effect on services/tests when execute with java 11 runtime env
2. All test passed with java 17 runtime env
<details>
- 
- `trigger …
=> techdebt: [PL-39827]: Changes required for UTs to be able to run in java 17 runtime env

930-delegate-tasks/src/main/java/io/harness/delegate/task/jira/JiraTaskNGHandler.java, 930-delegate-tasks/src/test/java/io/harness/delegate/task/jira/JiraTaskNGHandlerTest.java, 960-api-services/src/main/java/io/harness/jira/JiraClient.java, 960-api-services/src/test/java/io/harness/jira/JiraClientTest.java, 970-api-services-beans/src/main/java/io/harness/jira/JiraConstantsNG.java
- Refactors the Jira user flow in `JiraTaskNGHandler` and shifts the flow to `JiraClient`.
- Delegate Only Change. Backward compatibility of `JiraClient` create and update calls in CG and CCM are taken care of.
- Advantage 
a. removes duplicate metadata calls in create and update flows in NG.
b. reduces `getInstanceDetails` calls to 1 per create/update flow from 3 per jira user field per create/update flow
- While refactoring adding one fast return condition if no user type fields in metadata. Also added some null checks.   
- Changed error message to include the query used.
- Dev Testing Jira User flow in NG: [Test Plan](https://docs.google.com/spreadsheets/d/1PfTDKLqKibFRfyO1dmlTkrhri_-GI8JdISfwws9njLc/edit#gid=1495506352)
- Exhaustive UTs added for different cases of Jira user flow in …
=> feat:[CDS-78286]: refactoring jira user flow to optimize jira calls

127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/mappers/ServiceFilterHelper.java, 127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImpl.java, 127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/mappers/ServiceFilterHelperTest.java, 127-cd-nextgen-entities/src/test/java/io/harness/ng/core/service/services/impl/ServiceEntityServiceImplTest.java
Issue was when includeAllAccessibleAtScope and search term both were present in service list api call, 
We adding these in query criteria through andOperator, and two andOperator are not supported in mongo.
For the fix i have made a single array of criteria including includeAllAccessibleAtScope and searchTerm both.
<details>
- 
</details>
<details>
<summary>PR Check …
=> [feat]: [CDS-79705] : fix mongo query for serviceResourceV2 list services call

360-cg-manager/src/main/java/software/wings/app/WingsApplication.java, build.properties
No microservice is using the NotifyEventConsumer and this is causing high retained memory in heapDump in manager. Removing that thread altogether.
In manager heapDump, we are seeing a lot of HKryo objects, reflect objects because of NotifyEventCgConsumer. After taking to prashanth, we got to know that no one is using the NotifyEventCgConsumer and we are going to remove it.
develop pr - https://github.com/harness/harness-core/pull/53273
Note: This is not a hotfix. We want to get this to prod faster to verify the memory reduction in manager after this change.
<details>
- 
- `trigger …
=> fix: [PL-41469]: Remove NotifyEventConsumerCg thread

100-migrator/src/main/java/io/harness/ngmigration/api/EntityDetailsResource.java, 400-rest/src/main/java/io/harness/event/handler/impl/account/AccountChangeHandler.java, 400-rest/src/main/java/software/wings/delegatetasks/buildsource/BuildSourceCleanupHelper.java, 400-rest/src/main/java/software/wings/helpers/ext/account/DeleteAccountHelper.java, 400-rest/src/main/java/software/wings/service/impl/AppServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/EnvironmentServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/HarnessTagServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/PipelineServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/ResourceLookupServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/ServiceResourceServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/UserGroupServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/instance/CloudToHarnessMappingServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/workflow/WorkflowServiceImpl.java, 400-rest/src/main/java/software/wings/service/impl/yaml/YamlGitServiceImpl.java, 956-feature-flag-beans/src/main/java/io/harness/beans/FeatureName.java
This pr does two things:
- As part of previous pr we had removed usages of CDS_QUERY_OPTIMIZATIONS as those were done quite a few months back. But I noticed these were enabled only on prod 2 globally. So I am reverting removal of those flags.
- All new changes I have created a new flag CDS_QUERY_OPTIMIZATIONS_V2 and put them behind this. This is so the changes are by default not enabled when the changes reach prod.
In future once some flag is enabled for a long time in prods we will move them to CDS_QUERY_OPTIMIZATIONS and new ones will go to V2
Hot fix pr for qa https://github.com/harness/harness-core/pull/53606
<details>
- 
- `trigger cvng …
=> fix: [CDS-79153]: Using V2 feature flag enum instead of existing one
